// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name, role, password_hash, photo_url, member_since, created_at)
VALUES ($1, $2, $3, 'reader', $4, $5, $6, $6)
RETURNING id, email, phone, name, password_hash, role, photo_url, area, district, member_since, strikes, banned, deleted_at, created_at, photo_data
`

type CreateUserParams struct {
	ID           string
	Email        pgtype.Text
	Name         string
	PasswordHash pgtype.Text
	PhotoUrl     pgtype.Text
	MemberSince  time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.PhotoUrl,
		arg.MemberSince,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.PhotoUrl,
		&i.Area,
		&i.District,
		&i.MemberSince,
		&i.Strikes,
		&i.Banned,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.PhotoData,
	)
	return i, err
}

const deletePendingSignup = `-- name: DeletePendingSignup :exec
DELETE FROM pending_signups WHERE contact = $1
`

func (q *Queries) DeletePendingSignup(ctx context.Context, contact string) error {
	_, err := q.db.Exec(ctx, deletePendingSignup, contact)
	return err
}

const getPendingSignup = `-- name: GetPendingSignup :one
SELECT contact, name, password_hash, created_at FROM pending_signups WHERE contact = $1
`

func (q *Queries) GetPendingSignup(ctx context.Context, contact string) (PendingSignup, error) {
	row := q.db.QueryRow(ctx, getPendingSignup, contact)
	var i PendingSignup
	err := row.Scan(
		&i.Contact,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           string
	PasswordHash pgtype.Text
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const upsertPendingSignup = `-- name: UpsertPendingSignup :exec
INSERT INTO pending_signups (contact, name, password_hash, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (contact) DO UPDATE
SET name = EXCLUDED.name, password_hash = EXCLUDED.password_hash, created_at = EXCLUDED.created_at
`

type UpsertPendingSignupParams struct {
	Contact      string
	Name         string
	PasswordHash string
	CreatedAt    time.Time
}

func (q *Queries) UpsertPendingSignup(ctx context.Context, arg UpsertPendingSignupParams) error {
	_, err := q.db.Exec(ctx, upsertPendingSignup,
		arg.Contact,
		arg.Name,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}
