// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpOTPAttempts = `-- name: BumpOTPAttempts :one
UPDATE otp_codes SET attempts = attempts + 1
WHERE contact = $1 AND purpose = $2
RETURNING attempts
`

type BumpOTPAttemptsParams struct {
	Contact string
	Purpose string
}

func (q *Queries) BumpOTPAttempts(ctx context.Context, arg BumpOTPAttemptsParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpOTPAttempts, arg.Contact, arg.Purpose)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const deleteOTP = `-- name: DeleteOTP :exec
DELETE FROM otp_codes WHERE contact = $1 AND purpose = $2
`

type DeleteOTPParams struct {
	Contact string
	Purpose string
}

func (q *Queries) DeleteOTP(ctx context.Context, arg DeleteOTPParams) error {
	_, err := q.db.Exec(ctx, deleteOTP, arg.Contact, arg.Purpose)
	return err
}

const getOTP = `-- name: GetOTP :one
SELECT contact, purpose, code_hash, expires_at, attempts, created_at FROM otp_codes WHERE contact = $1 AND purpose = $2
`

type GetOTPParams struct {
	Contact string
	Purpose string
}

func (q *Queries) GetOTP(ctx context.Context, arg GetOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getOTP, arg.Contact, arg.Purpose)
	var i OtpCode
	err := row.Scan(
		&i.Contact,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const getOTPForUpdate = `-- name: GetOTPForUpdate :one
SELECT contact, purpose, code_hash, expires_at, attempts, created_at FROM otp_codes WHERE contact = $1 AND purpose = $2 FOR UPDATE
`

type GetOTPForUpdateParams struct {
	Contact string
	Purpose string
}

func (q *Queries) GetOTPForUpdate(ctx context.Context, arg GetOTPForUpdateParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getOTPForUpdate, arg.Contact, arg.Purpose)
	var i OtpCode
	err := row.Scan(
		&i.Contact,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT rt.id, rt.user_id, rt.expires_at, rt.revoked_at,
       u.banned::boolean AS user_banned, (u.deleted_at IS NOT NULL)::boolean AS user_deleted
FROM refresh_tokens rt
JOIN users u ON u.id = rt.user_id
WHERE rt.token_hash = $1
FOR UPDATE OF rt
`

type GetRefreshTokenForUpdateRow struct {
	ID          string
	UserID      string
	ExpiresAt   time.Time
	RevokedAt   pgtype.Timestamptz
	UserBanned  bool
	UserDeleted bool
}

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, tokenHash string) (GetRefreshTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, tokenHash)
	var i GetRefreshTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserBanned,
		&i.UserDeleted,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRefreshTokenParams struct {
	ID        string
	UserID    string
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const pruneRefreshTokens = `-- name: PruneRefreshTokens :execrows
DELETE FROM refresh_tokens WHERE expires_at < $1
`

func (q *Queries) PruneRefreshTokens(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneRefreshTokens, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllRefreshTokens = `-- name: RevokeAllRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = $2::timestamptz
WHERE user_id = $1 AND revoked_at IS NULL
`

type RevokeAllRefreshTokensParams struct {
	UserID    string
	RevokedAt time.Time
}

func (q *Queries) RevokeAllRefreshTokens(ctx context.Context, arg RevokeAllRefreshTokensParams) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokens, arg.UserID, arg.RevokedAt)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = $2::timestamptz
WHERE id = $1 AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	ID        string
	RevokedAt time.Time
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, arg.ID, arg.RevokedAt)
	return err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :exec
UPDATE refresh_tokens SET revoked_at = $2::timestamptz
WHERE token_hash = $1 AND revoked_at IS NULL
`

type RevokeRefreshTokenByHashParams struct {
	TokenHash string
	RevokedAt time.Time
}

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, arg RevokeRefreshTokenByHashParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByHash, arg.TokenHash, arg.RevokedAt)
	return err
}

const upsertOTP = `-- name: UpsertOTP :exec
INSERT INTO otp_codes (contact, purpose, code_hash, expires_at, attempts, created_at)
VALUES ($1, $2, $3, $4, 0, $5)
ON CONFLICT (contact, purpose) DO UPDATE
SET code_hash = EXCLUDED.code_hash, expires_at = EXCLUDED.expires_at,
    attempts = 0, created_at = EXCLUDED.created_at
`

type UpsertOTPParams struct {
	Contact   string
	Purpose   string
	CodeHash  string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) UpsertOTP(ctx context.Context, arg UpsertOTPParams) error {
	_, err := q.db.Exec(ctx, upsertOTP,
		arg.Contact,
		arg.Purpose,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}
