// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bites.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBitesBy = `-- name: CountBitesBy :one
SELECT count(*)::integer FROM bites WHERE author_id = $1
`

func (q *Queries) CountBitesBy(ctx context.Context, authorID string) (int32, error) {
	row := q.db.QueryRow(ctx, countBitesBy, authorID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteBite = `-- name: DeleteBite :exec
DELETE FROM bites WHERE id = $1
`

func (q *Queries) DeleteBite(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBite, id)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM bite_comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const findBite = `-- name: FindBite :one
SELECT id, position, author_id, text, book_id, spoiler, created_at, edited_at FROM bites WHERE id = $1
`

func (q *Queries) FindBite(ctx context.Context, id string) (Bite, error) {
	row := q.db.QueryRow(ctx, findBite, id)
	var i Bite
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.AuthorID,
		&i.Text,
		&i.BookID,
		&i.Spoiler,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const findComment = `-- name: FindComment :one
SELECT id, position, bite_id, parent_id, author_id, text, created_at FROM bite_comments WHERE id = $1
`

func (q *Queries) FindComment(ctx context.Context, id string) (BiteComment, error) {
	row := q.db.QueryRow(ctx, findComment, id)
	var i BiteComment
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.BiteID,
		&i.ParentID,
		&i.AuthorID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const getBite = `-- name: GetBite :one
SELECT b.id, b.position, b.author_id, b.text, b.book_id, b.spoiler, b.created_at, b.edited_at, u.name AS author_name, u.area AS author_area,
       (SELECT count(*) FROM bite_likes l WHERE l.bite_id = b.id)::integer AS likes,
       EXISTS (SELECT 1 FROM bite_likes l WHERE l.bite_id = b.id AND l.user_id = $1::text) AS liked,
       (SELECT count(*) FROM bite_comments c WHERE c.bite_id = b.id)::integer AS comments
FROM bites b JOIN users u ON u.id = b.author_id
WHERE b.id = $2 AND u.deleted_at IS NULL
`

type GetBiteParams struct {
	Viewer string
	ID     string
}

type GetBiteRow struct {
	Bite       Bite
	AuthorName string
	AuthorArea string
	Likes      int32
	Liked      bool
	Comments   int32
}

func (q *Queries) GetBite(ctx context.Context, arg GetBiteParams) (GetBiteRow, error) {
	row := q.db.QueryRow(ctx, getBite, arg.Viewer, arg.ID)
	var i GetBiteRow
	err := row.Scan(
		&i.Bite.ID,
		&i.Bite.Position,
		&i.Bite.AuthorID,
		&i.Bite.Text,
		&i.Bite.BookID,
		&i.Bite.Spoiler,
		&i.Bite.CreatedAt,
		&i.Bite.EditedAt,
		&i.AuthorName,
		&i.AuthorArea,
		&i.Likes,
		&i.Liked,
		&i.Comments,
	)
	return i, err
}

const insertBite = `-- name: InsertBite :exec
INSERT INTO bites (id, author_id, text, book_id, spoiler, created_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertBiteParams struct {
	ID        string
	AuthorID  string
	Text      string
	BookID    pgtype.Text
	Spoiler   bool
	CreatedAt time.Time
}

func (q *Queries) InsertBite(ctx context.Context, arg InsertBiteParams) error {
	_, err := q.db.Exec(ctx, insertBite,
		arg.ID,
		arg.AuthorID,
		arg.Text,
		arg.BookID,
		arg.Spoiler,
		arg.CreatedAt,
	)
	return err
}

const insertComment = `-- name: InsertComment :exec
INSERT INTO bite_comments (id, bite_id, parent_id, author_id, text, created_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCommentParams struct {
	ID        string
	BiteID    string
	ParentID  pgtype.Text
	AuthorID  string
	Text      string
	CreatedAt time.Time
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) error {
	_, err := q.db.Exec(ctx, insertComment,
		arg.ID,
		arg.BiteID,
		arg.ParentID,
		arg.AuthorID,
		arg.Text,
		arg.CreatedAt,
	)
	return err
}

const likeBite = `-- name: LikeBite :exec
INSERT INTO bite_likes (bite_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type LikeBiteParams struct {
	BiteID string
	UserID string
}

func (q *Queries) LikeBite(ctx context.Context, arg LikeBiteParams) error {
	_, err := q.db.Exec(ctx, likeBite, arg.BiteID, arg.UserID)
	return err
}

const listBiteComments = `-- name: ListBiteComments :many
SELECT c.id, c.position, c.bite_id, c.parent_id, c.author_id, c.text, c.created_at, u.name AS author_name
FROM bite_comments c JOIN users u ON u.id = c.author_id
WHERE c.bite_id = $1 ORDER BY c.position
`

type ListBiteCommentsRow struct {
	ID         string
	Position   int64
	BiteID     string
	ParentID   pgtype.Text
	AuthorID   string
	Text       string
	CreatedAt  time.Time
	AuthorName string
}

func (q *Queries) ListBiteComments(ctx context.Context, biteID string) ([]ListBiteCommentsRow, error) {
	rows, err := q.db.Query(ctx, listBiteComments, biteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBiteCommentsRow{}
	for rows.Next() {
		var i ListBiteCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.BiteID,
			&i.ParentID,
			&i.AuthorID,
			&i.Text,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBites = `-- name: ListBites :many
SELECT b.id, b.position, b.author_id, b.text, b.book_id, b.spoiler, b.created_at, b.edited_at, u.name AS author_name, u.area AS author_area,
       (SELECT count(*) FROM bite_likes l WHERE l.bite_id = b.id)::integer AS likes,
       EXISTS (SELECT 1 FROM bite_likes l WHERE l.bite_id = b.id AND l.user_id = $1::text) AS liked,
       (SELECT count(*) FROM bite_comments c WHERE c.bite_id = b.id)::integer AS comments
FROM bites b JOIN users u ON u.id = b.author_id
WHERE u.deleted_at IS NULL AND NOT u.banned
  AND NOT (b.author_id = ANY ($2::text[]))
  AND (NOT $3::boolean OR b.author_id = ANY ($4::text[]))
  AND ($5::text IS NULL OR b.book_id = $5::text)
  AND ($6::text IS NULL OR b.author_id = $6::text)
ORDER BY b.created_at DESC, b.position DESC
LIMIT 30
`

type ListBitesParams struct {
	Viewer        string
	Hidden        []string
	OnlyFollowing bool
	Following     []string
	BookID        pgtype.Text
	AuthorID      pgtype.Text
}

type ListBitesRow struct {
	Bite       Bite
	AuthorName string
	AuthorArea string
	Likes      int32
	Liked      bool
	Comments   int32
}

// A feed, newest first, at most 30: authors that are deleted, banned or hidden from the viewer
// (blocks either way) are left out.
func (q *Queries) ListBites(ctx context.Context, arg ListBitesParams) ([]ListBitesRow, error) {
	rows, err := q.db.Query(ctx, listBites,
		arg.Viewer,
		arg.Hidden,
		arg.OnlyFollowing,
		arg.Following,
		arg.BookID,
		arg.AuthorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBitesRow{}
	for rows.Next() {
		var i ListBitesRow
		if err := rows.Scan(
			&i.Bite.ID,
			&i.Bite.Position,
			&i.Bite.AuthorID,
			&i.Bite.Text,
			&i.Bite.BookID,
			&i.Bite.Spoiler,
			&i.Bite.CreatedAt,
			&i.Bite.EditedAt,
			&i.AuthorName,
			&i.AuthorArea,
			&i.Likes,
			&i.Liked,
			&i.Comments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedBite = `-- name: SeedBite :exec
INSERT INTO bites (id, author_id, text, book_id, spoiler, created_at) VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (id) DO NOTHING
`

type SeedBiteParams struct {
	ID        string
	AuthorID  string
	Text      string
	BookID    pgtype.Text
	Spoiler   bool
	CreatedAt time.Time
}

func (q *Queries) SeedBite(ctx context.Context, arg SeedBiteParams) error {
	_, err := q.db.Exec(ctx, seedBite,
		arg.ID,
		arg.AuthorID,
		arg.Text,
		arg.BookID,
		arg.Spoiler,
		arg.CreatedAt,
	)
	return err
}

const seedComment = `-- name: SeedComment :exec
INSERT INTO bite_comments (id, bite_id, parent_id, author_id, text, created_at) VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (id) DO NOTHING
`

type SeedCommentParams struct {
	ID        string
	BiteID    string
	ParentID  pgtype.Text
	AuthorID  string
	Text      string
	CreatedAt time.Time
}

func (q *Queries) SeedComment(ctx context.Context, arg SeedCommentParams) error {
	_, err := q.db.Exec(ctx, seedComment,
		arg.ID,
		arg.BiteID,
		arg.ParentID,
		arg.AuthorID,
		arg.Text,
		arg.CreatedAt,
	)
	return err
}

const seedLike = `-- name: SeedLike :exec
INSERT INTO bite_likes (bite_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type SeedLikeParams struct {
	BiteID string
	UserID string
}

func (q *Queries) SeedLike(ctx context.Context, arg SeedLikeParams) error {
	_, err := q.db.Exec(ctx, seedLike, arg.BiteID, arg.UserID)
	return err
}

const unlikeBite = `-- name: UnlikeBite :exec
DELETE FROM bite_likes WHERE bite_id = $1 AND user_id = $2
`

type UnlikeBiteParams struct {
	BiteID string
	UserID string
}

func (q *Queries) UnlikeBite(ctx context.Context, arg UnlikeBiteParams) error {
	_, err := q.db.Exec(ctx, unlikeBite, arg.BiteID, arg.UserID)
	return err
}

const updateBite = `-- name: UpdateBite :exec
UPDATE bites SET text = $2, book_id = $3, spoiler = $4, edited_at = $5 WHERE id = $1
`

type UpdateBiteParams struct {
	ID       string
	Text     string
	BookID   pgtype.Text
	Spoiler  bool
	EditedAt pgtype.Timestamptz
}

func (q *Queries) UpdateBite(ctx context.Context, arg UpdateBiteParams) error {
	_, err := q.db.Exec(ctx, updateBite,
		arg.ID,
		arg.Text,
		arg.BookID,
		arg.Spoiler,
		arg.EditedAt,
	)
	return err
}
