// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bookrequest.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeBookRequest = `-- name: CloseBookRequest :execrows
UPDATE book_requests SET is_open = false WHERE id = $1 AND requester_id = $2
`

type CloseBookRequestParams struct {
	ID          string
	RequesterID string
}

func (q *Queries) CloseBookRequest(ctx context.Context, arg CloseBookRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeBookRequest, arg.ID, arg.RequesterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertBookRequest = `-- name: InsertBookRequest :exec
INSERT INTO book_requests (id, requester_id, title, author, book_id, max_price_bdt, note, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertBookRequestParams struct {
	ID          string
	RequesterID string
	Title       string
	Author      pgtype.Text
	BookID      pgtype.Text
	MaxPriceBdt pgtype.Int4
	Note        pgtype.Text
	CreatedAt   time.Time
}

func (q *Queries) InsertBookRequest(ctx context.Context, arg InsertBookRequestParams) error {
	_, err := q.db.Exec(ctx, insertBookRequest,
		arg.ID,
		arg.RequesterID,
		arg.Title,
		arg.Author,
		arg.BookID,
		arg.MaxPriceBdt,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}

const listBookRequestsOf = `-- name: ListBookRequestsOf :many
SELECT id, position, requester_id, title, author, book_id, max_price_bdt, note, is_open, created_at FROM book_requests WHERE requester_id = $1 ORDER BY position DESC
`

func (q *Queries) ListBookRequestsOf(ctx context.Context, requesterID string) ([]BookRequest, error) {
	rows, err := q.db.Query(ctx, listBookRequestsOf, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookRequest{}
	for rows.Next() {
		var i BookRequest
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.RequesterID,
			&i.Title,
			&i.Author,
			&i.BookID,
			&i.MaxPriceBdt,
			&i.Note,
			&i.IsOpen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenBookRequests = `-- name: ListOpenBookRequests :many
SELECT id, position, requester_id, title, author, book_id, max_price_bdt, note, is_open, created_at FROM book_requests WHERE is_open ORDER BY position
`

func (q *Queries) ListOpenBookRequests(ctx context.Context) ([]BookRequest, error) {
	rows, err := q.db.Query(ctx, listOpenBookRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookRequest{}
	for rows.Next() {
		var i BookRequest
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.RequesterID,
			&i.Title,
			&i.Author,
			&i.BookID,
			&i.MaxPriceBdt,
			&i.Note,
			&i.IsOpen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenBookRequestsOfOthers = `-- name: ListOpenBookRequestsOfOthers :many
SELECT r.id, r.position, r.requester_id, r.title, r.author, r.book_id, r.max_price_bdt, r.note, r.is_open, r.created_at, u.name AS requester_name FROM book_requests r JOIN users u ON u.id = r.requester_id
WHERE r.is_open AND r.requester_id <> $1 AND u.deleted_at IS NULL ORDER BY r.position DESC
`

type ListOpenBookRequestsOfOthersRow struct {
	ID            string
	Position      int64
	RequesterID   string
	Title         string
	Author        pgtype.Text
	BookID        pgtype.Text
	MaxPriceBdt   pgtype.Int4
	Note          pgtype.Text
	IsOpen        bool
	CreatedAt     time.Time
	RequesterName string
}

func (q *Queries) ListOpenBookRequestsOfOthers(ctx context.Context, requesterID string) ([]ListOpenBookRequestsOfOthersRow, error) {
	rows, err := q.db.Query(ctx, listOpenBookRequestsOfOthers, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenBookRequestsOfOthersRow{}
	for rows.Next() {
		var i ListOpenBookRequestsOfOthersRow
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.RequesterID,
			&i.Title,
			&i.Author,
			&i.BookID,
			&i.MaxPriceBdt,
			&i.Note,
			&i.IsOpen,
			&i.CreatedAt,
			&i.RequesterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedBookRequest = `-- name: SeedBookRequest :exec
INSERT INTO book_requests (id, requester_id, title, author, book_id, max_price_bdt, note, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) ON CONFLICT (id) DO NOTHING
`

type SeedBookRequestParams struct {
	ID          string
	RequesterID string
	Title       string
	Author      pgtype.Text
	BookID      pgtype.Text
	MaxPriceBdt pgtype.Int4
	Note        pgtype.Text
	CreatedAt   time.Time
}

func (q *Queries) SeedBookRequest(ctx context.Context, arg SeedBookRequestParams) error {
	_, err := q.db.Exec(ctx, seedBookRequest,
		arg.ID,
		arg.RequesterID,
		arg.Title,
		arg.Author,
		arg.BookID,
		arg.MaxPriceBdt,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}
