// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: buying.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_lines WHERE user_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, clearCart, userID)
	return err
}

const deleteAlert = `-- name: DeleteAlert :exec
DELETE FROM alerts WHERE user_id = $1 AND id = $2
`

type DeleteAlertParams struct {
	UserID string
	ID     string
}

func (q *Queries) DeleteAlert(ctx context.Context, arg DeleteAlertParams) error {
	_, err := q.db.Exec(ctx, deleteAlert, arg.UserID, arg.ID)
	return err
}

const deleteAlertsOfKind = `-- name: DeleteAlertsOfKind :exec
DELETE FROM alerts WHERE user_id = $1 AND kind = $2 AND edition_id = $3
`

type DeleteAlertsOfKindParams struct {
	UserID    string
	Kind      string
	EditionID string
}

func (q *Queries) DeleteAlertsOfKind(ctx context.Context, arg DeleteAlertsOfKindParams) error {
	_, err := q.db.Exec(ctx, deleteAlertsOfKind, arg.UserID, arg.Kind, arg.EditionID)
	return err
}

const deleteCartLine = `-- name: DeleteCartLine :exec
DELETE FROM cart_lines WHERE user_id = $1 AND kind = $2 AND item_id = $3
`

type DeleteCartLineParams struct {
	UserID string
	Kind   string
	ItemID string
}

func (q *Queries) DeleteCartLine(ctx context.Context, arg DeleteCartLineParams) error {
	_, err := q.db.Exec(ctx, deleteCartLine, arg.UserID, arg.Kind, arg.ItemID)
	return err
}

const getCartLine = `-- name: GetCartLine :one
SELECT user_id, kind, item_id, position, quantity, added_at FROM cart_lines WHERE user_id = $1 AND kind = $2 AND item_id = $3 FOR UPDATE
`

type GetCartLineParams struct {
	UserID string
	Kind   string
	ItemID string
}

func (q *Queries) GetCartLine(ctx context.Context, arg GetCartLineParams) (CartLine, error) {
	row := q.db.QueryRow(ctx, getCartLine, arg.UserID, arg.Kind, arg.ItemID)
	var i CartLine
	err := row.Scan(
		&i.UserID,
		&i.Kind,
		&i.ItemID,
		&i.Position,
		&i.Quantity,
		&i.AddedAt,
	)
	return i, err
}

const getShareByID = `-- name: GetShareByID :one
SELECT id, user_id, owner_name FROM wishlist_shares WHERE id = $1
`

func (q *Queries) GetShareByID(ctx context.Context, id string) (WishlistShare, error) {
	row := q.db.QueryRow(ctx, getShareByID, id)
	var i WishlistShare
	err := row.Scan(&i.ID, &i.UserID, &i.OwnerName)
	return i, err
}

const getShareByUser = `-- name: GetShareByUser :one
SELECT id, user_id, owner_name FROM wishlist_shares WHERE user_id = $1
`

func (q *Queries) GetShareByUser(ctx context.Context, userID string) (WishlistShare, error) {
	row := q.db.QueryRow(ctx, getShareByUser, userID)
	var i WishlistShare
	err := row.Scan(&i.ID, &i.UserID, &i.OwnerName)
	return i, err
}

const insertAlert = `-- name: InsertAlert :exec
INSERT INTO alerts (id, user_id, kind, book_id, edition_id, target_price_bdt, fired_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAlertParams struct {
	ID             string
	UserID         string
	Kind           string
	BookID         string
	EditionID      string
	TargetPriceBdt pgtype.Int4
	FiredAt        pgtype.Timestamptz
}

func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) error {
	_, err := q.db.Exec(ctx, insertAlert,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.BookID,
		arg.EditionID,
		arg.TargetPriceBdt,
		arg.FiredAt,
	)
	return err
}

const insertCartLine = `-- name: InsertCartLine :exec
INSERT INTO cart_lines (user_id, kind, item_id, quantity, added_at) VALUES ($1, $2, $3, $4, $5)
`

type InsertCartLineParams struct {
	UserID   string
	Kind     string
	ItemID   string
	Quantity int32
	AddedAt  time.Time
}

func (q *Queries) InsertCartLine(ctx context.Context, arg InsertCartLineParams) error {
	_, err := q.db.Exec(ctx, insertCartLine,
		arg.UserID,
		arg.Kind,
		arg.ItemID,
		arg.Quantity,
		arg.AddedAt,
	)
	return err
}

const listAlerts = `-- name: ListAlerts :many
SELECT id, user_id, position, kind, book_id, edition_id, target_price_bdt, fired_at FROM alerts WHERE user_id = $1 ORDER BY position
`

func (q *Queries) ListAlerts(ctx context.Context, userID string) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlerts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Position,
			&i.Kind,
			&i.BookID,
			&i.EditionID,
			&i.TargetPriceBdt,
			&i.FiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBundles = `-- name: ListBundles :many
SELECT id, position, title, edition_ids, price_bdt FROM bundles ORDER BY position
`

func (q *Queries) ListBundles(ctx context.Context) ([]Bundle, error) {
	rows, err := q.db.Query(ctx, listBundles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bundle{}
	for rows.Next() {
		var i Bundle
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Title,
			&i.EditionIds,
			&i.PriceBdt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCartLines = `-- name: ListCartLines :many
SELECT user_id, kind, item_id, position, quantity, added_at FROM cart_lines WHERE user_id = $1 ORDER BY position
`

func (q *Queries) ListCartLines(ctx context.Context, userID string) ([]CartLine, error) {
	rows, err := q.db.Query(ctx, listCartLines, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartLine{}
	for rows.Next() {
		var i CartLine
		if err := rows.Scan(
			&i.UserID,
			&i.Kind,
			&i.ItemID,
			&i.Position,
			&i.Quantity,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlashItems = `-- name: ListFlashItems :many
SELECT edition_id, position, price_bdt FROM flash_sale_items ORDER BY position
`

func (q *Queries) ListFlashItems(ctx context.Context) ([]FlashSaleItem, error) {
	rows, err := q.db.Query(ctx, listFlashItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlashSaleItem{}
	for rows.Next() {
		var i FlashSaleItem
		if err := rows.Scan(&i.EditionID, &i.Position, &i.PriceBdt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreorders = `-- name: ListPreorders :many
SELECT edition_id, position FROM preorders ORDER BY position
`

func (q *Queries) ListPreorders(ctx context.Context) ([]Preorder, error) {
	rows, err := q.db.Query(ctx, listPreorders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preorder{}
	for rows.Next() {
		var i Preorder
		if err := rows.Scan(&i.EditionID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnfiredAlerts = `-- name: ListUnfiredAlerts :many
SELECT id, user_id, position, kind, book_id, edition_id, target_price_bdt, fired_at FROM alerts WHERE fired_at IS NULL ORDER BY position
`

func (q *Queries) ListUnfiredAlerts(ctx context.Context) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listUnfiredAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Position,
			&i.Kind,
			&i.BookID,
			&i.EditionID,
			&i.TargetPriceBdt,
			&i.FiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWishlistBookIDs = `-- name: ListWishlistBookIDs :many
SELECT book_id FROM wishlist_items WHERE user_id = $1 ORDER BY added_at DESC, book_id
`

func (q *Queries) ListWishlistBookIDs(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listWishlistBookIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var book_id string
		if err := rows.Scan(&book_id); err != nil {
			return nil, err
		}
		items = append(items, book_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlertFired = `-- name: MarkAlertFired :execrows
UPDATE alerts SET fired_at = $2 WHERE id = $1 AND fired_at IS NULL
`

type MarkAlertFiredParams struct {
	ID      string
	FiredAt pgtype.Timestamptz
}

func (q *Queries) MarkAlertFired(ctx context.Context, arg MarkAlertFiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAlertFired, arg.ID, arg.FiredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeWishlistItem = `-- name: RemoveWishlistItem :exec
DELETE FROM wishlist_items WHERE user_id = $1 AND book_id = $2
`

type RemoveWishlistItemParams struct {
	UserID string
	BookID string
}

func (q *Queries) RemoveWishlistItem(ctx context.Context, arg RemoveWishlistItemParams) error {
	_, err := q.db.Exec(ctx, removeWishlistItem, arg.UserID, arg.BookID)
	return err
}

const saveWishlistItem = `-- name: SaveWishlistItem :exec
INSERT INTO wishlist_items (user_id, book_id, added_at) VALUES ($1, $2, $3)
ON CONFLICT (user_id, book_id) DO UPDATE SET added_at = EXCLUDED.added_at
`

type SaveWishlistItemParams struct {
	UserID  string
	BookID  string
	AddedAt time.Time
}

func (q *Queries) SaveWishlistItem(ctx context.Context, arg SaveWishlistItemParams) error {
	_, err := q.db.Exec(ctx, saveWishlistItem, arg.UserID, arg.BookID, arg.AddedAt)
	return err
}

const setCartQuantity = `-- name: SetCartQuantity :exec
UPDATE cart_lines SET quantity = $4 WHERE user_id = $1 AND kind = $2 AND item_id = $3
`

type SetCartQuantityParams struct {
	UserID   string
	Kind     string
	ItemID   string
	Quantity int32
}

func (q *Queries) SetCartQuantity(ctx context.Context, arg SetCartQuantityParams) error {
	_, err := q.db.Exec(ctx, setCartQuantity,
		arg.UserID,
		arg.Kind,
		arg.ItemID,
		arg.Quantity,
	)
	return err
}

const upsertShare = `-- name: UpsertShare :exec
INSERT INTO wishlist_shares (id, user_id, owner_name) VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET owner_name = EXCLUDED.owner_name
`

type UpsertShareParams struct {
	ID        string
	UserID    string
	OwnerName string
}

func (q *Queries) UpsertShare(ctx context.Context, arg UpsertShareParams) error {
	_, err := q.db.Exec(ctx, upsertShare, arg.ID, arg.UserID, arg.OwnerName)
	return err
}
