// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: catalog.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOwnBooklist = `-- name: DeleteOwnBooklist :execrows
DELETE FROM booklists WHERE id = $1 AND owner_id = $2
`

type DeleteOwnBooklistParams struct {
	ID      string
	OwnerID pgtype.Text
}

func (q *Queries) DeleteOwnBooklist(ctx context.Context, arg DeleteOwnBooklistParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOwnBooklist, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBookDetails = `-- name: GetBookDetails :one
SELECT book_id, description, pages FROM book_details WHERE book_id = $1
`

func (q *Queries) GetBookDetails(ctx context.Context, bookID string) (BookDetail, error) {
	row := q.db.QueryRow(ctx, getBookDetails, bookID)
	var i BookDetail
	err := row.Scan(&i.BookID, &i.Description, &i.Pages)
	return i, err
}

const getBooklist = `-- name: GetBooklist :one
SELECT id, position, owner_id, kind, title_en, title_bn, note_en, note_bn, book_ids, updated_at FROM booklists WHERE id = $1
`

func (q *Queries) GetBooklist(ctx context.Context, id string) (Booklist, error) {
	row := q.db.QueryRow(ctx, getBooklist, id)
	var i Booklist
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.OwnerID,
		&i.Kind,
		&i.TitleEn,
		&i.TitleBn,
		&i.NoteEn,
		&i.NoteBn,
		&i.BookIds,
		&i.UpdatedAt,
	)
	return i, err
}

const getLookInside = `-- name: GetLookInside :one
SELECT book_id, contents, sample_pages FROM look_inside WHERE book_id = $1
`

func (q *Queries) GetLookInside(ctx context.Context, bookID string) (LookInside, error) {
	row := q.db.QueryRow(ctx, getLookInside, bookID)
	var i LookInside
	err := row.Scan(&i.BookID, &i.Contents, &i.SamplePages)
	return i, err
}

const insertAnswer = `-- name: InsertAnswer :exec
INSERT INTO book_answers (id, question_id, user_id, author_name, text, answered_at, is_staff)
SELECT $1, q.id, $3, $4, $5, $6, $7 FROM book_questions q WHERE q.id = $2 AND q.book_id = $8
`

type InsertAnswerParams struct {
	ID         string
	ID_2       string
	UserID     pgtype.Text
	AuthorName string
	Text       string
	AnsweredAt time.Time
	IsStaff    bool
	BookID     string
}

func (q *Queries) InsertAnswer(ctx context.Context, arg InsertAnswerParams) error {
	_, err := q.db.Exec(ctx, insertAnswer,
		arg.ID,
		arg.ID_2,
		arg.UserID,
		arg.AuthorName,
		arg.Text,
		arg.AnsweredAt,
		arg.IsStaff,
		arg.BookID,
	)
	return err
}

const insertBooklist = `-- name: InsertBooklist :one
INSERT INTO booklists (id, owner_id, kind, title_en, title_bn, book_ids, updated_at)
VALUES ($1, $2, 'personal', $3, $3, $4, $5)
RETURNING id, position, owner_id, kind, title_en, title_bn, note_en, note_bn, book_ids, updated_at
`

type InsertBooklistParams struct {
	ID        string
	OwnerID   pgtype.Text
	TitleEn   string
	BookIds   []string
	UpdatedAt time.Time
}

func (q *Queries) InsertBooklist(ctx context.Context, arg InsertBooklistParams) (Booklist, error) {
	row := q.db.QueryRow(ctx, insertBooklist,
		arg.ID,
		arg.OwnerID,
		arg.TitleEn,
		arg.BookIds,
		arg.UpdatedAt,
	)
	var i Booklist
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.OwnerID,
		&i.Kind,
		&i.TitleEn,
		&i.TitleBn,
		&i.NoteEn,
		&i.NoteBn,
		&i.BookIds,
		&i.UpdatedAt,
	)
	return i, err
}

const insertQuestion = `-- name: InsertQuestion :exec
INSERT INTO book_questions (id, book_id, user_id, asker_name, text, asked_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertQuestionParams struct {
	ID        string
	BookID    string
	UserID    pgtype.Text
	AskerName string
	Text      string
	AskedAt   time.Time
}

func (q *Queries) InsertQuestion(ctx context.Context, arg InsertQuestionParams) error {
	_, err := q.db.Exec(ctx, insertQuestion,
		arg.ID,
		arg.BookID,
		arg.UserID,
		arg.AskerName,
		arg.Text,
		arg.AskedAt,
	)
	return err
}

const listAnswersForBook = `-- name: ListAnswersForBook :many
SELECT a.id, a.position, a.question_id, a.user_id, a.author_name, a.text, a.answered_at, a.is_staff FROM book_answers a
JOIN book_questions q ON q.id = a.question_id
WHERE q.book_id = $1
ORDER BY a.position
`

func (q *Queries) ListAnswersForBook(ctx context.Context, bookID string) ([]BookAnswer, error) {
	rows, err := q.db.Query(ctx, listAnswersForBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookAnswer{}
	for rows.Next() {
		var i BookAnswer
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.QuestionID,
			&i.UserID,
			&i.AuthorName,
			&i.Text,
			&i.AnsweredAt,
			&i.IsStaff,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, name_bn, bio FROM authors ORDER BY id
`

func (q *Queries) ListAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.db.Query(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Author{}
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameBn,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooklists = `-- name: ListBooklists :many
SELECT id, position, owner_id, kind, title_en, title_bn, note_en, note_bn, book_ids, updated_at FROM booklists
WHERE owner_id IS NULL OR owner_id = $1::text
ORDER BY position
`

func (q *Queries) ListBooklists(ctx context.Context, viewer string) ([]Booklist, error) {
	rows, err := q.db.Query(ctx, listBooklists, viewer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booklist{}
	for rows.Next() {
		var i Booklist
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.OwnerID,
			&i.Kind,
			&i.TitleEn,
			&i.TitleBn,
			&i.NoteEn,
			&i.NoteBn,
			&i.BookIds,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooks = `-- name: ListBooks :many
SELECT id, position, title, title_bn, short_title, author, author_id, publisher_id, category_id, section, original_language, added_at, rating, tags, cover_seed, hidden, classes, exams, subject_id FROM books ORDER BY position
`

func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Title,
			&i.TitleBn,
			&i.ShortTitle,
			&i.Author,
			&i.AuthorID,
			&i.PublisherID,
			&i.CategoryID,
			&i.Section,
			&i.OriginalLanguage,
			&i.AddedAt,
			&i.Rating,
			&i.Tags,
			&i.CoverSeed,
			&i.Hidden,
			&i.Classes,
			&i.Exams,
			&i.SubjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, section, name_en, name_bn FROM categories ORDER BY id
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Section,
			&i.NameEn,
			&i.NameBn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollections = `-- name: ListCollections :many
SELECT id, position, title_en, title_bn, note_en, note_bn, section, expert_id, book_ids FROM collections ORDER BY position
`

func (q *Queries) ListCollections(ctx context.Context) ([]Collection, error) {
	rows, err := q.db.Query(ctx, listCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.TitleEn,
			&i.TitleBn,
			&i.NoteEn,
			&i.NoteBn,
			&i.Section,
			&i.ExpertID,
			&i.BookIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEditions = `-- name: ListEditions :many
SELECT id, book_id, position, format, language, price_bdt, list_price_bdt, stock, is_preorder, isbn FROM editions ORDER BY book_id, position
`

func (q *Queries) ListEditions(ctx context.Context) ([]Edition, error) {
	rows, err := q.db.Query(ctx, listEditions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edition{}
	for rows.Next() {
		var i Edition
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Position,
			&i.Format,
			&i.Language,
			&i.PriceBdt,
			&i.ListPriceBdt,
			&i.Stock,
			&i.IsPreorder,
			&i.Isbn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExperts = `-- name: ListExperts :many
SELECT id, position, name, name_bn, credential_en, credential_bn, kind, verified FROM experts ORDER BY position
`

func (q *Queries) ListExperts(ctx context.Context) ([]Expert, error) {
	rows, err := q.db.Query(ctx, listExperts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expert{}
	for rows.Next() {
		var i Expert
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Name,
			&i.NameBn,
			&i.CredentialEn,
			&i.CredentialBn,
			&i.Kind,
			&i.Verified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceLows = `-- name: ListPriceLows :many
SELECT edition_id, low_bdt, since FROM price_lows
`

func (q *Queries) ListPriceLows(ctx context.Context) ([]PriceLow, error) {
	rows, err := q.db.Query(ctx, listPriceLows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceLow{}
	for rows.Next() {
		var i PriceLow
		if err := rows.Scan(&i.EditionID, &i.LowBdt, &i.Since); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishers = `-- name: ListPublishers :many
SELECT id, name, name_bn FROM publishers ORDER BY id
`

func (q *Queries) ListPublishers(ctx context.Context) ([]Publisher, error) {
	rows, err := q.db.Query(ctx, listPublishers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Publisher{}
	for rows.Next() {
		var i Publisher
		if err := rows.Scan(&i.ID, &i.Name, &i.NameBn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestions = `-- name: ListQuestions :many
SELECT id, position, book_id, user_id, asker_name, text, asked_at FROM book_questions WHERE book_id = $1 ORDER BY position
`

func (q *Queries) ListQuestions(ctx context.Context, bookID string) ([]BookQuestion, error) {
	rows, err := q.db.Query(ctx, listQuestions, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookQuestion{}
	for rows.Next() {
		var i BookQuestion
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.BookID,
			&i.UserID,
			&i.AskerName,
			&i.Text,
			&i.AskedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesSince = `-- name: ListSalesSince :many
SELECT edition_id, sum(copies)::int AS copies FROM sales_by_month
WHERE month >= $1 GROUP BY edition_id
`

type ListSalesSinceRow struct {
	EditionID string
	Copies    int32
}

func (q *Queries) ListSalesSince(ctx context.Context, month time.Time) ([]ListSalesSinceRow, error) {
	rows, err := q.db.Query(ctx, listSalesSince, month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesSinceRow{}
	for rows.Next() {
		var i ListSalesSinceRow
		if err := rows.Scan(&i.EditionID, &i.Copies); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeries = `-- name: ListSeries :many
SELECT id, position, name, entries FROM series ORDER BY position
`

func (q *Queries) ListSeries(ctx context.Context) ([]Series, error) {
	rows, err := q.db.Query(ctx, listSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Name,
			&i.Entries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, name_en, name_bn FROM subjects ORDER BY id
`

func (q *Queries) ListSubjects(ctx context.Context) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subject{}
	for rows.Next() {
		var i Subject
		if err := rows.Scan(&i.ID, &i.NameEn, &i.NameBn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBooklist = `-- name: UpdateBooklist :one
UPDATE booklists SET title_en = $2, title_bn = $3, book_ids = $4, updated_at = $5
WHERE id = $1
RETURNING id, position, owner_id, kind, title_en, title_bn, note_en, note_bn, book_ids, updated_at
`

type UpdateBooklistParams struct {
	ID        string
	TitleEn   string
	TitleBn   string
	BookIds   []string
	UpdatedAt time.Time
}

func (q *Queries) UpdateBooklist(ctx context.Context, arg UpdateBooklistParams) (Booklist, error) {
	row := q.db.QueryRow(ctx, updateBooklist,
		arg.ID,
		arg.TitleEn,
		arg.TitleBn,
		arg.BookIds,
		arg.UpdatedAt,
	)
	var i Booklist
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.OwnerID,
		&i.Kind,
		&i.TitleEn,
		&i.TitleBn,
		&i.NoteEn,
		&i.NoteBn,
		&i.BookIds,
		&i.UpdatedAt,
	)
	return i, err
}
