// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: catalog_admin.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const bookIDs = `-- name: BookIDs :many
SELECT id FROM books
`

func (q *Queries) BookIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, bookIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBooksUsing = `-- name: CountBooksUsing :one
SELECT count(*) FROM books
WHERE ($1::text = 'category' AND category_id = $2::text)
   OR ($1::text = 'author' AND author_id = $2::text)
   OR ($1::text = 'publisher' AND publisher_id = $2::text)
`

type CountBooksUsingParams struct {
	Kind string
	ID   string
}

func (q *Queries) CountBooksUsing(ctx context.Context, arg CountBooksUsingParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBooksUsing, arg.Kind, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAuthor = `-- name: DeleteAuthor :execrows
DELETE FROM authors WHERE id = $1
`

func (q *Queries) DeleteAuthor(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuthor, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCollection = `-- name: DeleteCollection :execrows
DELETE FROM collections WHERE id = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCollection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEditionsExcept = `-- name: DeleteEditionsExcept :exec
DELETE FROM editions WHERE book_id = $1 AND NOT (id = ANY($2::text[]))
`

type DeleteEditionsExceptParams struct {
	BookID  string
	Column2 []string
}

func (q *Queries) DeleteEditionsExcept(ctx context.Context, arg DeleteEditionsExceptParams) error {
	_, err := q.db.Exec(ctx, deleteEditionsExcept, arg.BookID, arg.Column2)
	return err
}

const deletePublisher = `-- name: DeletePublisher :execrows
DELETE FROM publishers WHERE id = $1
`

func (q *Queries) DeletePublisher(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePublisher, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaffBooklist = `-- name: DeleteStaffBooklist :execrows
DELETE FROM booklists WHERE id = $1 AND owner_id IS NULL
`

func (q *Queries) DeleteStaffBooklist(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaffBooklist, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expertExists = `-- name: ExpertExists :one
SELECT EXISTS (SELECT 1 FROM experts WHERE id = $1)
`

func (q *Queries) ExpertExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, expertExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, name_bn, bio, position FROM authors WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAuthor(ctx context.Context, id string) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthor, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameBn,
		&i.Bio,
		&i.Position,
	)
	return i, err
}

const getBookForUpdate = `-- name: GetBookForUpdate :one
SELECT id, position, title, title_bn, short_title, author, author_id, publisher_id, category_id, section, original_language, added_at, rating, tags, cover_seed, hidden, classes, exams, subject_id FROM books WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetBookForUpdate(ctx context.Context, id string) (Book, error) {
	row := q.db.QueryRow(ctx, getBookForUpdate, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.Title,
		&i.TitleBn,
		&i.ShortTitle,
		&i.Author,
		&i.AuthorID,
		&i.PublisherID,
		&i.CategoryID,
		&i.Section,
		&i.OriginalLanguage,
		&i.AddedAt,
		&i.Rating,
		&i.Tags,
		&i.CoverSeed,
		&i.Hidden,
		&i.Classes,
		&i.Exams,
		&i.SubjectID,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, section, name_en, name_bn, position FROM categories WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetCategory(ctx context.Context, id string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Section,
		&i.NameEn,
		&i.NameBn,
		&i.Position,
	)
	return i, err
}

const getEditionForUpdate = `-- name: GetEditionForUpdate :one
SELECT id, book_id, position, format, language, price_bdt, list_price_bdt, stock, is_preorder, isbn FROM editions WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetEditionForUpdate(ctx context.Context, id string) (Edition, error) {
	row := q.db.QueryRow(ctx, getEditionForUpdate, id)
	var i Edition
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Position,
		&i.Format,
		&i.Language,
		&i.PriceBdt,
		&i.ListPriceBdt,
		&i.Stock,
		&i.IsPreorder,
		&i.Isbn,
	)
	return i, err
}

const getPriceLow = `-- name: GetPriceLow :one
SELECT edition_id, low_bdt, since FROM price_lows WHERE edition_id = $1
`

func (q *Queries) GetPriceLow(ctx context.Context, editionID string) (PriceLow, error) {
	row := q.db.QueryRow(ctx, getPriceLow, editionID)
	var i PriceLow
	err := row.Scan(&i.EditionID, &i.LowBdt, &i.Since)
	return i, err
}

const insertBook = `-- name: InsertBook :exec
INSERT INTO books (id, title, title_bn, short_title, author, author_id, publisher_id, category_id, section,
                   original_language, added_at, rating, tags, cover_seed, hidden, classes, exams, subject_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
`

type InsertBookParams struct {
	ID               string
	Title            string
	TitleBn          pgtype.Text
	ShortTitle       pgtype.Text
	Author           string
	AuthorID         string
	PublisherID      string
	CategoryID       string
	Section          string
	OriginalLanguage string
	AddedAt          time.Time
	Rating           float64
	Tags             []string
	CoverSeed        int32
	Hidden           bool
	Classes          []int32
	Exams            []string
	SubjectID        pgtype.Text
}

func (q *Queries) InsertBook(ctx context.Context, arg InsertBookParams) error {
	_, err := q.db.Exec(ctx, insertBook,
		arg.ID,
		arg.Title,
		arg.TitleBn,
		arg.ShortTitle,
		arg.Author,
		arg.AuthorID,
		arg.PublisherID,
		arg.CategoryID,
		arg.Section,
		arg.OriginalLanguage,
		arg.AddedAt,
		arg.Rating,
		arg.Tags,
		arg.CoverSeed,
		arg.Hidden,
		arg.Classes,
		arg.Exams,
		arg.SubjectID,
	)
	return err
}

const listCollectionIDs = `-- name: ListCollectionIDs :many
SELECT id FROM collections
`

func (q *Queries) ListCollectionIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listCollectionIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEditionsOfBook = `-- name: ListEditionsOfBook :many
SELECT id, book_id, position, format, language, price_bdt, list_price_bdt, stock, is_preorder, isbn FROM editions WHERE book_id = $1 ORDER BY position
`

func (q *Queries) ListEditionsOfBook(ctx context.Context, bookID string) ([]Edition, error) {
	rows, err := q.db.Query(ctx, listEditionsOfBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edition{}
	for rows.Next() {
		var i Edition
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Position,
			&i.Format,
			&i.Language,
			&i.PriceBdt,
			&i.ListPriceBdt,
			&i.Stock,
			&i.IsPreorder,
			&i.Isbn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordCounts = `-- name: ListRecordCounts :many
SELECT 'category'::text AS kind, category_id AS id, count(*)::int AS n FROM books GROUP BY category_id
UNION ALL SELECT 'author', author_id, count(*)::int FROM books GROUP BY author_id
UNION ALL SELECT 'publisher', publisher_id, count(*)::int FROM books GROUP BY publisher_id
`

type ListRecordCountsRow struct {
	Kind string
	ID   string
	N    int32
}

func (q *Queries) ListRecordCounts(ctx context.Context) ([]ListRecordCountsRow, error) {
	rows, err := q.db.Query(ctx, listRecordCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecordCountsRow{}
	for rows.Next() {
		var i ListRecordCountsRow
		if err := rows.Scan(&i.Kind, &i.ID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffBooklistIDs = `-- name: ListStaffBooklistIDs :many
SELECT id FROM booklists WHERE owner_id IS NULL
`

func (q *Queries) ListStaffBooklistIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listStaffBooklistIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lowStockEditions = `-- name: LowStockEditions :many
SELECT e.id AS edition_id, e.format, e.language, e.stock, b.id AS book_id, b.title, b.cover_seed
FROM editions e JOIN books b ON b.id = e.book_id
WHERE e.format <> 'ebook' AND NOT e.is_preorder AND e.stock <= $1
ORDER BY e.stock, b.position, e.position
`

type LowStockEditionsRow struct {
	EditionID string
	Format    string
	Language  string
	Stock     int32
	BookID    string
	Title     string
	CoverSeed int32
}

func (q *Queries) LowStockEditions(ctx context.Context, stock int32) ([]LowStockEditionsRow, error) {
	rows, err := q.db.Query(ctx, lowStockEditions, stock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LowStockEditionsRow{}
	for rows.Next() {
		var i LowStockEditionsRow
		if err := rows.Scan(
			&i.EditionID,
			&i.Format,
			&i.Language,
			&i.Stock,
			&i.BookID,
			&i.Title,
			&i.CoverSeed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const otherBooksIsbns = `-- name: OtherBooksIsbns :many
SELECT e.isbn FROM editions e WHERE e.isbn IS NOT NULL AND e.book_id <> $1
`

func (q *Queries) OtherBooksIsbns(ctx context.Context, bookID string) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, otherBooksIsbns, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var isbn pgtype.Text
		if err := rows.Scan(&isbn); err != nil {
			return nil, err
		}
		items = append(items, isbn)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publisherExists = `-- name: PublisherExists :one
SELECT EXISTS (SELECT 1 FROM publishers WHERE id = $1)
`

func (q *Queries) PublisherExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, publisherExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const renameBooksAuthor = `-- name: RenameBooksAuthor :exec
UPDATE books SET author = $2 WHERE author_id = $1
`

type RenameBooksAuthorParams struct {
	AuthorID string
	Author   string
}

func (q *Queries) RenameBooksAuthor(ctx context.Context, arg RenameBooksAuthorParams) error {
	_, err := q.db.Exec(ctx, renameBooksAuthor, arg.AuthorID, arg.Author)
	return err
}

const setBookHidden = `-- name: SetBookHidden :execrows
UPDATE books SET hidden = $2 WHERE id = $1
`

type SetBookHiddenParams struct {
	ID     string
	Hidden bool
}

func (q *Queries) SetBookHidden(ctx context.Context, arg SetBookHiddenParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBookHidden, arg.ID, arg.Hidden)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setEditionStock = `-- name: SetEditionStock :execrows
UPDATE editions SET stock = $2 WHERE id = $1
`

type SetEditionStockParams struct {
	ID    string
	Stock int32
}

func (q *Queries) SetEditionStock(ctx context.Context, arg SetEditionStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, setEditionStock, arg.ID, arg.Stock)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBook = `-- name: UpdateBook :exec
UPDATE books
SET title = $2, title_bn = $3, short_title = $4, author = $5, author_id = $6, publisher_id = $7,
    category_id = $8, section = $9, original_language = $10, cover_seed = $11, classes = $12,
    exams = $13, subject_id = $14
WHERE id = $1
`

type UpdateBookParams struct {
	ID               string
	Title            string
	TitleBn          pgtype.Text
	ShortTitle       pgtype.Text
	Author           string
	AuthorID         string
	PublisherID      string
	CategoryID       string
	Section          string
	OriginalLanguage string
	CoverSeed        int32
	Classes          []int32
	Exams            []string
	SubjectID        pgtype.Text
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) error {
	_, err := q.db.Exec(ctx, updateBook,
		arg.ID,
		arg.Title,
		arg.TitleBn,
		arg.ShortTitle,
		arg.Author,
		arg.AuthorID,
		arg.PublisherID,
		arg.CategoryID,
		arg.Section,
		arg.OriginalLanguage,
		arg.CoverSeed,
		arg.Classes,
		arg.Exams,
		arg.SubjectID,
	)
	return err
}

const upsertAuthor = `-- name: UpsertAuthor :exec
INSERT INTO authors (id, name, name_bn, bio) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_bn = EXCLUDED.name_bn
`

type UpsertAuthorParams struct {
	ID     string
	Name   string
	NameBn pgtype.Text
	Bio    pgtype.Text
}

func (q *Queries) UpsertAuthor(ctx context.Context, arg UpsertAuthorParams) error {
	_, err := q.db.Exec(ctx, upsertAuthor,
		arg.ID,
		arg.Name,
		arg.NameBn,
		arg.Bio,
	)
	return err
}

const upsertCategory = `-- name: UpsertCategory :exec
INSERT INTO categories (id, section, name_en, name_bn) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, name_en = EXCLUDED.name_en, name_bn = EXCLUDED.name_bn
`

type UpsertCategoryParams struct {
	ID      string
	Section string
	NameEn  string
	NameBn  string
}

func (q *Queries) UpsertCategory(ctx context.Context, arg UpsertCategoryParams) error {
	_, err := q.db.Exec(ctx, upsertCategory,
		arg.ID,
		arg.Section,
		arg.NameEn,
		arg.NameBn,
	)
	return err
}

const upsertCollection = `-- name: UpsertCollection :exec
INSERT INTO collections (id, title_en, title_bn, note_en, note_bn, section, expert_id, book_ids)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE
SET title_en = EXCLUDED.title_en, title_bn = EXCLUDED.title_bn, note_en = EXCLUDED.note_en,
    note_bn = EXCLUDED.note_bn, section = EXCLUDED.section, expert_id = EXCLUDED.expert_id,
    book_ids = EXCLUDED.book_ids
`

type UpsertCollectionParams struct {
	ID       string
	TitleEn  string
	TitleBn  string
	NoteEn   string
	NoteBn   string
	Section  pgtype.Text
	ExpertID pgtype.Text
	BookIds  []string
}

func (q *Queries) UpsertCollection(ctx context.Context, arg UpsertCollectionParams) error {
	_, err := q.db.Exec(ctx, upsertCollection,
		arg.ID,
		arg.TitleEn,
		arg.TitleBn,
		arg.NoteEn,
		arg.NoteBn,
		arg.Section,
		arg.ExpertID,
		arg.BookIds,
	)
	return err
}

const upsertEdition = `-- name: UpsertEdition :exec
INSERT INTO editions (id, book_id, format, language, price_bdt, list_price_bdt, stock, is_preorder, isbn)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE
SET format = EXCLUDED.format, language = EXCLUDED.language, price_bdt = EXCLUDED.price_bdt,
    list_price_bdt = EXCLUDED.list_price_bdt, stock = EXCLUDED.stock,
    is_preorder = EXCLUDED.is_preorder, isbn = EXCLUDED.isbn
`

type UpsertEditionParams struct {
	ID           string
	BookID       string
	Format       string
	Language     string
	PriceBdt     int32
	ListPriceBdt pgtype.Int4
	Stock        int32
	IsPreorder   bool
	Isbn         pgtype.Text
}

func (q *Queries) UpsertEdition(ctx context.Context, arg UpsertEditionParams) error {
	_, err := q.db.Exec(ctx, upsertEdition,
		arg.ID,
		arg.BookID,
		arg.Format,
		arg.Language,
		arg.PriceBdt,
		arg.ListPriceBdt,
		arg.Stock,
		arg.IsPreorder,
		arg.Isbn,
	)
	return err
}

const upsertPriceLow = `-- name: UpsertPriceLow :exec
INSERT INTO price_lows (edition_id, low_bdt, since) VALUES ($1, $2, $3)
ON CONFLICT (edition_id) DO UPDATE SET low_bdt = EXCLUDED.low_bdt, since = EXCLUDED.since
`

type UpsertPriceLowParams struct {
	EditionID string
	LowBdt    int32
	Since     time.Time
}

func (q *Queries) UpsertPriceLow(ctx context.Context, arg UpsertPriceLowParams) error {
	_, err := q.db.Exec(ctx, upsertPriceLow, arg.EditionID, arg.LowBdt, arg.Since)
	return err
}

const upsertPublisher = `-- name: UpsertPublisher :exec
INSERT INTO publishers (id, name, name_bn) VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_bn = EXCLUDED.name_bn
`

type UpsertPublisherParams struct {
	ID     string
	Name   string
	NameBn pgtype.Text
}

func (q *Queries) UpsertPublisher(ctx context.Context, arg UpsertPublisherParams) error {
	_, err := q.db.Exec(ctx, upsertPublisher, arg.ID, arg.Name, arg.NameBn)
	return err
}

const upsertStaffBooklist = `-- name: UpsertStaffBooklist :exec
INSERT INTO booklists (id, owner_id, kind, title_en, title_bn, note_en, note_bn, book_ids, updated_at)
VALUES ($1, NULL, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE
SET kind = EXCLUDED.kind, title_en = EXCLUDED.title_en, title_bn = EXCLUDED.title_bn,
    note_en = EXCLUDED.note_en, note_bn = EXCLUDED.note_bn, book_ids = EXCLUDED.book_ids,
    updated_at = EXCLUDED.updated_at
`

type UpsertStaffBooklistParams struct {
	ID        string
	Kind      string
	TitleEn   string
	TitleBn   string
	NoteEn    pgtype.Text
	NoteBn    pgtype.Text
	BookIds   []string
	UpdatedAt time.Time
}

func (q *Queries) UpsertStaffBooklist(ctx context.Context, arg UpsertStaffBooklistParams) error {
	_, err := q.db.Exec(ctx, upsertStaffBooklist,
		arg.ID,
		arg.Kind,
		arg.TitleEn,
		arg.TitleBn,
		arg.NoteEn,
		arg.NoteBn,
		arg.BookIds,
		arg.UpdatedAt,
	)
	return err
}
