// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dashboard.sql

package sqlc

import (
	"context"
	"time"
)

const bumpSearch = `-- name: BumpSearch :exec
INSERT INTO search_log (term, day, count) VALUES ($1, $2, 1)
ON CONFLICT (term, day) DO UPDATE SET count = search_log.count + 1
`

type BumpSearchParams struct {
	Term string
	Day  time.Time
}

func (q *Queries) BumpSearch(ctx context.Context, arg BumpSearchParams) error {
	_, err := q.db.Exec(ctx, bumpSearch, arg.Term, arg.Day)
	return err
}

const dropSearch = `-- name: DropSearch :exec
WITH lowered AS (
    UPDATE search_log SET count = count - 1 WHERE term = $1 AND day = $2 AND count > 1 RETURNING term
)
DELETE FROM search_log s WHERE s.term = $1 AND s.day = $2 AND s.count <= 1 AND NOT EXISTS (SELECT 1 FROM lowered)
`

type DropSearchParams struct {
	Term string
	Day  time.Time
}

// A live search that grew: the shorter term it replaces counts one less (and goes at zero).
func (q *Queries) DropSearch(ctx context.Context, arg DropSearchParams) error {
	_, err := q.db.Exec(ctx, dropSearch, arg.Term, arg.Day)
	return err
}

const seedSearch = `-- name: SeedSearch :exec
INSERT INTO search_log (term, day, count) VALUES ($1, $2, $3) ON CONFLICT (term, day) DO NOTHING
`

type SeedSearchParams struct {
	Term  string
	Day   time.Time
	Count int32
}

func (q *Queries) SeedSearch(ctx context.Context, arg SeedSearchParams) error {
	_, err := q.db.Exec(ctx, seedSearch, arg.Term, arg.Day, arg.Count)
	return err
}

const topSearches = `-- name: TopSearches :many
SELECT term, sum(count)::integer AS count FROM search_log GROUP BY term ORDER BY count DESC, term LIMIT $1
`

type TopSearchesRow struct {
	Term  string
	Count int32
}

func (q *Queries) TopSearches(ctx context.Context, limit int32) ([]TopSearchesRow, error) {
	rows, err := q.db.Query(ctx, topSearches, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopSearchesRow{}
	for rows.Next() {
		var i TopSearchesRow
		if err := rows.Scan(&i.Term, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
