// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: donate.sql

package sqlc

import (
	"context"
)

const addDonationReceived = `-- name: AddDonationReceived :exec
UPDATE donate_needs SET received = received + $3 WHERE place_id = $1 AND book_id = $2
`

type AddDonationReceivedParams struct {
	PlaceID  string
	BookID   string
	Received int32
}

func (q *Queries) AddDonationReceived(ctx context.Context, arg AddDonationReceivedParams) error {
	_, err := q.db.Exec(ctx, addDonationReceived, arg.PlaceID, arg.BookID, arg.Received)
	return err
}

const deleteDonateNeeds = `-- name: DeleteDonateNeeds :exec
DELETE FROM donate_needs WHERE place_id = $1
`

func (q *Queries) DeleteDonateNeeds(ctx context.Context, placeID string) error {
	_, err := q.db.Exec(ctx, deleteDonateNeeds, placeID)
	return err
}

const getDonatePlace = `-- name: GetDonatePlace :one
SELECT id, position, name, kind, district, area, story, created_at, removed_at FROM donate_places WHERE id = $1 AND removed_at IS NULL
`

func (q *Queries) GetDonatePlace(ctx context.Context, id string) (DonatePlace, error) {
	row := q.db.QueryRow(ctx, getDonatePlace, id)
	var i DonatePlace
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.Name,
		&i.Kind,
		&i.District,
		&i.Area,
		&i.Story,
		&i.CreatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const insertDonateNeed = `-- name: InsertDonateNeed :exec
INSERT INTO donate_needs (place_id, position, book_id, wanted, received) VALUES ($1, $2, $3, $4, $5)
`

type InsertDonateNeedParams struct {
	PlaceID  string
	Position int32
	BookID   string
	Wanted   int32
	Received int32
}

func (q *Queries) InsertDonateNeed(ctx context.Context, arg InsertDonateNeedParams) error {
	_, err := q.db.Exec(ctx, insertDonateNeed,
		arg.PlaceID,
		arg.Position,
		arg.BookID,
		arg.Wanted,
		arg.Received,
	)
	return err
}

const insertDonatePlace = `-- name: InsertDonatePlace :exec
INSERT INTO donate_places (id, name, kind, district, area, story) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertDonatePlaceParams struct {
	ID       string
	Name     string
	Kind     string
	District string
	Area     string
	Story    string
}

func (q *Queries) InsertDonatePlace(ctx context.Context, arg InsertDonatePlaceParams) error {
	_, err := q.db.Exec(ctx, insertDonatePlace,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.District,
		arg.Area,
		arg.Story,
	)
	return err
}

const listDonateNeeds = `-- name: ListDonateNeeds :many
SELECT place_id, position, book_id, wanted, received FROM donate_needs WHERE place_id = ANY($1::text[]) ORDER BY place_id, position
`

func (q *Queries) ListDonateNeeds(ctx context.Context, dollar_1 []string) ([]DonateNeed, error) {
	rows, err := q.db.Query(ctx, listDonateNeeds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DonateNeed{}
	for rows.Next() {
		var i DonateNeed
		if err := rows.Scan(
			&i.PlaceID,
			&i.Position,
			&i.BookID,
			&i.Wanted,
			&i.Received,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDonatePlaces = `-- name: ListDonatePlaces :many
SELECT id, position, name, kind, district, area, story, created_at, removed_at FROM donate_places WHERE removed_at IS NULL ORDER BY position
`

func (q *Queries) ListDonatePlaces(ctx context.Context) ([]DonatePlace, error) {
	rows, err := q.db.Query(ctx, listDonatePlaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DonatePlace{}
	for rows.Next() {
		var i DonatePlace
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Name,
			&i.Kind,
			&i.District,
			&i.Area,
			&i.Story,
			&i.CreatedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDonatePlace = `-- name: LockDonatePlace :one
SELECT id, position, name, kind, district, area, story, created_at, removed_at FROM donate_places WHERE id = $1 AND removed_at IS NULL FOR UPDATE
`

func (q *Queries) LockDonatePlace(ctx context.Context, id string) (DonatePlace, error) {
	row := q.db.QueryRow(ctx, lockDonatePlace, id)
	var i DonatePlace
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.Name,
		&i.Kind,
		&i.District,
		&i.Area,
		&i.Story,
		&i.CreatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const removeDonatePlace = `-- name: RemoveDonatePlace :execrows
UPDATE donate_places SET removed_at = now() WHERE id = $1 AND removed_at IS NULL
`

func (q *Queries) RemoveDonatePlace(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, removeDonatePlace, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const seedDonateNeed = `-- name: SeedDonateNeed :exec
INSERT INTO donate_needs (place_id, position, book_id, wanted, received) VALUES ($1, $2, $3, $4, $5)
`

type SeedDonateNeedParams struct {
	PlaceID  string
	Position int32
	BookID   string
	Wanted   int32
	Received int32
}

func (q *Queries) SeedDonateNeed(ctx context.Context, arg SeedDonateNeedParams) error {
	_, err := q.db.Exec(ctx, seedDonateNeed,
		arg.PlaceID,
		arg.Position,
		arg.BookID,
		arg.Wanted,
		arg.Received,
	)
	return err
}

const seedDonatePlace = `-- name: SeedDonatePlace :exec
INSERT INTO donate_places (id, name, kind, district, area, story) VALUES ($1, $2, $3, $4, $5, $6)
`

type SeedDonatePlaceParams struct {
	ID       string
	Name     string
	Kind     string
	District string
	Area     string
	Story    string
}

func (q *Queries) SeedDonatePlace(ctx context.Context, arg SeedDonatePlaceParams) error {
	_, err := q.db.Exec(ctx, seedDonatePlace,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.District,
		arg.Area,
		arg.Story,
	)
	return err
}

const seedDonatePlaceExists = `-- name: SeedDonatePlaceExists :one
SELECT EXISTS (SELECT 1 FROM donate_places WHERE id = $1)
`

func (q *Queries) SeedDonatePlaceExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, seedDonatePlaceExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateDonatePlace = `-- name: UpdateDonatePlace :exec
UPDATE donate_places SET name = $2, kind = $3, district = $4, area = $5, story = $6 WHERE id = $1
`

type UpdateDonatePlaceParams struct {
	ID       string
	Name     string
	Kind     string
	District string
	Area     string
	Story    string
}

func (q *Queries) UpdateDonatePlace(ctx context.Context, arg UpdateDonatePlaceParams) error {
	_, err := q.db.Exec(ctx, updateDonatePlace,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.District,
		arg.Area,
		arg.Story,
	)
	return err
}
