// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: handledsale.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDisputedSales = `-- name: CountDisputedSales :one
SELECT count(*)::bigint FROM handled_sales WHERE status = 'disputed'
`

func (q *Queries) CountDisputedSales(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDisputedSales)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getSale = `-- name: GetSale :one
SELECT id, listing_id, buyer_id, seller_id, price_bdt, fee_bdt, delivery_bdt, method, status, created_at, updated_at, dispute_reason, dispute_note, dispute_photos FROM handled_sales WHERE id = $1
`

func (q *Queries) GetSale(ctx context.Context, id string) (HandledSale, error) {
	row := q.db.QueryRow(ctx, getSale, id)
	var i HandledSale
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.SellerID,
		&i.PriceBdt,
		&i.FeeBdt,
		&i.DeliveryBdt,
		&i.Method,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisputeReason,
		&i.DisputeNote,
		&i.DisputePhotos,
	)
	return i, err
}

const insertPayout = `-- name: InsertPayout :exec
INSERT INTO payouts (user_id, amount_bdt, at) VALUES ($1, $2, $3)
`

type InsertPayoutParams struct {
	UserID    string
	AmountBdt int32
	At        time.Time
}

func (q *Queries) InsertPayout(ctx context.Context, arg InsertPayoutParams) error {
	_, err := q.db.Exec(ctx, insertPayout, arg.UserID, arg.AmountBdt, arg.At)
	return err
}

const insertSale = `-- name: InsertSale :exec
INSERT INTO handled_sales (id, listing_id, buyer_id, seller_id, price_bdt, fee_bdt, delivery_bdt, method, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $9)
`

type InsertSaleParams struct {
	ID          string
	ListingID   string
	BuyerID     string
	SellerID    string
	PriceBdt    int32
	FeeBdt      int32
	DeliveryBdt int32
	Method      string
	CreatedAt   time.Time
}

func (q *Queries) InsertSale(ctx context.Context, arg InsertSaleParams) error {
	_, err := q.db.Exec(ctx, insertSale,
		arg.ID,
		arg.ListingID,
		arg.BuyerID,
		arg.SellerID,
		arg.PriceBdt,
		arg.FeeBdt,
		arg.DeliveryBdt,
		arg.Method,
		arg.CreatedAt,
	)
	return err
}

const listDisputedSales = `-- name: ListDisputedSales :many
SELECT id, listing_id, buyer_id, seller_id, price_bdt, fee_bdt, delivery_bdt, method, status, created_at, updated_at, dispute_reason, dispute_note, dispute_photos FROM handled_sales WHERE status = 'disputed' ORDER BY created_at, id
`

func (q *Queries) ListDisputedSales(ctx context.Context) ([]HandledSale, error) {
	rows, err := q.db.Query(ctx, listDisputedSales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HandledSale{}
	for rows.Next() {
		var i HandledSale
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.BuyerID,
			&i.SellerID,
			&i.PriceBdt,
			&i.FeeBdt,
			&i.DeliveryBdt,
			&i.Method,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisputeReason,
			&i.DisputeNote,
			&i.DisputePhotos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayouts = `-- name: ListPayouts :many
SELECT amount_bdt, at FROM payouts WHERE user_id = $1 ORDER BY at DESC, id DESC
`

type ListPayoutsRow struct {
	AmountBdt int32
	At        time.Time
}

func (q *Queries) ListPayouts(ctx context.Context, userID string) ([]ListPayoutsRow, error) {
	rows, err := q.db.Query(ctx, listPayouts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayoutsRow{}
	for rows.Next() {
		var i ListPayoutsRow
		if err := rows.Scan(&i.AmountBdt, &i.At); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOf = `-- name: ListSalesOf :many
SELECT id, listing_id, buyer_id, seller_id, price_bdt, fee_bdt, delivery_bdt, method, status, created_at, updated_at, dispute_reason, dispute_note, dispute_photos FROM handled_sales WHERE buyer_id = $1 OR seller_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListSalesOf(ctx context.Context, buyerID string) ([]HandledSale, error) {
	rows, err := q.db.Query(ctx, listSalesOf, buyerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HandledSale{}
	for rows.Next() {
		var i HandledSale
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.BuyerID,
			&i.SellerID,
			&i.PriceBdt,
			&i.FeeBdt,
			&i.DeliveryBdt,
			&i.Method,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisputeReason,
			&i.DisputeNote,
			&i.DisputePhotos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSale = `-- name: LockSale :one
SELECT id, listing_id, buyer_id, seller_id, price_bdt, fee_bdt, delivery_bdt, method, status, created_at, updated_at, dispute_reason, dispute_note, dispute_photos FROM handled_sales WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockSale(ctx context.Context, id string) (HandledSale, error) {
	row := q.db.QueryRow(ctx, lockSale, id)
	var i HandledSale
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.SellerID,
		&i.PriceBdt,
		&i.FeeBdt,
		&i.DeliveryBdt,
		&i.Method,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisputeReason,
		&i.DisputeNote,
		&i.DisputePhotos,
	)
	return i, err
}

const paidOut = `-- name: PaidOut :one
SELECT coalesce(sum(amount_bdt), 0)::bigint FROM payouts WHERE user_id = $1
`

func (q *Queries) PaidOut(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, paidOut, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const seedListingBuyer = `-- name: SeedListingBuyer :exec
UPDATE listings SET status = $2, buyer_id = $3 WHERE id = $1 AND buyer_id IS NULL
`

type SeedListingBuyerParams struct {
	ID      string
	Status  string
	BuyerID pgtype.Text
}

func (q *Queries) SeedListingBuyer(ctx context.Context, arg SeedListingBuyerParams) error {
	_, err := q.db.Exec(ctx, seedListingBuyer, arg.ID, arg.Status, arg.BuyerID)
	return err
}

const seedPayout = `-- name: SeedPayout :exec
INSERT INTO payouts (user_id, amount_bdt, at)
SELECT $1, $2, $3 WHERE NOT EXISTS (SELECT 1 FROM payouts WHERE user_id = $1)
`

type SeedPayoutParams struct {
	UserID    string
	AmountBdt int32
	At        time.Time
}

func (q *Queries) SeedPayout(ctx context.Context, arg SeedPayoutParams) error {
	_, err := q.db.Exec(ctx, seedPayout, arg.UserID, arg.AmountBdt, arg.At)
	return err
}

const seedSale = `-- name: SeedSale :exec
INSERT INTO handled_sales (id, listing_id, buyer_id, seller_id, price_bdt, fee_bdt, delivery_bdt, method, status, created_at, updated_at,
                           dispute_reason, dispute_note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10, $11, $12)
ON CONFLICT (id) DO NOTHING
`

type SeedSaleParams struct {
	ID            string
	ListingID     string
	BuyerID       string
	SellerID      string
	PriceBdt      int32
	FeeBdt        int32
	DeliveryBdt   int32
	Method        string
	Status        string
	CreatedAt     time.Time
	DisputeReason pgtype.Text
	DisputeNote   pgtype.Text
}

func (q *Queries) SeedSale(ctx context.Context, arg SeedSaleParams) error {
	_, err := q.db.Exec(ctx, seedSale,
		arg.ID,
		arg.ListingID,
		arg.BuyerID,
		arg.SellerID,
		arg.PriceBdt,
		arg.FeeBdt,
		arg.DeliveryBdt,
		arg.Method,
		arg.Status,
		arg.CreatedAt,
		arg.DisputeReason,
		arg.DisputeNote,
	)
	return err
}

const sellerEarnings = `-- name: SellerEarnings :one
SELECT coalesce(sum(price_bdt - fee_bdt) FILTER (WHERE status IN ('paid', 'sent', 'disputed')), 0)::bigint AS held_bdt,
       coalesce(sum(price_bdt - fee_bdt) FILTER (WHERE status IN ('completed', 'released')), 0)::bigint AS earned_bdt
FROM handled_sales WHERE seller_id = $1
`

type SellerEarningsRow struct {
	HeldBdt   int64
	EarnedBdt int64
}

func (q *Queries) SellerEarnings(ctx context.Context, sellerID string) (SellerEarningsRow, error) {
	row := q.db.QueryRow(ctx, sellerEarnings, sellerID)
	var i SellerEarningsRow
	err := row.Scan(&i.HeldBdt, &i.EarnedBdt)
	return i, err
}

const sendDemoSales = `-- name: SendDemoSales :many
UPDATE handled_sales SET status = 'sent', updated_at = $1
WHERE status = 'paid' AND seller_id LIKE 'p-%' AND created_at <= $2
RETURNING id, listing_id, buyer_id, seller_id, price_bdt, fee_bdt, delivery_bdt, method, status, created_at, updated_at, dispute_reason, dispute_note, dispute_photos
`

type SendDemoSalesParams struct {
	Now time.Time
	Due time.Time
}

// The demo bot: demo sellers (ids "p-...") hand paid books to the courier once they are old enough.
func (q *Queries) SendDemoSales(ctx context.Context, arg SendDemoSalesParams) ([]HandledSale, error) {
	rows, err := q.db.Query(ctx, sendDemoSales, arg.Now, arg.Due)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HandledSale{}
	for rows.Next() {
		var i HandledSale
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.BuyerID,
			&i.SellerID,
			&i.PriceBdt,
			&i.FeeBdt,
			&i.DeliveryBdt,
			&i.Method,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisputeReason,
			&i.DisputeNote,
			&i.DisputePhotos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSaleDispute = `-- name: SetSaleDispute :exec
UPDATE handled_sales SET status = 'disputed', dispute_reason = $2, dispute_note = $3, dispute_photos = $4, updated_at = $5
WHERE id = $1
`

type SetSaleDisputeParams struct {
	ID            string
	DisputeReason pgtype.Text
	DisputeNote   pgtype.Text
	DisputePhotos []byte
	UpdatedAt     time.Time
}

func (q *Queries) SetSaleDispute(ctx context.Context, arg SetSaleDisputeParams) error {
	_, err := q.db.Exec(ctx, setSaleDispute,
		arg.ID,
		arg.DisputeReason,
		arg.DisputeNote,
		arg.DisputePhotos,
		arg.UpdatedAt,
	)
	return err
}

const setSaleStatus = `-- name: SetSaleStatus :exec
UPDATE handled_sales SET status = $2, updated_at = $3 WHERE id = $1
`

type SetSaleStatusParams struct {
	ID        string
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) SetSaleStatus(ctx context.Context, arg SetSaleStatusParams) error {
	_, err := q.db.Exec(ctx, setSaleStatus, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}
