// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: home.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBanner = `-- name: DeleteBanner :execrows
DELETE FROM banners WHERE id = $1
`

func (q *Queries) DeleteBanner(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBanner, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBanner = `-- name: GetBanner :one
SELECT id, position, title_en, title_bn, subtitle_en, subtitle_bn, seed, target_kind, target_value, season FROM banners WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetBanner(ctx context.Context, id string) (Banner, error) {
	row := q.db.QueryRow(ctx, getBanner, id)
	var i Banner
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.TitleEn,
		&i.TitleBn,
		&i.SubtitleEn,
		&i.SubtitleBn,
		&i.Seed,
		&i.TargetKind,
		&i.TargetValue,
		&i.Season,
	)
	return i, err
}

const getConfig = `-- name: GetConfig :one
SELECT value FROM app_config WHERE key = $1
`

func (q *Queries) GetConfig(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getConfig, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const getIsbnLookup = `-- name: GetIsbnLookup :one
SELECT isbn, title, title_bn, author, publisher, language, format, list_price_bdt FROM isbn_lookup WHERE isbn = $1
`

func (q *Queries) GetIsbnLookup(ctx context.Context, isbn string) (IsbnLookup, error) {
	row := q.db.QueryRow(ctx, getIsbnLookup, isbn)
	var i IsbnLookup
	err := row.Scan(
		&i.Isbn,
		&i.Title,
		&i.TitleBn,
		&i.Author,
		&i.Publisher,
		&i.Language,
		&i.Format,
		&i.ListPriceBdt,
	)
	return i, err
}

const insertBanner = `-- name: InsertBanner :exec
INSERT INTO banners (id, position, title_en, title_bn, subtitle_en, subtitle_bn, seed, target_kind, target_value, season)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertBannerParams struct {
	ID          string
	Position    int32
	TitleEn     string
	TitleBn     string
	SubtitleEn  string
	SubtitleBn  string
	Seed        int32
	TargetKind  string
	TargetValue string
	Season      pgtype.Text
}

func (q *Queries) InsertBanner(ctx context.Context, arg InsertBannerParams) error {
	_, err := q.db.Exec(ctx, insertBanner,
		arg.ID,
		arg.Position,
		arg.TitleEn,
		arg.TitleBn,
		arg.SubtitleEn,
		arg.SubtitleBn,
		arg.Seed,
		arg.TargetKind,
		arg.TargetValue,
		arg.Season,
	)
	return err
}

const listAyahs = `-- name: ListAyahs :many
SELECT position, arabic, translation, surah_en, surah_bn, surah_number, verse_number FROM ayahs ORDER BY position
`

func (q *Queries) ListAyahs(ctx context.Context) ([]Ayah, error) {
	rows, err := q.db.Query(ctx, listAyahs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ayah{}
	for rows.Next() {
		var i Ayah
		if err := rows.Scan(
			&i.Position,
			&i.Arabic,
			&i.Translation,
			&i.SurahEn,
			&i.SurahBn,
			&i.SurahNumber,
			&i.VerseNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBanners = `-- name: ListBanners :many
SELECT id, position, title_en, title_bn, subtitle_en, subtitle_bn, seed, target_kind, target_value, season FROM banners ORDER BY position, id
`

func (q *Queries) ListBanners(ctx context.Context) ([]Banner, error) {
	rows, err := q.db.Query(ctx, listBanners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Banner{}
	for rows.Next() {
		var i Banner
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.TitleEn,
			&i.TitleBn,
			&i.SubtitleEn,
			&i.SubtitleBn,
			&i.Seed,
			&i.TargetKind,
			&i.TargetValue,
			&i.Season,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextBannerPosition = `-- name: NextBannerPosition :one
SELECT (COALESCE(max(position), 0) + 1)::int FROM banners
`

func (q *Queries) NextBannerPosition(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, nextBannerPosition)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setBannerPosition = `-- name: SetBannerPosition :exec
UPDATE banners SET position = $2 WHERE id = $1
`

type SetBannerPositionParams struct {
	ID       string
	Position int32
}

func (q *Queries) SetBannerPosition(ctx context.Context, arg SetBannerPositionParams) error {
	_, err := q.db.Exec(ctx, setBannerPosition, arg.ID, arg.Position)
	return err
}

const setConfig = `-- name: SetConfig :exec
INSERT INTO app_config (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
`

type SetConfigParams struct {
	Key   string
	Value []byte
}

func (q *Queries) SetConfig(ctx context.Context, arg SetConfigParams) error {
	_, err := q.db.Exec(ctx, setConfig, arg.Key, arg.Value)
	return err
}

const updateBanner = `-- name: UpdateBanner :exec
UPDATE banners
SET title_en = $2, title_bn = $3, subtitle_en = $4, subtitle_bn = $5, seed = $6,
    target_kind = $7, target_value = $8, season = $9
WHERE id = $1
`

type UpdateBannerParams struct {
	ID          string
	TitleEn     string
	TitleBn     string
	SubtitleEn  string
	SubtitleBn  string
	Seed        int32
	TargetKind  string
	TargetValue string
	Season      pgtype.Text
}

func (q *Queries) UpdateBanner(ctx context.Context, arg UpdateBannerParams) error {
	_, err := q.db.Exec(ctx, updateBanner,
		arg.ID,
		arg.TitleEn,
		arg.TitleBn,
		arg.SubtitleEn,
		arg.SubtitleBn,
		arg.Seed,
		arg.TargetKind,
		arg.TargetValue,
		arg.Season,
	)
	return err
}
