// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ids.sql

package sqlc

import (
	"context"
)

const nextHandledSaleNumber = `-- name: NextHandledSaleNumber :one
SELECT nextval('handled_sale_seq')::bigint
`

func (q *Queries) NextHandledSaleNumber(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextHandledSaleNumber)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const nextOrderNumber = `-- name: NextOrderNumber :one
SELECT nextval('order_number_seq')::bigint
`

func (q *Queries) NextOrderNumber(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextOrderNumber)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
