// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: inbox.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const closePendingOffers = `-- name: ClosePendingOffers :exec
UPDATE offers SET status = 'closed' WHERE thread_id = $1 AND status = 'pending'
`

func (q *Queries) ClosePendingOffers(ctx context.Context, threadID string) error {
	_, err := q.db.Exec(ctx, closePendingOffers, threadID)
	return err
}

const deleteMessage = `-- name: DeleteMessage :one
DELETE FROM messages WHERE id = $1 RETURNING thread_id
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteMessage, id)
	var thread_id string
	err := row.Scan(&thread_id)
	return thread_id, err
}

const findThreadOf = `-- name: FindThreadOf :one
SELECT id, listing_id, buyer_id, seller_id, buyer_read, seller_read, bot_replied, created_at FROM threads WHERE listing_id = $1 AND buyer_id = $2
`

type FindThreadOfParams struct {
	ListingID string
	BuyerID   string
}

func (q *Queries) FindThreadOf(ctx context.Context, arg FindThreadOfParams) (Thread, error) {
	row := q.db.QueryRow(ctx, findThreadOf, arg.ListingID, arg.BuyerID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.SellerID,
		&i.BuyerRead,
		&i.SellerRead,
		&i.BotReplied,
		&i.CreatedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, position, thread_id, author_id, at, text, offer_id, event, amount_bdt FROM messages WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.ThreadID,
		&i.AuthorID,
		&i.At,
		&i.Text,
		&i.OfferID,
		&i.Event,
		&i.AmountBdt,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT id, listing_id, buyer_id, seller_id, buyer_read, seller_read, bot_replied, created_at FROM threads WHERE id = $1
`

func (q *Queries) GetThread(ctx context.Context, id string) (Thread, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.SellerID,
		&i.BuyerRead,
		&i.SellerRead,
		&i.BotReplied,
		&i.CreatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (id, thread_id, author_id, at, text, offer_id, event, amount_bdt)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING position
`

type InsertMessageParams struct {
	ID        string
	ThreadID  string
	AuthorID  string
	At        time.Time
	Text      pgtype.Text
	OfferID   pgtype.Text
	Event     pgtype.Text
	AmountBdt pgtype.Int4
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ID,
		arg.ThreadID,
		arg.AuthorID,
		arg.At,
		arg.Text,
		arg.OfferID,
		arg.Event,
		arg.AmountBdt,
	)
	var position int64
	err := row.Scan(&position)
	return position, err
}

const insertOffer = `-- name: InsertOffer :exec
INSERT INTO offers (id, thread_id, amount_bdt, handover) VALUES ($1, $2, $3, $4)
`

type InsertOfferParams struct {
	ID        string
	ThreadID  string
	AmountBdt int32
	Handover  string
}

func (q *Queries) InsertOffer(ctx context.Context, arg InsertOfferParams) error {
	_, err := q.db.Exec(ctx, insertOffer,
		arg.ID,
		arg.ThreadID,
		arg.AmountBdt,
		arg.Handover,
	)
	return err
}

const insertThread = `-- name: InsertThread :exec
INSERT INTO threads (id, listing_id, buyer_id, seller_id) VALUES ($1, $2, $3, $4) ON CONFLICT (listing_id, buyer_id) DO NOTHING
`

type InsertThreadParams struct {
	ID        string
	ListingID string
	BuyerID   string
	SellerID  string
}

func (q *Queries) InsertThread(ctx context.Context, arg InsertThreadParams) error {
	_, err := q.db.Exec(ctx, insertThread,
		arg.ID,
		arg.ListingID,
		arg.BuyerID,
		arg.SellerID,
	)
	return err
}

const listMessagePositions = `-- name: ListMessagePositions :many
SELECT position FROM messages WHERE thread_id = $1 ORDER BY position
`

func (q *Queries) ListMessagePositions(ctx context.Context, threadID string) ([]int64, error) {
	rows, err := q.db.Query(ctx, listMessagePositions, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var position int64
		if err := rows.Scan(&position); err != nil {
			return nil, err
		}
		items = append(items, position)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesOf = `-- name: ListMessagesOf :many
SELECT m.id, m.position, m.thread_id, m.author_id, m.at, m.text, m.event, m.amount_bdt,
       o.id AS offer_id, o.amount_bdt AS offer_amount_bdt, o.handover AS offer_handover, o.status AS offer_status
FROM messages m LEFT JOIN offers o ON o.id = m.offer_id
WHERE m.thread_id = ANY($1::text[])
ORDER BY m.thread_id, m.position
`

type ListMessagesOfRow struct {
	ID             string
	Position       int64
	ThreadID       string
	AuthorID       string
	At             time.Time
	Text           pgtype.Text
	Event          pgtype.Text
	AmountBdt      pgtype.Int4
	OfferID        pgtype.Text
	OfferAmountBdt pgtype.Int4
	OfferHandover  pgtype.Text
	OfferStatus    pgtype.Text
}

func (q *Queries) ListMessagesOf(ctx context.Context, dollar_1 []string) ([]ListMessagesOfRow, error) {
	rows, err := q.db.Query(ctx, listMessagesOf, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesOfRow{}
	for rows.Next() {
		var i ListMessagesOfRow
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.ThreadID,
			&i.AuthorID,
			&i.At,
			&i.Text,
			&i.Event,
			&i.AmountBdt,
			&i.OfferID,
			&i.OfferAmountBdt,
			&i.OfferHandover,
			&i.OfferStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsAbout = `-- name: ListThreadsAbout :many
SELECT id, listing_id, buyer_id, seller_id, buyer_read, seller_read, bot_replied, created_at FROM threads WHERE listing_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListThreadsAbout(ctx context.Context, listingID string) ([]Thread, error) {
	rows, err := q.db.Query(ctx, listThreadsAbout, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Thread{}
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.BuyerID,
			&i.SellerID,
			&i.BuyerRead,
			&i.SellerRead,
			&i.BotReplied,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsOf = `-- name: ListThreadsOf :many
SELECT id, listing_id, buyer_id, seller_id, buyer_read, seller_read, bot_replied, created_at FROM threads WHERE buyer_id = $1 OR seller_id = $1
`

func (q *Queries) ListThreadsOf(ctx context.Context, buyerID string) ([]Thread, error) {
	rows, err := q.db.Query(ctx, listThreadsOf, buyerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Thread{}
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.BuyerID,
			&i.SellerID,
			&i.BuyerRead,
			&i.SellerRead,
			&i.BotReplied,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNames = `-- name: ListUserNames :many
SELECT id, name FROM users WHERE id = ANY($1::text[])
`

type ListUserNamesRow struct {
	ID   string
	Name string
}

func (q *Queries) ListUserNames(ctx context.Context, dollar_1 []string) ([]ListUserNamesRow, error) {
	rows, err := q.db.Query(ctx, listUserNames, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserNamesRow{}
	for rows.Next() {
		var i ListUserNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockThread = `-- name: LockThread :one
SELECT id, listing_id, buyer_id, seller_id, buyer_read, seller_read, bot_replied, created_at FROM threads WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockThread(ctx context.Context, id string) (Thread, error) {
	row := q.db.QueryRow(ctx, lockThread, id)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.SellerID,
		&i.BuyerRead,
		&i.SellerRead,
		&i.BotReplied,
		&i.CreatedAt,
	)
	return i, err
}

const markBotReplied = `-- name: MarkBotReplied :execrows
UPDATE threads SET bot_replied = true WHERE id = $1 AND NOT bot_replied
`

func (q *Queries) MarkBotReplied(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markBotReplied, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pendingOffer = `-- name: PendingOffer :one
SELECT id, position, thread_id, amount_bdt, handover, status FROM offers WHERE thread_id = $1 AND status = 'pending' ORDER BY position DESC LIMIT 1
`

func (q *Queries) PendingOffer(ctx context.Context, threadID string) (Offer, error) {
	row := q.db.QueryRow(ctx, pendingOffer, threadID)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.ThreadID,
		&i.AmountBdt,
		&i.Handover,
		&i.Status,
	)
	return i, err
}

const readUpBuyer = `-- name: ReadUpBuyer :exec
UPDATE threads SET buyer_read = COALESCE((SELECT max(position) FROM messages WHERE thread_id = threads.id), 0) WHERE threads.id = $1
`

func (q *Queries) ReadUpBuyer(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, readUpBuyer, id)
	return err
}

const readUpSeller = `-- name: ReadUpSeller :exec
UPDATE threads SET seller_read = COALESCE((SELECT max(position) FROM messages WHERE thread_id = threads.id), 0) WHERE threads.id = $1
`

func (q *Queries) ReadUpSeller(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, readUpSeller, id)
	return err
}

const seedMessage = `-- name: SeedMessage :exec
INSERT INTO messages (id, thread_id, author_id, at, text, offer_id, event, amount_bdt)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) ON CONFLICT (id) DO NOTHING
`

type SeedMessageParams struct {
	ID        string
	ThreadID  string
	AuthorID  string
	At        time.Time
	Text      pgtype.Text
	OfferID   pgtype.Text
	Event     pgtype.Text
	AmountBdt pgtype.Int4
}

func (q *Queries) SeedMessage(ctx context.Context, arg SeedMessageParams) error {
	_, err := q.db.Exec(ctx, seedMessage,
		arg.ID,
		arg.ThreadID,
		arg.AuthorID,
		arg.At,
		arg.Text,
		arg.OfferID,
		arg.Event,
		arg.AmountBdt,
	)
	return err
}

const seedOffer = `-- name: SeedOffer :exec
INSERT INTO offers (id, thread_id, amount_bdt, handover, status) VALUES ($1, $2, $3, $4, $5) ON CONFLICT (id) DO NOTHING
`

type SeedOfferParams struct {
	ID        string
	ThreadID  string
	AmountBdt int32
	Handover  string
	Status    string
}

func (q *Queries) SeedOffer(ctx context.Context, arg SeedOfferParams) error {
	_, err := q.db.Exec(ctx, seedOffer,
		arg.ID,
		arg.ThreadID,
		arg.AmountBdt,
		arg.Handover,
		arg.Status,
	)
	return err
}

const seedSetReadBuyer = `-- name: SeedSetReadBuyer :exec
UPDATE threads SET buyer_read = $2 WHERE id = $1
`

type SeedSetReadBuyerParams struct {
	ID        string
	BuyerRead int64
}

func (q *Queries) SeedSetReadBuyer(ctx context.Context, arg SeedSetReadBuyerParams) error {
	_, err := q.db.Exec(ctx, seedSetReadBuyer, arg.ID, arg.BuyerRead)
	return err
}

const seedSetReadSeller = `-- name: SeedSetReadSeller :exec
UPDATE threads SET seller_read = $2 WHERE id = $1
`

type SeedSetReadSellerParams struct {
	ID         string
	SellerRead int64
}

func (q *Queries) SeedSetReadSeller(ctx context.Context, arg SeedSetReadSellerParams) error {
	_, err := q.db.Exec(ctx, seedSetReadSeller, arg.ID, arg.SellerRead)
	return err
}

const seedThread = `-- name: SeedThread :exec
INSERT INTO threads (id, listing_id, buyer_id, seller_id, bot_replied, created_at) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO NOTHING
`

type SeedThreadParams struct {
	ID         string
	ListingID  string
	BuyerID    string
	SellerID   string
	BotReplied bool
	CreatedAt  time.Time
}

func (q *Queries) SeedThread(ctx context.Context, arg SeedThreadParams) error {
	_, err := q.db.Exec(ctx, seedThread,
		arg.ID,
		arg.ListingID,
		arg.BuyerID,
		arg.SellerID,
		arg.BotReplied,
		arg.CreatedAt,
	)
	return err
}

const setOfferStatus = `-- name: SetOfferStatus :exec
UPDATE offers SET status = $2 WHERE id = $1
`

type SetOfferStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) SetOfferStatus(ctx context.Context, arg SetOfferStatusParams) error {
	_, err := q.db.Exec(ctx, setOfferStatus, arg.ID, arg.Status)
	return err
}
