// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID        string
	UserID    string
	Position  int64
	Label     string
	Recipient string
	Phone     string
	Line      string
	Upazila   string
	District  string
	Division  string
	IsDefault bool
}

type Notification struct {
	ID        string
	UserID    string
	Kind      string
	Params    []byte
	Target    []byte
	ReadAt    pgtype.Timestamptz
	CreatedAt time.Time
}

type OtpCode struct {
	Contact   string
	Purpose   string
	CodeHash  string
	ExpiresAt time.Time
	Attempts  int32
	CreatedAt time.Time
}

type PendingSignup struct {
	Contact      string
	Name         string
	PasswordHash string
	CreatedAt    time.Time
}

type ProfilePref struct {
	UserID          string
	Muted           []string
	ProfileVisible  bool
	ActivityVisible bool
}

type RefreshToken struct {
	ID        string
	UserID    string
	TokenHash string
	ExpiresAt time.Time
	RevokedAt pgtype.Timestamptz
	CreatedAt time.Time
}

type User struct {
	ID           string
	Email        pgtype.Text
	Phone        string
	Name         string
	PasswordHash pgtype.Text
	Role         string
	PhotoUrl     pgtype.Text
	Area         string
	District     string
	MemberSince  time.Time
	Strikes      int32
	Banned       bool
	DeletedAt    pgtype.Timestamptz
	CreatedAt    time.Time
	PhotoData    pgtype.Text
}
