// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID        string
	UserID    string
	Position  int64
	Label     string
	Recipient string
	Phone     string
	Line      string
	Upazila   string
	District  string
	Division  string
	IsDefault bool
}

type Alert struct {
	ID             string
	UserID         string
	Position       int64
	Kind           string
	BookID         string
	EditionID      string
	TargetPriceBdt pgtype.Int4
	FiredAt        pgtype.Timestamptz
}

type AppConfig struct {
	Key   string
	Value []byte
}

type Author struct {
	ID       string
	Name     string
	NameBn   pgtype.Text
	Bio      pgtype.Text
	Position pgtype.Int8
}

type Ayah struct {
	Position    int32
	Arabic      string
	Translation string
	SurahEn     string
	SurahBn     string
	SurahNumber int32
	VerseNumber int32
}

type Banner struct {
	ID          string
	Position    int32
	TitleEn     string
	TitleBn     string
	SubtitleEn  string
	SubtitleBn  string
	Seed        int32
	TargetKind  string
	TargetValue string
	Season      pgtype.Text
}

type Book struct {
	ID               string
	Position         int64
	Title            string
	TitleBn          pgtype.Text
	ShortTitle       pgtype.Text
	Author           string
	AuthorID         string
	PublisherID      string
	CategoryID       string
	Section          string
	OriginalLanguage string
	AddedAt          time.Time
	Rating           float64
	Tags             []string
	CoverSeed        int32
	Hidden           bool
	Classes          []int32
	Exams            []string
	SubjectID        pgtype.Text
}

type BookAnswer struct {
	ID         string
	Position   int64
	QuestionID string
	UserID     pgtype.Text
	AuthorName string
	Text       string
	AnsweredAt time.Time
	IsStaff    bool
}

type BookDetail struct {
	BookID      string
	Description string
	Pages       int32
}

type BookQuestion struct {
	ID        string
	Position  int64
	BookID    string
	UserID    pgtype.Text
	AskerName string
	Text      string
	AskedAt   time.Time
}

type Booklist struct {
	ID        string
	Position  int64
	OwnerID   pgtype.Text
	Kind      string
	TitleEn   string
	TitleBn   string
	NoteEn    pgtype.Text
	NoteBn    pgtype.Text
	BookIds   []string
	UpdatedAt time.Time
}

type Bundle struct {
	ID         string
	Position   int32
	Title      string
	EditionIds []string
	PriceBdt   int32
}

type CartLine struct {
	UserID   string
	Kind     string
	ItemID   string
	Position int64
	Quantity int32
	AddedAt  time.Time
}

type Category struct {
	ID       string
	Section  string
	NameEn   string
	NameBn   string
	Position pgtype.Int8
}

type Collection struct {
	ID       string
	Position int64
	TitleEn  string
	TitleBn  string
	NoteEn   string
	NoteBn   string
	Section  pgtype.Text
	ExpertID pgtype.Text
	BookIds  []string
}

type Coupon struct {
	Code           string
	Position       int64
	Kind           string
	Value          int32
	MinOrderBdt    int32
	MaxDiscountBdt pgtype.Int4
	ExpiresAt      pgtype.Timestamptz
	CreatedBy      pgtype.Text
}

type Edition struct {
	ID           string
	BookID       string
	Position     int64
	Format       string
	Language     string
	PriceBdt     int32
	ListPriceBdt pgtype.Int4
	Stock        int32
	IsPreorder   bool
	Isbn         pgtype.Text
}

type Expert struct {
	ID           string
	Position     int64
	Name         string
	NameBn       string
	CredentialEn string
	CredentialBn string
	Kind         string
	Verified     bool
}

type FlashSaleItem struct {
	EditionID string
	Position  int32
	PriceBdt  int32
}

type IsbnLookup struct {
	Isbn         string
	Title        string
	TitleBn      pgtype.Text
	Author       string
	Publisher    string
	Language     string
	Format       string
	ListPriceBdt int32
}

type LookInside struct {
	BookID      string
	Contents    []byte
	SamplePages []byte
}

type Notification struct {
	ID        string
	UserID    string
	Kind      string
	Params    []byte
	Target    []byte
	ReadAt    pgtype.Timestamptz
	CreatedAt time.Time
}

type Order struct {
	Number         string
	UserID         string
	Status         string
	PlacedAt       time.Time
	AddressLabel   string
	AddressLine    string
	Payment        string
	SubtotalBdt    int32
	DeliveryFeeBdt int32
	DiscountBdt    int32
	TotalBdt       int32
	NeedsDelivery  bool
	PointsUsed     int32
	PointsEarned   int32
	Gift           []byte
	GiftWrapBdt    int32
	IsDonation     bool
	DonatePlaceID  pgtype.Text
	WalletUsedBdt  int32
	RefundedBdt    int32
}

type OrderHistory struct {
	OrderNumber string
	Position    int32
	Status      string
	At          time.Time
}

type OrderLine struct {
	OrderNumber  string
	Position     int32
	BookID       string
	EditionID    pgtype.Text
	Title        string
	Author       string
	Quantity     int32
	UnitPriceBdt int32
	Format       pgtype.Text
	Language     pgtype.Text
	CoverSeed    int32
}

type OrderReturn struct {
	OrderNumber string
	Reason      string
	Status      string
	RequestedAt time.Time
	DecidedAt   pgtype.Timestamptz
	Note        string
	Photos      []byte
}

type OtpCode struct {
	Contact   string
	Purpose   string
	CodeHash  string
	ExpiresAt time.Time
	Attempts  int32
	CreatedAt time.Time
}

type PendingSignup struct {
	Contact      string
	Name         string
	PasswordHash string
	CreatedAt    time.Time
}

type PointsEntry struct {
	ID          int64
	UserID      string
	Points      int32
	Reason      string
	OrderNumber pgtype.Text
	At          time.Time
}

type Preorder struct {
	EditionID string
	Position  int32
}

type PriceLow struct {
	EditionID string
	LowBdt    int32
	Since     time.Time
}

type ProfilePref struct {
	UserID          string
	Muted           []string
	ProfileVisible  bool
	ActivityVisible bool
}

type Publisher struct {
	ID       string
	Name     string
	NameBn   pgtype.Text
	Position pgtype.Int8
}

type RefreshToken struct {
	ID        string
	UserID    string
	TokenHash string
	ExpiresAt time.Time
	RevokedAt pgtype.Timestamptz
	CreatedAt time.Time
}

type SalesByMonth struct {
	EditionID string
	Month     time.Time
	Copies    int32
}

type Series struct {
	ID       string
	Position int64
	Name     string
	Entries  []byte
}

type Subject struct {
	ID       string
	NameEn   string
	NameBn   string
	Position pgtype.Int8
}

type User struct {
	ID           string
	Email        pgtype.Text
	Phone        string
	Name         string
	PasswordHash pgtype.Text
	Role         string
	PhotoUrl     pgtype.Text
	Area         string
	District     string
	MemberSince  time.Time
	Strikes      int32
	Banned       bool
	DeletedAt    pgtype.Timestamptz
	CreatedAt    time.Time
	PhotoData    pgtype.Text
}

type WalletEntry struct {
	ID          int64
	UserID      string
	AmountBdt   int32
	Reason      string
	OrderNumber pgtype.Text
	Note        pgtype.Text
	At          time.Time
}

type WishlistItem struct {
	UserID  string
	BookID  string
	AddedAt time.Time
}

type WishlistShare struct {
	ID        string
	UserID    string
	OwnerName string
}
