// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: moderation.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPerson = `-- name: GetPerson :one
SELECT id, name, area, district FROM users WHERE id = $1 AND deleted_at IS NULL
`

type GetPersonRow struct {
	ID       string
	Name     string
	Area     string
	District string
}

func (q *Queries) GetPerson(ctx context.Context, id string) (GetPersonRow, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i GetPersonRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Area,
		&i.District,
	)
	return i, err
}

const getStrikes = `-- name: GetStrikes :one
SELECT strikes, banned FROM users WHERE id = $1
`

type GetStrikesRow struct {
	Strikes int32
	Banned  bool
}

func (q *Queries) GetStrikes(ctx context.Context, id string) (GetStrikesRow, error) {
	row := q.db.QueryRow(ctx, getStrikes, id)
	var i GetStrikesRow
	err := row.Scan(&i.Strikes, &i.Banned)
	return i, err
}

const insertLog = `-- name: InsertLog :exec
INSERT INTO moderation_log (at, by_name, action, subject, reason) VALUES ($1, $2, $3, $4, $5)
`

type InsertLogParams struct {
	At      time.Time
	ByName  string
	Action  string
	Subject string
	Reason  pgtype.Text
}

func (q *Queries) InsertLog(ctx context.Context, arg InsertLogParams) error {
	_, err := q.db.Exec(ctx, insertLog,
		arg.At,
		arg.ByName,
		arg.Action,
		arg.Subject,
		arg.Reason,
	)
	return err
}

const listLog = `-- name: ListLog :many
SELECT id, at, by_name, action, subject, reason FROM moderation_log ORDER BY at DESC, id DESC
`

func (q *Queries) ListLog(ctx context.Context) ([]ModerationLog, error) {
	rows, err := q.db.Query(ctx, listLog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModerationLog{}
	for rows.Next() {
		var i ModerationLog
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ByName,
			&i.Action,
			&i.Subject,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStrikes = `-- name: SetStrikes :exec
UPDATE users SET strikes = $2, banned = $3 WHERE id = $1
`

type SetStrikesParams struct {
	ID      string
	Strikes int32
	Banned  bool
}

func (q *Queries) SetStrikes(ctx context.Context, arg SetStrikesParams) error {
	_, err := q.db.Exec(ctx, setStrikes, arg.ID, arg.Strikes, arg.Banned)
	return err
}

const staffName = `-- name: StaffName :one
SELECT COALESCE(NULLIF(name, ''), email::text, id)::text FROM users WHERE id = $1
`

func (q *Queries) StaffName(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, staffName, id)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}
