// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notifications.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notifications (id, user_id, kind, params, target, read_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertNotificationParams struct {
	ID        string
	UserID    string
	Kind      string
	Params    []byte
	Target    []byte
	ReadAt    pgtype.Timestamptz
	CreatedAt time.Time
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Params,
		arg.Target,
		arg.ReadAt,
		arg.CreatedAt,
	)
	return err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, kind, params, target, read_at, created_at
FROM notifications WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

type ListNotificationsRow struct {
	ID        string
	Kind      string
	Params    []byte
	Target    []byte
	ReadAt    pgtype.Timestamptz
	CreatedAt time.Time
}

func (q *Queries) ListNotifications(ctx context.Context, userID string) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Params,
			&i.Target,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = $2 WHERE user_id = $1 AND read_at IS NULL
`

type MarkAllNotificationsReadParams struct {
	UserID string
	ReadAt pgtype.Timestamptz
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, arg.UserID, arg.ReadAt)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications SET read_at = COALESCE(read_at, $3) WHERE user_id = $1 AND id = $2
`

type MarkNotificationReadParams struct {
	UserID string
	ID     string
	ReadAt pgtype.Timestamptz
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.UserID, arg.ID, arg.ReadAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
