// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrderRefund = `-- name: AddOrderRefund :exec
UPDATE orders SET refunded_bdt = refunded_bdt + $2 WHERE number = $1
`

type AddOrderRefundParams struct {
	Number      string
	RefundedBdt int32
}

func (q *Queries) AddOrderRefund(ctx context.Context, arg AddOrderRefundParams) error {
	_, err := q.db.Exec(ctx, addOrderRefund, arg.Number, arg.RefundedBdt)
	return err
}

const addPointsEntry = `-- name: AddPointsEntry :exec
INSERT INTO points_entries (user_id, points, reason, order_number, at) VALUES ($1, $2, $3, $4, $5)
`

type AddPointsEntryParams struct {
	UserID      string
	Points      int32
	Reason      string
	OrderNumber pgtype.Text
	At          time.Time
}

func (q *Queries) AddPointsEntry(ctx context.Context, arg AddPointsEntryParams) error {
	_, err := q.db.Exec(ctx, addPointsEntry,
		arg.UserID,
		arg.Points,
		arg.Reason,
		arg.OrderNumber,
		arg.At,
	)
	return err
}

const addSale = `-- name: AddSale :exec
INSERT INTO sales_by_month (edition_id, month, copies) VALUES ($1, $2, $3)
ON CONFLICT (edition_id, month) DO UPDATE SET copies = sales_by_month.copies + EXCLUDED.copies
`

type AddSaleParams struct {
	EditionID string
	Month     time.Time
	Copies    int32
}

func (q *Queries) AddSale(ctx context.Context, arg AddSaleParams) error {
	_, err := q.db.Exec(ctx, addSale, arg.EditionID, arg.Month, arg.Copies)
	return err
}

const addWalletEntry = `-- name: AddWalletEntry :exec
INSERT INTO wallet_entries (user_id, amount_bdt, reason, order_number, note, at) VALUES ($1, $2, $3, $4, $5, $6)
`

type AddWalletEntryParams struct {
	UserID      string
	AmountBdt   int32
	Reason      string
	OrderNumber pgtype.Text
	Note        pgtype.Text
	At          time.Time
}

func (q *Queries) AddWalletEntry(ctx context.Context, arg AddWalletEntryParams) error {
	_, err := q.db.Exec(ctx, addWalletEntry,
		arg.UserID,
		arg.AmountBdt,
		arg.Reason,
		arg.OrderNumber,
		arg.Note,
		arg.At,
	)
	return err
}

const decideReturn = `-- name: DecideReturn :exec
UPDATE order_returns SET status = $2, decided_at = $3 WHERE order_number = $1
`

type DecideReturnParams struct {
	OrderNumber string
	Status      string
	DecidedAt   pgtype.Timestamptz
}

func (q *Queries) DecideReturn(ctx context.Context, arg DecideReturnParams) error {
	_, err := q.db.Exec(ctx, decideReturn, arg.OrderNumber, arg.Status, arg.DecidedAt)
	return err
}

const deliveredLinesOf = `-- name: DeliveredLinesOf :many
SELECT l.book_id, l.edition_id, o.number, h.at AS delivered_at
FROM orders o
JOIN order_lines l ON l.order_number = o.number
JOIN order_history h ON h.order_number = o.number AND h.status = 'delivered'
WHERE o.user_id = $1 AND o.status = 'delivered'
ORDER BY h.at, o.number, l.position
`

type DeliveredLinesOfRow struct {
	BookID      string
	EditionID   pgtype.Text
	Number      string
	DeliveredAt time.Time
}

func (q *Queries) DeliveredLinesOf(ctx context.Context, userID string) ([]DeliveredLinesOfRow, error) {
	rows, err := q.db.Query(ctx, deliveredLinesOf, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveredLinesOfRow{}
	for rows.Next() {
		var i DeliveredLinesOfRow
		if err := rows.Scan(
			&i.BookID,
			&i.EditionID,
			&i.Number,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoupon = `-- name: GetCoupon :one
SELECT code, position, kind, value, min_order_bdt, max_discount_bdt, expires_at, created_by FROM coupons WHERE code = $1
`

func (q *Queries) GetCoupon(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCoupon, code)
	var i Coupon
	err := row.Scan(
		&i.Code,
		&i.Position,
		&i.Kind,
		&i.Value,
		&i.MinOrderBdt,
		&i.MaxDiscountBdt,
		&i.ExpiresAt,
		&i.CreatedBy,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT number, user_id, status, placed_at, address_label, address_line, payment, subtotal_bdt, delivery_fee_bdt, discount_bdt, total_bdt, needs_delivery, points_used, points_earned, gift, gift_wrap_bdt, is_donation, donate_place_id, wallet_used_bdt, refunded_bdt FROM orders WHERE number = $1 FOR UPDATE
`

func (q *Queries) GetOrder(ctx context.Context, number string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, number)
	var i Order
	err := row.Scan(
		&i.Number,
		&i.UserID,
		&i.Status,
		&i.PlacedAt,
		&i.AddressLabel,
		&i.AddressLine,
		&i.Payment,
		&i.SubtotalBdt,
		&i.DeliveryFeeBdt,
		&i.DiscountBdt,
		&i.TotalBdt,
		&i.NeedsDelivery,
		&i.PointsUsed,
		&i.PointsEarned,
		&i.Gift,
		&i.GiftWrapBdt,
		&i.IsDonation,
		&i.DonatePlaceID,
		&i.WalletUsedBdt,
		&i.RefundedBdt,
	)
	return i, err
}

const insertCoupon = `-- name: InsertCoupon :execrows
INSERT INTO coupons (code, kind, value, min_order_bdt, max_discount_bdt, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (code) DO NOTHING
`

type InsertCouponParams struct {
	Code           string
	Kind           string
	Value          int32
	MinOrderBdt    int32
	MaxDiscountBdt pgtype.Int4
	ExpiresAt      pgtype.Timestamptz
	CreatedBy      pgtype.Text
}

func (q *Queries) InsertCoupon(ctx context.Context, arg InsertCouponParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCoupon,
		arg.Code,
		arg.Kind,
		arg.Value,
		arg.MinOrderBdt,
		arg.MaxDiscountBdt,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertOrder = `-- name: InsertOrder :exec
INSERT INTO orders (number, user_id, status, placed_at, address_label, address_line, payment, subtotal_bdt, delivery_fee_bdt,
                    discount_bdt, total_bdt, needs_delivery, points_used, points_earned, gift, gift_wrap_bdt, is_donation,
                    donate_place_id, wallet_used_bdt, refunded_bdt)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
`

type InsertOrderParams struct {
	Number         string
	UserID         string
	Status         string
	PlacedAt       time.Time
	AddressLabel   string
	AddressLine    string
	Payment        string
	SubtotalBdt    int32
	DeliveryFeeBdt int32
	DiscountBdt    int32
	TotalBdt       int32
	NeedsDelivery  bool
	PointsUsed     int32
	PointsEarned   int32
	Gift           []byte
	GiftWrapBdt    int32
	IsDonation     bool
	DonatePlaceID  pgtype.Text
	WalletUsedBdt  int32
	RefundedBdt    int32
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) error {
	_, err := q.db.Exec(ctx, insertOrder,
		arg.Number,
		arg.UserID,
		arg.Status,
		arg.PlacedAt,
		arg.AddressLabel,
		arg.AddressLine,
		arg.Payment,
		arg.SubtotalBdt,
		arg.DeliveryFeeBdt,
		arg.DiscountBdt,
		arg.TotalBdt,
		arg.NeedsDelivery,
		arg.PointsUsed,
		arg.PointsEarned,
		arg.Gift,
		arg.GiftWrapBdt,
		arg.IsDonation,
		arg.DonatePlaceID,
		arg.WalletUsedBdt,
		arg.RefundedBdt,
	)
	return err
}

const insertOrderHistory = `-- name: InsertOrderHistory :exec
INSERT INTO order_history (order_number, position, status, at)
VALUES ($1, (SELECT COALESCE(max(position), 0) + 1 FROM order_history WHERE order_number = $1), $2, $3)
`

type InsertOrderHistoryParams struct {
	OrderNumber string
	Status      string
	At          time.Time
}

func (q *Queries) InsertOrderHistory(ctx context.Context, arg InsertOrderHistoryParams) error {
	_, err := q.db.Exec(ctx, insertOrderHistory, arg.OrderNumber, arg.Status, arg.At)
	return err
}

const insertOrderLine = `-- name: InsertOrderLine :exec
INSERT INTO order_lines (order_number, position, book_id, edition_id, title, author, quantity, unit_price_bdt, format, language, cover_seed)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertOrderLineParams struct {
	OrderNumber  string
	Position     int32
	BookID       string
	EditionID    pgtype.Text
	Title        string
	Author       string
	Quantity     int32
	UnitPriceBdt int32
	Format       pgtype.Text
	Language     pgtype.Text
	CoverSeed    int32
}

func (q *Queries) InsertOrderLine(ctx context.Context, arg InsertOrderLineParams) error {
	_, err := q.db.Exec(ctx, insertOrderLine,
		arg.OrderNumber,
		arg.Position,
		arg.BookID,
		arg.EditionID,
		arg.Title,
		arg.Author,
		arg.Quantity,
		arg.UnitPriceBdt,
		arg.Format,
		arg.Language,
		arg.CoverSeed,
	)
	return err
}

const insertReturn = `-- name: InsertReturn :exec
INSERT INTO order_returns (order_number, reason, status, requested_at, note, photos)
VALUES ($1, $2, 'requested', $3, $4, $5)
`

type InsertReturnParams struct {
	OrderNumber string
	Reason      string
	RequestedAt time.Time
	Note        string
	Photos      []byte
}

func (q *Queries) InsertReturn(ctx context.Context, arg InsertReturnParams) error {
	_, err := q.db.Exec(ctx, insertReturn,
		arg.OrderNumber,
		arg.Reason,
		arg.RequestedAt,
		arg.Note,
		arg.Photos,
	)
	return err
}

const listAllOrders = `-- name: ListAllOrders :many
SELECT number, user_id, status, placed_at, address_label, address_line, payment, subtotal_bdt, delivery_fee_bdt, discount_bdt, total_bdt, needs_delivery, points_used, points_earned, gift, gift_wrap_bdt, is_donation, donate_place_id, wallet_used_bdt, refunded_bdt FROM orders ORDER BY placed_at DESC, number DESC
`

func (q *Queries) ListAllOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, listAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.Number,
			&i.UserID,
			&i.Status,
			&i.PlacedAt,
			&i.AddressLabel,
			&i.AddressLine,
			&i.Payment,
			&i.SubtotalBdt,
			&i.DeliveryFeeBdt,
			&i.DiscountBdt,
			&i.TotalBdt,
			&i.NeedsDelivery,
			&i.PointsUsed,
			&i.PointsEarned,
			&i.Gift,
			&i.GiftWrapBdt,
			&i.IsDonation,
			&i.DonatePlaceID,
			&i.WalletUsedBdt,
			&i.RefundedBdt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoupons = `-- name: ListCoupons :many
SELECT code, position, kind, value, min_order_bdt, max_discount_bdt, expires_at, created_by FROM coupons ORDER BY position DESC
`

func (q *Queries) ListCoupons(ctx context.Context) ([]Coupon, error) {
	rows, err := q.db.Query(ctx, listCoupons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Coupon{}
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.Code,
			&i.Position,
			&i.Kind,
			&i.Value,
			&i.MinOrderBdt,
			&i.MaxDiscountBdt,
			&i.ExpiresAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistoryOf = `-- name: ListHistoryOf :many
SELECT order_number, position, status, at FROM order_history WHERE order_number = ANY($1::text[]) ORDER BY order_number, position
`

func (q *Queries) ListHistoryOf(ctx context.Context, dollar_1 []string) ([]OrderHistory, error) {
	rows, err := q.db.Query(ctx, listHistoryOf, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderHistory{}
	for rows.Next() {
		var i OrderHistory
		if err := rows.Scan(
			&i.OrderNumber,
			&i.Position,
			&i.Status,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinesOf = `-- name: ListLinesOf :many
SELECT order_number, position, book_id, edition_id, title, author, quantity, unit_price_bdt, format, language, cover_seed FROM order_lines WHERE order_number = ANY($1::text[]) ORDER BY order_number, position
`

func (q *Queries) ListLinesOf(ctx context.Context, dollar_1 []string) ([]OrderLine, error) {
	rows, err := q.db.Query(ctx, listLinesOf, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderLine{}
	for rows.Next() {
		var i OrderLine
		if err := rows.Scan(
			&i.OrderNumber,
			&i.Position,
			&i.BookID,
			&i.EditionID,
			&i.Title,
			&i.Author,
			&i.Quantity,
			&i.UnitPriceBdt,
			&i.Format,
			&i.Language,
			&i.CoverSeed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersOf = `-- name: ListOrdersOf :many
SELECT number, user_id, status, placed_at, address_label, address_line, payment, subtotal_bdt, delivery_fee_bdt, discount_bdt, total_bdt, needs_delivery, points_used, points_earned, gift, gift_wrap_bdt, is_donation, donate_place_id, wallet_used_bdt, refunded_bdt FROM orders WHERE user_id = $1 ORDER BY placed_at DESC, number DESC
`

func (q *Queries) ListOrdersOf(ctx context.Context, userID string) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersOf, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.Number,
			&i.UserID,
			&i.Status,
			&i.PlacedAt,
			&i.AddressLabel,
			&i.AddressLine,
			&i.Payment,
			&i.SubtotalBdt,
			&i.DeliveryFeeBdt,
			&i.DiscountBdt,
			&i.TotalBdt,
			&i.NeedsDelivery,
			&i.PointsUsed,
			&i.PointsEarned,
			&i.Gift,
			&i.GiftWrapBdt,
			&i.IsDonation,
			&i.DonatePlaceID,
			&i.WalletUsedBdt,
			&i.RefundedBdt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPointsEntries = `-- name: ListPointsEntries :many
SELECT id, user_id, points, reason, order_number, at FROM points_entries WHERE user_id = $1 ORDER BY at DESC, id DESC
`

func (q *Queries) ListPointsEntries(ctx context.Context, userID string) ([]PointsEntry, error) {
	rows, err := q.db.Query(ctx, listPointsEntries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PointsEntry{}
	for rows.Next() {
		var i PointsEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Points,
			&i.Reason,
			&i.OrderNumber,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReturnsOf = `-- name: ListReturnsOf :many
SELECT order_number, reason, status, requested_at, decided_at, note, photos FROM order_returns WHERE order_number = ANY($1::text[])
`

func (q *Queries) ListReturnsOf(ctx context.Context, dollar_1 []string) ([]OrderReturn, error) {
	rows, err := q.db.Query(ctx, listReturnsOf, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderReturn{}
	for rows.Next() {
		var i OrderReturn
		if err := rows.Scan(
			&i.OrderNumber,
			&i.Reason,
			&i.Status,
			&i.RequestedAt,
			&i.DecidedAt,
			&i.Note,
			&i.Photos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletEntries = `-- name: ListWalletEntries :many
SELECT id, user_id, amount_bdt, reason, order_number, note, at FROM wallet_entries WHERE user_id = $1 ORDER BY at DESC, id DESC
`

func (q *Queries) ListWalletEntries(ctx context.Context, userID string) ([]WalletEntry, error) {
	rows, err := q.db.Query(ctx, listWalletEntries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletEntry{}
	for rows.Next() {
		var i WalletEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AmountBdt,
			&i.Reason,
			&i.OrderNumber,
			&i.Note,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :one
SELECT id FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUser(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	err := row.Scan(&id)
	return id, err
}

const pointsBalance = `-- name: PointsBalance :one
SELECT COALESCE(sum(points), 0)::bigint FROM points_entries WHERE user_id = $1
`

func (q *Queries) PointsBalance(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, pointsBalance, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const restockEdition = `-- name: RestockEdition :exec
UPDATE editions SET stock = stock + $2 WHERE id = $1 AND format <> 'ebook'
`

type RestockEditionParams struct {
	ID    string
	Stock int32
}

func (q *Queries) RestockEdition(ctx context.Context, arg RestockEditionParams) error {
	_, err := q.db.Exec(ctx, restockEdition, arg.ID, arg.Stock)
	return err
}

const setOrderStatus = `-- name: SetOrderStatus :exec
UPDATE orders SET status = $2 WHERE number = $1
`

type SetOrderStatusParams struct {
	Number string
	Status string
}

func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) error {
	_, err := q.db.Exec(ctx, setOrderStatus, arg.Number, arg.Status)
	return err
}

const takeStock = `-- name: TakeStock :exec
UPDATE editions SET stock = GREATEST(stock - $2, 0) WHERE id = $1 AND format <> 'ebook' AND stock > 0
`

type TakeStockParams struct {
	ID    string
	Stock int32
}

func (q *Queries) TakeStock(ctx context.Context, arg TakeStockParams) error {
	_, err := q.db.Exec(ctx, takeStock, arg.ID, arg.Stock)
	return err
}

const walletBalance = `-- name: WalletBalance :one
SELECT COALESCE(sum(amount_bdt), 0)::bigint FROM wallet_entries WHERE user_id = $1
`

func (q *Queries) WalletBalance(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, walletBalance, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
