// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: p2p.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countListingsInReview = `-- name: CountListingsInReview :one
SELECT count(*)::integer FROM listings l JOIN users u ON u.id = l.seller_id WHERE l.status = 'inReview' AND u.deleted_at IS NULL
`

func (q *Queries) CountListingsInReview(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countListingsInReview)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countLiveListingsOf = `-- name: CountLiveListingsOf :one
SELECT count(*)::integer FROM listings WHERE seller_id = $1 AND status = 'live'
`

func (q *Queries) CountLiveListingsOf(ctx context.Context, sellerID string) (int32, error) {
	row := q.db.QueryRow(ctx, countLiveListingsOf, sellerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countSoldBy = `-- name: CountSoldBy :one
SELECT count(*)::int FROM listings WHERE seller_id = $1 AND status = 'sold'
`

func (q *Queries) CountSoldBy(ctx context.Context, sellerID string) (int32, error) {
	row := q.db.QueryRow(ctx, countSoldBy, sellerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAllListingPhotosOf = `-- name: DeleteAllListingPhotosOf :many
DELETE FROM listing_photos WHERE listing_id IN (SELECT id FROM listings WHERE seller_id = $1) RETURNING public_id
`

func (q *Queries) DeleteAllListingPhotosOf(ctx context.Context, sellerID string) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteAllListingPhotosOf, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var public_id string
		if err := rows.Scan(&public_id); err != nil {
			return nil, err
		}
		items = append(items, public_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteListingPhotosExcept = `-- name: DeleteListingPhotosExcept :many
DELETE FROM listing_photos WHERE listing_id = $1::text AND NOT (slot = ANY($2::text[])) RETURNING public_id
`

type DeleteListingPhotosExceptParams struct {
	ListingID string
	Slots     []string
}

func (q *Queries) DeleteListingPhotosExcept(ctx context.Context, arg DeleteListingPhotosExceptParams) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteListingPhotosExcept, arg.ListingID, arg.Slots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var public_id string
		if err := rows.Scan(&public_id); err != nil {
			return nil, err
		}
		items = append(items, public_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePhotosOfListing = `-- name: DeletePhotosOfListing :many
DELETE FROM listing_photos WHERE listing_id = $1 RETURNING public_id
`

func (q *Queries) DeletePhotosOfListing(ctx context.Context, listingID string) ([]string, error) {
	rows, err := q.db.Query(ctx, deletePhotosOfListing, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var public_id string
		if err := rows.Scan(&public_id); err != nil {
			return nil, err
		}
		items = append(items, public_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListing = `-- name: GetListing :one
SELECT l.id, l.position, l.seller_id, l.title, l.price_bdt, l.condition, l.flags, l.is_negotiable, l.handover, l.status, l.rejection_reason, l.book_id, l.cover_seed, l.district, l.area, l.category_id, l.new_price_bdt, l.note, l.buyer_id, l.created_at, u.name AS seller_name
FROM listings l JOIN users u ON u.id = l.seller_id
WHERE l.id = $1
`

type GetListingRow struct {
	Listing    Listing
	SellerName string
}

func (q *Queries) GetListing(ctx context.Context, id string) (GetListingRow, error) {
	row := q.db.QueryRow(ctx, getListing, id)
	var i GetListingRow
	err := row.Scan(
		&i.Listing.ID,
		&i.Listing.Position,
		&i.Listing.SellerID,
		&i.Listing.Title,
		&i.Listing.PriceBdt,
		&i.Listing.Condition,
		&i.Listing.Flags,
		&i.Listing.IsNegotiable,
		&i.Listing.Handover,
		&i.Listing.Status,
		&i.Listing.RejectionReason,
		&i.Listing.BookID,
		&i.Listing.CoverSeed,
		&i.Listing.District,
		&i.Listing.Area,
		&i.Listing.CategoryID,
		&i.Listing.NewPriceBdt,
		&i.Listing.Note,
		&i.Listing.BuyerID,
		&i.Listing.CreatedAt,
		&i.SellerName,
	)
	return i, err
}

const getReader = `-- name: GetReader :one
SELECT id, name, area, district, member_since, sold_before FROM users WHERE id = $1 AND role = 'reader' AND deleted_at IS NULL
`

type GetReaderRow struct {
	ID          string
	Name        string
	Area        string
	District    string
	MemberSince time.Time
	SoldBefore  int32
}

func (q *Queries) GetReader(ctx context.Context, id string) (GetReaderRow, error) {
	row := q.db.QueryRow(ctx, getReader, id)
	var i GetReaderRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Area,
		&i.District,
		&i.MemberSince,
		&i.SoldBefore,
	)
	return i, err
}

const insertListing = `-- name: InsertListing :exec
INSERT INTO listings (id, seller_id, title, price_bdt, condition, flags, is_negotiable, handover, status, rejection_reason,
                      book_id, cover_seed, district, area, category_id, new_price_bdt, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
`

type InsertListingParams struct {
	ID              string
	SellerID        string
	Title           string
	PriceBdt        int32
	Condition       string
	Flags           []string
	IsNegotiable    bool
	Handover        string
	Status          string
	RejectionReason pgtype.Text
	BookID          pgtype.Text
	CoverSeed       int32
	District        pgtype.Text
	Area            pgtype.Text
	CategoryID      pgtype.Text
	NewPriceBdt     pgtype.Int4
	Note            pgtype.Text
}

func (q *Queries) InsertListing(ctx context.Context, arg InsertListingParams) error {
	_, err := q.db.Exec(ctx, insertListing,
		arg.ID,
		arg.SellerID,
		arg.Title,
		arg.PriceBdt,
		arg.Condition,
		arg.Flags,
		arg.IsNegotiable,
		arg.Handover,
		arg.Status,
		arg.RejectionReason,
		arg.BookID,
		arg.CoverSeed,
		arg.District,
		arg.Area,
		arg.CategoryID,
		arg.NewPriceBdt,
		arg.Note,
	)
	return err
}

const insertRating = `-- name: InsertRating :exec
INSERT INTO ratings (from_id, to_id, listing_id, stars, comment, at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertRatingParams struct {
	FromID    string
	ToID      string
	ListingID pgtype.Text
	Stars     int32
	Comment   pgtype.Text
	At        time.Time
}

func (q *Queries) InsertRating(ctx context.Context, arg InsertRatingParams) error {
	_, err := q.db.Exec(ctx, insertRating,
		arg.FromID,
		arg.ToID,
		arg.ListingID,
		arg.Stars,
		arg.Comment,
		arg.At,
	)
	return err
}

const listListingsForBook = `-- name: ListListingsForBook :many
SELECT l.id, l.position, l.seller_id, l.title, l.price_bdt, l.condition, l.flags, l.is_negotiable, l.handover, l.status, l.rejection_reason, l.book_id, l.cover_seed, l.district, l.area, l.category_id, l.new_price_bdt, l.note, l.buyer_id, l.created_at, u.name AS seller_name
FROM listings l JOIN users u ON u.id = l.seller_id
WHERE l.book_id = $1::text AND l.status = 'live' AND l.seller_id <> $2::text AND u.deleted_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM blocks b WHERE (b.user_id = $2::text AND b.blocked_id = l.seller_id)
                                            OR (b.user_id = l.seller_id AND b.blocked_id = $2::text))
ORDER BY l.position DESC
`

type ListListingsForBookParams struct {
	BookID string
	Viewer string
}

type ListListingsForBookRow struct {
	Listing    Listing
	SellerName string
}

func (q *Queries) ListListingsForBook(ctx context.Context, arg ListListingsForBookParams) ([]ListListingsForBookRow, error) {
	rows, err := q.db.Query(ctx, listListingsForBook, arg.BookID, arg.Viewer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListListingsForBookRow{}
	for rows.Next() {
		var i ListListingsForBookRow
		if err := rows.Scan(
			&i.Listing.ID,
			&i.Listing.Position,
			&i.Listing.SellerID,
			&i.Listing.Title,
			&i.Listing.PriceBdt,
			&i.Listing.Condition,
			&i.Listing.Flags,
			&i.Listing.IsNegotiable,
			&i.Listing.Handover,
			&i.Listing.Status,
			&i.Listing.RejectionReason,
			&i.Listing.BookID,
			&i.Listing.CoverSeed,
			&i.Listing.District,
			&i.Listing.Area,
			&i.Listing.CategoryID,
			&i.Listing.NewPriceBdt,
			&i.Listing.Note,
			&i.Listing.BuyerID,
			&i.Listing.CreatedAt,
			&i.SellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMineListings = `-- name: ListMineListings :many
SELECT l.id, l.position, l.seller_id, l.title, l.price_bdt, l.condition, l.flags, l.is_negotiable, l.handover, l.status, l.rejection_reason, l.book_id, l.cover_seed, l.district, l.area, l.category_id, l.new_price_bdt, l.note, l.buyer_id, l.created_at, u.name AS seller_name
FROM listings l JOIN users u ON u.id = l.seller_id
WHERE l.seller_id = $1
ORDER BY l.position DESC
`

type ListMineListingsRow struct {
	Listing    Listing
	SellerName string
}

func (q *Queries) ListMineListings(ctx context.Context, sellerID string) ([]ListMineListingsRow, error) {
	rows, err := q.db.Query(ctx, listMineListings, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMineListingsRow{}
	for rows.Next() {
		var i ListMineListingsRow
		if err := rows.Scan(
			&i.Listing.ID,
			&i.Listing.Position,
			&i.Listing.SellerID,
			&i.Listing.Title,
			&i.Listing.PriceBdt,
			&i.Listing.Condition,
			&i.Listing.Flags,
			&i.Listing.IsNegotiable,
			&i.Listing.Handover,
			&i.Listing.Status,
			&i.Listing.RejectionReason,
			&i.Listing.BookID,
			&i.Listing.CoverSeed,
			&i.Listing.District,
			&i.Listing.Area,
			&i.Listing.CategoryID,
			&i.Listing.NewPriceBdt,
			&i.Listing.Note,
			&i.Listing.BuyerID,
			&i.Listing.CreatedAt,
			&i.SellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenListings = `-- name: ListOpenListings :many
SELECT l.id, l.position, l.seller_id, l.title, l.price_bdt, l.condition, l.flags, l.is_negotiable, l.handover, l.status, l.rejection_reason, l.book_id, l.cover_seed, l.district, l.area, l.category_id, l.new_price_bdt, l.note, l.buyer_id, l.created_at, u.name AS seller_name
FROM listings l JOIN users u ON u.id = l.seller_id
WHERE u.deleted_at IS NULL
  AND CASE WHEN $1::boolean THEN l.status = 'live' AND l.seller_id <> $2::text
           ELSE l.status IN ('live', 'reserved') END
  AND NOT EXISTS (SELECT 1 FROM blocks b WHERE (b.user_id = $2::text AND b.blocked_id = l.seller_id)
                                            OR (b.user_id = l.seller_id AND b.blocked_id = $2::text))
ORDER BY l.position DESC
LIMIT COALESCE($3::int, 1000000)
`

type ListOpenListingsParams struct {
	OnlyAvailable bool
	Viewer        string
	Lim           pgtype.Int4
}

type ListOpenListingsRow struct {
	Listing    Listing
	SellerName string
}

// On sale or reserved, newest first. only_available keeps the live ones of other readers.
// Listings of deleted accounts, and of readers who blocked the viewer or were blocked by the viewer, stay out.
func (q *Queries) ListOpenListings(ctx context.Context, arg ListOpenListingsParams) ([]ListOpenListingsRow, error) {
	rows, err := q.db.Query(ctx, listOpenListings, arg.OnlyAvailable, arg.Viewer, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenListingsRow{}
	for rows.Next() {
		var i ListOpenListingsRow
		if err := rows.Scan(
			&i.Listing.ID,
			&i.Listing.Position,
			&i.Listing.SellerID,
			&i.Listing.Title,
			&i.Listing.PriceBdt,
			&i.Listing.Condition,
			&i.Listing.Flags,
			&i.Listing.IsNegotiable,
			&i.Listing.Handover,
			&i.Listing.Status,
			&i.Listing.RejectionReason,
			&i.Listing.BookID,
			&i.Listing.CoverSeed,
			&i.Listing.District,
			&i.Listing.Area,
			&i.Listing.CategoryID,
			&i.Listing.NewPriceBdt,
			&i.Listing.Note,
			&i.Listing.BuyerID,
			&i.Listing.CreatedAt,
			&i.SellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotosOf = `-- name: ListPhotosOf :many
SELECT listing_id, slot, position, url, public_id FROM listing_photos WHERE listing_id = ANY($1::text[]) ORDER BY listing_id, position
`

func (q *Queries) ListPhotosOf(ctx context.Context, dollar_1 []string) ([]ListingPhoto, error) {
	rows, err := q.db.Query(ctx, listPhotosOf, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListingPhoto{}
	for rows.Next() {
		var i ListingPhoto
		if err := rows.Scan(
			&i.ListingID,
			&i.Slot,
			&i.Position,
			&i.Url,
			&i.PublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatingsForListings = `-- name: ListRatingsForListings :many
SELECT listing_id, from_id, stars FROM ratings WHERE listing_id = ANY($1::text[])
`

type ListRatingsForListingsRow struct {
	ListingID pgtype.Text
	FromID    string
	Stars     int32
}

func (q *Queries) ListRatingsForListings(ctx context.Context, dollar_1 []string) ([]ListRatingsForListingsRow, error) {
	rows, err := q.db.Query(ctx, listRatingsForListings, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRatingsForListingsRow{}
	for rows.Next() {
		var i ListRatingsForListingsRow
		if err := rows.Scan(&i.ListingID, &i.FromID, &i.Stars); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatingsTo = `-- name: ListRatingsTo :many
SELECT r.stars, r.at, r.comment, u.name AS from_name
FROM ratings r JOIN users u ON u.id = r.from_id
WHERE r.to_id = $1 ORDER BY r.at DESC, r.id DESC
`

type ListRatingsToRow struct {
	Stars    int32
	At       time.Time
	Comment  pgtype.Text
	FromName string
}

func (q *Queries) ListRatingsTo(ctx context.Context, toID string) ([]ListRatingsToRow, error) {
	rows, err := q.db.Query(ctx, listRatingsTo, toID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRatingsToRow{}
	for rows.Next() {
		var i ListRatingsToRow
		if err := rows.Scan(
			&i.Stars,
			&i.At,
			&i.Comment,
			&i.FromName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listingCandidates = `-- name: ListingCandidates :many
SELECT l.id, l.title, l.book_id, l.seller_id, l.status, u.name AS seller_name
FROM listings l JOIN users u ON u.id = l.seller_id
WHERE l.status <> 'sold' AND u.deleted_at IS NULL AND l.seller_id <> $1::text
  AND (NOT $2::boolean OR l.status = 'live')
ORDER BY l.position DESC
`

type ListingCandidatesParams struct {
	ExcludedSeller string
	OnlyLive       bool
}

type ListingCandidatesRow struct {
	ID         string
	Title      string
	BookID     pgtype.Text
	SellerID   string
	Status     string
	SellerName string
}

// Copies that may match a book request: not sold, of readers other than excluded_seller.
func (q *Queries) ListingCandidates(ctx context.Context, arg ListingCandidatesParams) ([]ListingCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listingCandidates, arg.ExcludedSeller, arg.OnlyLive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListingCandidatesRow{}
	for rows.Next() {
		var i ListingCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.BookID,
			&i.SellerID,
			&i.Status,
			&i.SellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listingQueue = `-- name: ListingQueue :many
SELECT l.id, l.position, l.seller_id, l.title, l.price_bdt, l.condition, l.flags, l.is_negotiable, l.handover, l.status, l.rejection_reason, l.book_id, l.cover_seed, l.district, l.area, l.category_id, l.new_price_bdt, l.note, l.buyer_id, l.created_at, u.name AS seller_name, u.strikes AS seller_strikes
FROM listings l JOIN users u ON u.id = l.seller_id
WHERE l.status = 'inReview' AND u.deleted_at IS NULL
ORDER BY l.position DESC
`

type ListingQueueRow struct {
	Listing       Listing
	SellerName    string
	SellerStrikes int32
}

func (q *Queries) ListingQueue(ctx context.Context) ([]ListingQueueRow, error) {
	rows, err := q.db.Query(ctx, listingQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListingQueueRow{}
	for rows.Next() {
		var i ListingQueueRow
		if err := rows.Scan(
			&i.Listing.ID,
			&i.Listing.Position,
			&i.Listing.SellerID,
			&i.Listing.Title,
			&i.Listing.PriceBdt,
			&i.Listing.Condition,
			&i.Listing.Flags,
			&i.Listing.IsNegotiable,
			&i.Listing.Handover,
			&i.Listing.Status,
			&i.Listing.RejectionReason,
			&i.Listing.BookID,
			&i.Listing.CoverSeed,
			&i.Listing.District,
			&i.Listing.Area,
			&i.Listing.CategoryID,
			&i.Listing.NewPriceBdt,
			&i.Listing.Note,
			&i.Listing.BuyerID,
			&i.Listing.CreatedAt,
			&i.SellerName,
			&i.SellerStrikes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listingsOfSeller = `-- name: ListingsOfSeller :many
SELECT l.id, l.title, l.book_id, l.seller_id, l.status, u.name AS seller_name
FROM listings l JOIN users u ON u.id = l.seller_id
WHERE l.seller_id = $1 AND l.status <> 'sold'
ORDER BY l.position DESC
`

type ListingsOfSellerRow struct {
	ID         string
	Title      string
	BookID     pgtype.Text
	SellerID   string
	Status     string
	SellerName string
}

func (q *Queries) ListingsOfSeller(ctx context.Context, sellerID string) ([]ListingsOfSellerRow, error) {
	rows, err := q.db.Query(ctx, listingsOfSeller, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListingsOfSellerRow{}
	for rows.Next() {
		var i ListingsOfSellerRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.BookID,
			&i.SellerID,
			&i.Status,
			&i.SellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveListingsOf = `-- name: LiveListingsOf :many
SELECT l.id, l.position, l.seller_id, l.title, l.price_bdt, l.condition, l.flags, l.is_negotiable, l.handover, l.status, l.rejection_reason, l.book_id, l.cover_seed, l.district, l.area, l.category_id, l.new_price_bdt, l.note, l.buyer_id, l.created_at, u.name AS seller_name
FROM listings l JOIN users u ON u.id = l.seller_id
WHERE l.seller_id = $1 AND l.status = 'live'
ORDER BY l.position DESC
`

type LiveListingsOfRow struct {
	Listing    Listing
	SellerName string
}

func (q *Queries) LiveListingsOf(ctx context.Context, sellerID string) ([]LiveListingsOfRow, error) {
	rows, err := q.db.Query(ctx, liveListingsOf, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LiveListingsOfRow{}
	for rows.Next() {
		var i LiveListingsOfRow
		if err := rows.Scan(
			&i.Listing.ID,
			&i.Listing.Position,
			&i.Listing.SellerID,
			&i.Listing.Title,
			&i.Listing.PriceBdt,
			&i.Listing.Condition,
			&i.Listing.Flags,
			&i.Listing.IsNegotiable,
			&i.Listing.Handover,
			&i.Listing.Status,
			&i.Listing.RejectionReason,
			&i.Listing.BookID,
			&i.Listing.CoverSeed,
			&i.Listing.District,
			&i.Listing.Area,
			&i.Listing.CategoryID,
			&i.Listing.NewPriceBdt,
			&i.Listing.Note,
			&i.Listing.BuyerID,
			&i.Listing.CreatedAt,
			&i.SellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockListing = `-- name: LockListing :one
SELECT id, position, seller_id, title, price_bdt, condition, flags, is_negotiable, handover, status, rejection_reason, book_id, cover_seed, district, area, category_id, new_price_bdt, note, buyer_id, created_at FROM listings WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockListing(ctx context.Context, id string) (Listing, error) {
	row := q.db.QueryRow(ctx, lockListing, id)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.SellerID,
		&i.Title,
		&i.PriceBdt,
		&i.Condition,
		&i.Flags,
		&i.IsNegotiable,
		&i.Handover,
		&i.Status,
		&i.RejectionReason,
		&i.BookID,
		&i.CoverSeed,
		&i.District,
		&i.Area,
		&i.CategoryID,
		&i.NewPriceBdt,
		&i.Note,
		&i.BuyerID,
		&i.CreatedAt,
	)
	return i, err
}

const seedListing = `-- name: SeedListing :exec
INSERT INTO listings (id, position, seller_id, title, price_bdt, condition, flags, is_negotiable, handover, status, rejection_reason,
                      book_id, cover_seed, district, area, category_id, new_price_bdt, note, buyer_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
ON CONFLICT (id) DO NOTHING
`

type SeedListingParams struct {
	ID              string
	Position        int64
	SellerID        string
	Title           string
	PriceBdt        int32
	Condition       string
	Flags           []string
	IsNegotiable    bool
	Handover        string
	Status          string
	RejectionReason pgtype.Text
	BookID          pgtype.Text
	CoverSeed       int32
	District        pgtype.Text
	Area            pgtype.Text
	CategoryID      pgtype.Text
	NewPriceBdt     pgtype.Int4
	Note            pgtype.Text
	BuyerID         pgtype.Text
}

func (q *Queries) SeedListing(ctx context.Context, arg SeedListingParams) error {
	_, err := q.db.Exec(ctx, seedListing,
		arg.ID,
		arg.Position,
		arg.SellerID,
		arg.Title,
		arg.PriceBdt,
		arg.Condition,
		arg.Flags,
		arg.IsNegotiable,
		arg.Handover,
		arg.Status,
		arg.RejectionReason,
		arg.BookID,
		arg.CoverSeed,
		arg.District,
		arg.Area,
		arg.CategoryID,
		arg.NewPriceBdt,
		arg.Note,
		arg.BuyerID,
	)
	return err
}

const seedListingPhoto = `-- name: SeedListingPhoto :exec
INSERT INTO listing_photos (listing_id, slot, position) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type SeedListingPhotoParams struct {
	ListingID string
	Slot      string
	Position  int32
}

func (q *Queries) SeedListingPhoto(ctx context.Context, arg SeedListingPhotoParams) error {
	_, err := q.db.Exec(ctx, seedListingPhoto, arg.ListingID, arg.Slot, arg.Position)
	return err
}

const seedRating = `-- name: SeedRating :exec
INSERT INTO ratings (from_id, to_id, listing_id, stars, comment, at)
SELECT $1::text, $2::text, $3::text, $4::int, $5::text, $6::timestamptz
WHERE NOT EXISTS (SELECT 1 FROM ratings WHERE from_id = $1::text AND to_id = $2::text AND stars = $4::int
                  AND COALESCE(comment, '') = COALESCE($5::text, ''))
`

type SeedRatingParams struct {
	FromID    string
	ToID      string
	ListingID pgtype.Text
	Stars     int32
	Comment   pgtype.Text
	At        time.Time
}

func (q *Queries) SeedRating(ctx context.Context, arg SeedRatingParams) error {
	_, err := q.db.Exec(ctx, seedRating,
		arg.FromID,
		arg.ToID,
		arg.ListingID,
		arg.Stars,
		arg.Comment,
		arg.At,
	)
	return err
}

const seedSoldBefore = `-- name: SeedSoldBefore :exec
UPDATE users SET sold_before = $2 WHERE id = $1
`

type SeedSoldBeforeParams struct {
	ID         string
	SoldBefore int32
}

func (q *Queries) SeedSoldBefore(ctx context.Context, arg SeedSoldBeforeParams) error {
	_, err := q.db.Exec(ctx, seedSoldBefore, arg.ID, arg.SoldBefore)
	return err
}

const setListingStatus = `-- name: SetListingStatus :exec
UPDATE listings SET status = $2, rejection_reason = $3, buyer_id = $4 WHERE id = $1
`

type SetListingStatusParams struct {
	ID              string
	Status          string
	RejectionReason pgtype.Text
	BuyerID         pgtype.Text
}

func (q *Queries) SetListingStatus(ctx context.Context, arg SetListingStatusParams) error {
	_, err := q.db.Exec(ctx, setListingStatus,
		arg.ID,
		arg.Status,
		arg.RejectionReason,
		arg.BuyerID,
	)
	return err
}

const updateListing = `-- name: UpdateListing :exec
UPDATE listings SET title = $2, price_bdt = $3, condition = $4, flags = $5, is_negotiable = $6, handover = $7, status = $8,
                    rejection_reason = $9, book_id = $10, new_price_bdt = $11, note = $12
WHERE id = $1
`

type UpdateListingParams struct {
	ID              string
	Title           string
	PriceBdt        int32
	Condition       string
	Flags           []string
	IsNegotiable    bool
	Handover        string
	Status          string
	RejectionReason pgtype.Text
	BookID          pgtype.Text
	NewPriceBdt     pgtype.Int4
	Note            pgtype.Text
}

func (q *Queries) UpdateListing(ctx context.Context, arg UpdateListingParams) error {
	_, err := q.db.Exec(ctx, updateListing,
		arg.ID,
		arg.Title,
		arg.PriceBdt,
		arg.Condition,
		arg.Flags,
		arg.IsNegotiable,
		arg.Handover,
		arg.Status,
		arg.RejectionReason,
		arg.BookID,
		arg.NewPriceBdt,
		arg.Note,
	)
	return err
}

const upsertListingPhoto = `-- name: UpsertListingPhoto :exec
INSERT INTO listing_photos (listing_id, slot, position, url, public_id) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (listing_id, slot) DO UPDATE SET url = EXCLUDED.url, public_id = EXCLUDED.public_id, position = EXCLUDED.position
`

type UpsertListingPhotoParams struct {
	ListingID string
	Slot      string
	Position  int32
	Url       string
	PublicID  string
}

func (q *Queries) UpsertListingPhoto(ctx context.Context, arg UpsertListingPhotoParams) error {
	_, err := q.db.Exec(ctx, upsertListingPhoto,
		arg.ListingID,
		arg.Slot,
		arg.Position,
		arg.Url,
		arg.PublicID,
	)
	return err
}
