// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: profile.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const anonymiseUser = `-- name: AnonymiseUser :exec
UPDATE users
SET deleted_at = $2, email = NULL, name = 'Deleted reader', phone = '', photo_url = NULL,
    photo_data = NULL, password_hash = NULL
WHERE id = $1
`

type AnonymiseUserParams struct {
	ID        string
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) AnonymiseUser(ctx context.Context, arg AnonymiseUserParams) error {
	_, err := q.db.Exec(ctx, anonymiseUser, arg.ID, arg.DeletedAt)
	return err
}

const clearDefaultAddress = `-- name: ClearDefaultAddress :exec
UPDATE addresses SET is_default = false WHERE user_id = $1 AND is_default
`

func (q *Queries) ClearDefaultAddress(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, clearDefaultAddress, userID)
	return err
}

const countAddresses = `-- name: CountAddresses :one
SELECT count(*) FROM addresses WHERE user_id = $1
`

func (q *Queries) CountAddresses(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAddresses, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM addresses WHERE user_id = $1 AND id = $2
`

type DeleteAddressParams struct {
	UserID string
	ID     string
}

func (q *Queries) DeleteAddress(ctx context.Context, arg DeleteAddressParams) error {
	_, err := q.db.Exec(ctx, deleteAddress, arg.UserID, arg.ID)
	return err
}

const deleteAddresses = `-- name: DeleteAddresses :exec
DELETE FROM addresses WHERE user_id = $1
`

func (q *Queries) DeleteAddresses(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAddresses, userID)
	return err
}

const deletePrefs = `-- name: DeletePrefs :exec
DELETE FROM profile_prefs WHERE user_id = $1
`

func (q *Queries) DeletePrefs(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deletePrefs, userID)
	return err
}

const firstAddressID = `-- name: FirstAddressID :one
SELECT id FROM addresses WHERE user_id = $1 ORDER BY position LIMIT 1
`

func (q *Queries) FirstAddressID(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, firstAddressID, userID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getAddress = `-- name: GetAddress :one
SELECT id, label, recipient, phone, line, upazila, district, division, is_default
FROM addresses WHERE user_id = $1 AND id = $2 FOR UPDATE
`

type GetAddressParams struct {
	UserID string
	ID     string
}

type GetAddressRow struct {
	ID        string
	Label     string
	Recipient string
	Phone     string
	Line      string
	Upazila   string
	District  string
	Division  string
	IsDefault bool
}

func (q *Queries) GetAddress(ctx context.Context, arg GetAddressParams) (GetAddressRow, error) {
	row := q.db.QueryRow(ctx, getAddress, arg.UserID, arg.ID)
	var i GetAddressRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Recipient,
		&i.Phone,
		&i.Line,
		&i.Upazila,
		&i.District,
		&i.Division,
		&i.IsDefault,
	)
	return i, err
}

const getPrefs = `-- name: GetPrefs :one
SELECT muted, profile_visible, activity_visible FROM profile_prefs WHERE user_id = $1
`

type GetPrefsRow struct {
	Muted           []string
	ProfileVisible  bool
	ActivityVisible bool
}

func (q *Queries) GetPrefs(ctx context.Context, userID string) (GetPrefsRow, error) {
	row := q.db.QueryRow(ctx, getPrefs, userID)
	var i GetPrefsRow
	err := row.Scan(&i.Muted, &i.ProfileVisible, &i.ActivityVisible)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT name, phone, photo_data FROM users WHERE id = $1 AND deleted_at IS NULL
`

type GetProfileRow struct {
	Name      string
	Phone     string
	PhotoData pgtype.Text
}

func (q *Queries) GetProfile(ctx context.Context, id string) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i GetProfileRow
	err := row.Scan(&i.Name, &i.Phone, &i.PhotoData)
	return i, err
}

const insertAddress = `-- name: InsertAddress :exec
INSERT INTO addresses (id, user_id, label, recipient, phone, line, upazila, district, division, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertAddressParams struct {
	ID        string
	UserID    string
	Label     string
	Recipient string
	Phone     string
	Line      string
	Upazila   string
	District  string
	Division  string
	IsDefault bool
}

func (q *Queries) InsertAddress(ctx context.Context, arg InsertAddressParams) error {
	_, err := q.db.Exec(ctx, insertAddress,
		arg.ID,
		arg.UserID,
		arg.Label,
		arg.Recipient,
		arg.Phone,
		arg.Line,
		arg.Upazila,
		arg.District,
		arg.Division,
		arg.IsDefault,
	)
	return err
}

const listAddresses = `-- name: ListAddresses :many
SELECT id, label, recipient, phone, line, upazila, district, division, is_default
FROM addresses WHERE user_id = $1
ORDER BY is_default DESC, position
`

type ListAddressesRow struct {
	ID        string
	Label     string
	Recipient string
	Phone     string
	Line      string
	Upazila   string
	District  string
	Division  string
	IsDefault bool
}

func (q *Queries) ListAddresses(ctx context.Context, userID string) ([]ListAddressesRow, error) {
	rows, err := q.db.Query(ctx, listAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAddressesRow{}
	for rows.Next() {
		var i ListAddressesRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Recipient,
			&i.Phone,
			&i.Line,
			&i.Upazila,
			&i.District,
			&i.Division,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveProfile = `-- name: SaveProfile :exec
UPDATE users SET name = $2, phone = $3, photo_data = $4 WHERE id = $1
`

type SaveProfileParams struct {
	ID        string
	Name      string
	Phone     string
	PhotoData pgtype.Text
}

func (q *Queries) SaveProfile(ctx context.Context, arg SaveProfileParams) error {
	_, err := q.db.Exec(ctx, saveProfile,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.PhotoData,
	)
	return err
}

const setDefaultAddress = `-- name: SetDefaultAddress :exec
UPDATE addresses SET is_default = true WHERE user_id = $1 AND id = $2
`

type SetDefaultAddressParams struct {
	UserID string
	ID     string
}

func (q *Queries) SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) error {
	_, err := q.db.Exec(ctx, setDefaultAddress, arg.UserID, arg.ID)
	return err
}

const updateAddress = `-- name: UpdateAddress :exec
UPDATE addresses
SET label = $3, recipient = $4, phone = $5, line = $6, upazila = $7, district = $8, division = $9
WHERE user_id = $1 AND id = $2
`

type UpdateAddressParams struct {
	UserID    string
	ID        string
	Label     string
	Recipient string
	Phone     string
	Line      string
	Upazila   string
	District  string
	Division  string
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) error {
	_, err := q.db.Exec(ctx, updateAddress,
		arg.UserID,
		arg.ID,
		arg.Label,
		arg.Recipient,
		arg.Phone,
		arg.Line,
		arg.Upazila,
		arg.District,
		arg.Division,
	)
	return err
}

const upsertPrefs = `-- name: UpsertPrefs :exec
INSERT INTO profile_prefs (user_id, muted, profile_visible, activity_visible)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET muted = EXCLUDED.muted, profile_visible = EXCLUDED.profile_visible,
    activity_visible = EXCLUDED.activity_visible
`

type UpsertPrefsParams struct {
	UserID          string
	Muted           []string
	ProfileVisible  bool
	ActivityVisible bool
}

func (q *Queries) UpsertPrefs(ctx context.Context, arg UpsertPrefsParams) error {
	_, err := q.db.Exec(ctx, upsertPrefs,
		arg.UserID,
		arg.Muted,
		arg.ProfileVisible,
		arg.ActivityVisible,
	)
	return err
}
