// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: readers.sql

package sqlc

import (
	"context"
	"time"
)

const follow = `-- name: Follow :execrows
INSERT INTO follows (follower_id, followee_id, at) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type FollowParams struct {
	FollowerID string
	FolloweeID string
	At         time.Time
}

func (q *Queries) Follow(ctx context.Context, arg FollowParams) (int64, error) {
	result, err := q.db.Exec(ctx, follow, arg.FollowerID, arg.FolloweeID, arg.At)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const followCounts = `-- name: FollowCounts :one
SELECT (SELECT count(*) FROM follows f JOIN users u ON u.id = f.follower_id WHERE f.followee_id = $1 AND u.deleted_at IS NULL)::integer AS followers,
       (SELECT count(*) FROM follows f JOIN users u ON u.id = f.followee_id WHERE f.follower_id = $1 AND u.deleted_at IS NULL)::integer AS following
`

type FollowCountsRow struct {
	Followers int32
	Following int32
}

func (q *Queries) FollowCounts(ctx context.Context, followeeID string) (FollowCountsRow, error) {
	row := q.db.QueryRow(ctx, followCounts, followeeID)
	var i FollowCountsRow
	err := row.Scan(&i.Followers, &i.Following)
	return i, err
}

const getReaderPage = `-- name: GetReaderPage :one
SELECT id, name, area, district, member_since FROM users WHERE id = $1 AND deleted_at IS NULL
`

type GetReaderPageRow struct {
	ID          string
	Name        string
	Area        string
	District    string
	MemberSince time.Time
}

func (q *Queries) GetReaderPage(ctx context.Context, id string) (GetReaderPageRow, error) {
	row := q.db.QueryRow(ctx, getReaderPage, id)
	var i GetReaderPageRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Area,
		&i.District,
		&i.MemberSince,
	)
	return i, err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS (SELECT 1 FROM follows WHERE follower_id = $1 AND followee_id = $2)
`

type IsFollowingParams struct {
	FollowerID string
	FolloweeID string
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FolloweeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFollowing = `-- name: ListFollowing :many
SELECT followee_id FROM follows WHERE follower_id = $1
`

func (q *Queries) ListFollowing(ctx context.Context, followerID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listFollowing, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var followee_id string
		if err := rows.Scan(&followee_id); err != nil {
			return nil, err
		}
		items = append(items, followee_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedFollow = `-- name: SeedFollow :exec
INSERT INTO follows (follower_id, followee_id, at) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type SeedFollowParams struct {
	FollowerID string
	FolloweeID string
	At         time.Time
}

func (q *Queries) SeedFollow(ctx context.Context, arg SeedFollowParams) error {
	_, err := q.db.Exec(ctx, seedFollow, arg.FollowerID, arg.FolloweeID, arg.At)
	return err
}

const seedPrivateProfile = `-- name: SeedPrivateProfile :exec
INSERT INTO profile_prefs (user_id, profile_visible) VALUES ($1, false) ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) SeedPrivateProfile(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, seedPrivateProfile, userID)
	return err
}

const unfollow = `-- name: Unfollow :exec
DELETE FROM follows WHERE follower_id = $1 AND followee_id = $2
`

type UnfollowParams struct {
	FollowerID string
	FolloweeID string
}

func (q *Queries) Unfollow(ctx context.Context, arg UnfollowParams) error {
	_, err := q.db.Exec(ctx, unfollow, arg.FollowerID, arg.FolloweeID)
	return err
}
