// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: report.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addBlock = `-- name: AddBlock :exec
INSERT INTO blocks (user_id, blocked_id, at) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type AddBlockParams struct {
	UserID    string
	BlockedID string
	At        time.Time
}

func (q *Queries) AddBlock(ctx context.Context, arg AddBlockParams) error {
	_, err := q.db.Exec(ctx, addBlock, arg.UserID, arg.BlockedID, arg.At)
	return err
}

const closeReportsAbout = `-- name: CloseReportsAbout :exec
UPDATE reports SET status = $3 WHERE kind = $1 AND target_id = $2 AND status = 'open'
`

type CloseReportsAboutParams struct {
	Kind     string
	TargetID string
	Status   string
}

func (q *Queries) CloseReportsAbout(ctx context.Context, arg CloseReportsAboutParams) error {
	_, err := q.db.Exec(ctx, closeReportsAbout, arg.Kind, arg.TargetID, arg.Status)
	return err
}

const findOpenReport = `-- name: FindOpenReport :one
SELECT id, position, kind, target_id, reason, note, reporter_id, status, created_at FROM reports WHERE reporter_id = $1 AND kind = $2 AND target_id = $3 AND status = 'open' ORDER BY position LIMIT 1
`

type FindOpenReportParams struct {
	ReporterID string
	Kind       string
	TargetID   string
}

func (q *Queries) FindOpenReport(ctx context.Context, arg FindOpenReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, findOpenReport, arg.ReporterID, arg.Kind, arg.TargetID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.Kind,
		&i.TargetID,
		&i.Reason,
		&i.Note,
		&i.ReporterID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenReport = `-- name: GetOpenReport :one
SELECT id, position, kind, target_id, reason, note, reporter_id, status, created_at FROM reports WHERE id = $1 AND status = 'open' FOR UPDATE
`

func (q *Queries) GetOpenReport(ctx context.Context, id string) (Report, error) {
	row := q.db.QueryRow(ctx, getOpenReport, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.Kind,
		&i.TargetID,
		&i.Reason,
		&i.Note,
		&i.ReporterID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertReport = `-- name: InsertReport :exec
INSERT INTO reports (id, kind, target_id, reason, note, reporter_id, status, created_at) VALUES ($1, $2, $3, $4, $5, $6, 'open', $7)
`

type InsertReportParams struct {
	ID         string
	Kind       string
	TargetID   string
	Reason     string
	Note       pgtype.Text
	ReporterID string
	CreatedAt  time.Time
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) error {
	_, err := q.db.Exec(ctx, insertReport,
		arg.ID,
		arg.Kind,
		arg.TargetID,
		arg.Reason,
		arg.Note,
		arg.ReporterID,
		arg.CreatedAt,
	)
	return err
}

const isBlockedEither = `-- name: IsBlockedEither :one
SELECT EXISTS (SELECT 1 FROM blocks WHERE (user_id = $1 AND blocked_id = $2) OR (user_id = $2 AND blocked_id = $1))
`

type IsBlockedEitherParams struct {
	UserID    string
	BlockedID string
}

func (q *Queries) IsBlockedEither(ctx context.Context, arg IsBlockedEitherParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlockedEither, arg.UserID, arg.BlockedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBlockedEither = `-- name: ListBlockedEither :many
SELECT b.blocked_id FROM blocks b WHERE b.user_id = $1::text
UNION
SELECT b.user_id FROM blocks b WHERE b.blocked_id = $1::text
`

// Everyone the reader blocked or who blocked the reader.
func (q *Queries) ListBlockedEither(ctx context.Context, reader string) ([]string, error) {
	rows, err := q.db.Query(ctx, listBlockedEither, reader)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blocked_id string
		if err := rows.Scan(&blocked_id); err != nil {
			return nil, err
		}
		items = append(items, blocked_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocks = `-- name: ListBlocks :many
SELECT b.blocked_id, b.at, u.name FROM blocks b JOIN users u ON u.id = b.blocked_id
WHERE b.user_id = $1 ORDER BY b.at DESC, b.blocked_id
`

type ListBlocksRow struct {
	BlockedID string
	At        time.Time
	Name      string
}

func (q *Queries) ListBlocks(ctx context.Context, userID string) ([]ListBlocksRow, error) {
	rows, err := q.db.Query(ctx, listBlocks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlocksRow{}
	for rows.Next() {
		var i ListBlocksRow
		if err := rows.Scan(&i.BlockedID, &i.At, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenReports = `-- name: ListOpenReports :many
SELECT id, position, kind, target_id, reason, note, reporter_id, status, created_at FROM reports WHERE status = 'open' ORDER BY created_at, position
`

func (q *Queries) ListOpenReports(ctx context.Context) ([]Report, error) {
	rows, err := q.db.Query(ctx, listOpenReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Kind,
			&i.TargetID,
			&i.Reason,
			&i.Note,
			&i.ReporterID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBlock = `-- name: RemoveBlock :exec
DELETE FROM blocks WHERE user_id = $1 AND blocked_id = $2
`

type RemoveBlockParams struct {
	UserID    string
	BlockedID string
}

func (q *Queries) RemoveBlock(ctx context.Context, arg RemoveBlockParams) error {
	_, err := q.db.Exec(ctx, removeBlock, arg.UserID, arg.BlockedID)
	return err
}

const seedReport = `-- name: SeedReport :exec
INSERT INTO reports (id, kind, target_id, reason, note, reporter_id, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, 'open', $7) ON CONFLICT (id) DO NOTHING
`

type SeedReportParams struct {
	ID         string
	Kind       string
	TargetID   string
	Reason     string
	Note       pgtype.Text
	ReporterID string
	CreatedAt  time.Time
}

func (q *Queries) SeedReport(ctx context.Context, arg SeedReportParams) error {
	_, err := q.db.Exec(ctx, seedReport,
		arg.ID,
		arg.Kind,
		arg.TargetID,
		arg.Reason,
		arg.Note,
		arg.ReporterID,
		arg.CreatedAt,
	)
	return err
}
