// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reviews.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews WHERE book_id = $1 AND user_id = $2
`

type DeleteReviewParams struct {
	BookID string
	UserID string
}

func (q *Queries) DeleteReview(ctx context.Context, arg DeleteReviewParams) error {
	_, err := q.db.Exec(ctx, deleteReview, arg.BookID, arg.UserID)
	return err
}

const editReview = `-- name: EditReview :exec
UPDATE reviews SET stars = $3, text = $4, edited_at = $5 WHERE book_id = $1 AND user_id = $2
`

type EditReviewParams struct {
	BookID   string
	UserID   string
	Stars    int32
	Text     string
	EditedAt pgtype.Timestamptz
}

func (q *Queries) EditReview(ctx context.Context, arg EditReviewParams) error {
	_, err := q.db.Exec(ctx, editReview,
		arg.BookID,
		arg.UserID,
		arg.Stars,
		arg.Text,
		arg.EditedAt,
	)
	return err
}

const findReview = `-- name: FindReview :one
SELECT id, book_id, user_id, stars, text, seed_verified, created_at, edited_at FROM reviews WHERE id = $1
`

func (q *Queries) FindReview(ctx context.Context, id string) (Review, error) {
	row := q.db.QueryRow(ctx, findReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.UserID,
		&i.Stars,
		&i.Text,
		&i.SeedVerified,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const getReviewOf = `-- name: GetReviewOf :one
SELECT id, book_id, user_id, stars, text, seed_verified, created_at, edited_at FROM reviews WHERE book_id = $1 AND user_id = $2
`

type GetReviewOfParams struct {
	BookID string
	UserID string
}

func (q *Queries) GetReviewOf(ctx context.Context, arg GetReviewOfParams) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewOf, arg.BookID, arg.UserID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.UserID,
		&i.Stars,
		&i.Text,
		&i.SeedVerified,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const insertReview = `-- name: InsertReview :exec
INSERT INTO reviews (id, book_id, user_id, stars, text, created_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertReviewParams struct {
	ID        string
	BookID    string
	UserID    string
	Stars     int32
	Text      string
	CreatedAt time.Time
}

func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) error {
	_, err := q.db.Exec(ctx, insertReview,
		arg.ID,
		arg.BookID,
		arg.UserID,
		arg.Stars,
		arg.Text,
		arg.CreatedAt,
	)
	return err
}

const listReviews = `-- name: ListReviews :many
SELECT r.id, r.book_id, r.user_id, r.stars, r.text, r.seed_verified, r.created_at, r.edited_at, u.name AS author_name
FROM reviews r JOIN users u ON u.id = r.user_id
WHERE r.book_id = $1 AND u.deleted_at IS NULL
ORDER BY r.created_at DESC, r.id DESC
`

type ListReviewsRow struct {
	ID           string
	BookID       string
	UserID       string
	Stars        int32
	Text         string
	SeedVerified bool
	CreatedAt    time.Time
	EditedAt     pgtype.Timestamptz
	AuthorName   string
}

func (q *Queries) ListReviews(ctx context.Context, bookID string) ([]ListReviewsRow, error) {
	rows, err := q.db.Query(ctx, listReviews, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsRow{}
	for rows.Next() {
		var i ListReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.UserID,
			&i.Stars,
			&i.Text,
			&i.SeedVerified,
			&i.CreatedAt,
			&i.EditedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewStats = `-- name: ReviewStats :one
SELECT count(*)::integer AS count, coalesce(avg(stars), 0)::float8 AS average FROM reviews WHERE book_id = $1
`

type ReviewStatsRow struct {
	Count   int32
	Average float64
}

func (q *Queries) ReviewStats(ctx context.Context, bookID string) (ReviewStatsRow, error) {
	row := q.db.QueryRow(ctx, reviewStats, bookID)
	var i ReviewStatsRow
	err := row.Scan(&i.Count, &i.Average)
	return i, err
}

const seedReview = `-- name: SeedReview :exec
INSERT INTO reviews (id, book_id, user_id, stars, text, seed_verified, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT DO NOTHING
`

type SeedReviewParams struct {
	ID           string
	BookID       string
	UserID       string
	Stars        int32
	Text         string
	SeedVerified bool
	CreatedAt    time.Time
}

func (q *Queries) SeedReview(ctx context.Context, arg SeedReviewParams) error {
	_, err := q.db.Exec(ctx, seedReview,
		arg.ID,
		arg.BookID,
		arg.UserID,
		arg.Stars,
		arg.Text,
		arg.SeedVerified,
		arg.CreatedAt,
	)
	return err
}
