// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: seed_buying.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertSeedBundle = `-- name: UpsertSeedBundle :exec
INSERT INTO bundles (id, position, title, edition_ids, price_bdt) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
SET position = EXCLUDED.position, title = EXCLUDED.title, edition_ids = EXCLUDED.edition_ids,
    price_bdt = EXCLUDED.price_bdt
`

type UpsertSeedBundleParams struct {
	ID         string
	Position   int32
	Title      string
	EditionIds []string
	PriceBdt   int32
}

func (q *Queries) UpsertSeedBundle(ctx context.Context, arg UpsertSeedBundleParams) error {
	_, err := q.db.Exec(ctx, upsertSeedBundle,
		arg.ID,
		arg.Position,
		arg.Title,
		arg.EditionIds,
		arg.PriceBdt,
	)
	return err
}

const upsertSeedFlashItem = `-- name: UpsertSeedFlashItem :exec
INSERT INTO flash_sale_items (edition_id, position, price_bdt) VALUES ($1, $2, $3)
ON CONFLICT (edition_id) DO UPDATE SET position = EXCLUDED.position, price_bdt = EXCLUDED.price_bdt
`

type UpsertSeedFlashItemParams struct {
	EditionID string
	Position  int32
	PriceBdt  int32
}

func (q *Queries) UpsertSeedFlashItem(ctx context.Context, arg UpsertSeedFlashItemParams) error {
	_, err := q.db.Exec(ctx, upsertSeedFlashItem, arg.EditionID, arg.Position, arg.PriceBdt)
	return err
}

const upsertSeedPerson = `-- name: UpsertSeedPerson :exec
INSERT INTO users (id, email, name, role, password_hash, area, district, member_since, sold_before)
VALUES ($1, $2, $3, 'reader', $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE
SET email = EXCLUDED.email, name = EXCLUDED.name, area = EXCLUDED.area, district = EXCLUDED.district,
    member_since = EXCLUDED.member_since, sold_before = EXCLUDED.sold_before,
    password_hash = COALESCE(users.password_hash, EXCLUDED.password_hash)
`

type UpsertSeedPersonParams struct {
	ID           string
	Email        pgtype.Text
	Name         string
	PasswordHash pgtype.Text
	Area         string
	District     string
	MemberSince  time.Time
	SoldBefore   int32
}

func (q *Queries) UpsertSeedPerson(ctx context.Context, arg UpsertSeedPersonParams) error {
	_, err := q.db.Exec(ctx, upsertSeedPerson,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Area,
		arg.District,
		arg.MemberSince,
		arg.SoldBefore,
	)
	return err
}

const upsertSeedPreorder = `-- name: UpsertSeedPreorder :exec
INSERT INTO preorders (edition_id, position) VALUES ($1, $2)
ON CONFLICT (edition_id) DO UPDATE SET position = EXCLUDED.position
`

type UpsertSeedPreorderParams struct {
	EditionID string
	Position  int32
}

func (q *Queries) UpsertSeedPreorder(ctx context.Context, arg UpsertSeedPreorderParams) error {
	_, err := q.db.Exec(ctx, upsertSeedPreorder, arg.EditionID, arg.Position)
	return err
}

const upsertSeedShare = `-- name: UpsertSeedShare :exec
INSERT INTO wishlist_shares (id, user_id, owner_name) VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET owner_name = EXCLUDED.owner_name
`

type UpsertSeedShareParams struct {
	ID        string
	UserID    string
	OwnerName string
}

func (q *Queries) UpsertSeedShare(ctx context.Context, arg UpsertSeedShareParams) error {
	_, err := q.db.Exec(ctx, upsertSeedShare, arg.ID, arg.UserID, arg.OwnerName)
	return err
}

const upsertSeedWishlistItem = `-- name: UpsertSeedWishlistItem :exec
INSERT INTO wishlist_items (user_id, book_id, added_at) VALUES ($1, $2, $3)
ON CONFLICT (user_id, book_id) DO NOTHING
`

type UpsertSeedWishlistItemParams struct {
	UserID  string
	BookID  string
	AddedAt time.Time
}

func (q *Queries) UpsertSeedWishlistItem(ctx context.Context, arg UpsertSeedWishlistItemParams) error {
	_, err := q.db.Exec(ctx, upsertSeedWishlistItem, arg.UserID, arg.BookID, arg.AddedAt)
	return err
}
