// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: seed.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const setUserRoleByEmail = `-- name: SetUserRoleByEmail :execrows
UPDATE users SET role = $2 WHERE email = $1 AND deleted_at IS NULL
`

type SetUserRoleByEmailParams struct {
	Email pgtype.Text
	Role  string
}

func (q *Queries) SetUserRoleByEmail(ctx context.Context, arg SetUserRoleByEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserRoleByEmail, arg.Email, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSeedUser = `-- name: UpsertSeedUser :exec
INSERT INTO users (id, email, name, role, password_hash, member_since)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE
SET email = EXCLUDED.email, name = EXCLUDED.name, role = EXCLUDED.role,
    password_hash = COALESCE(users.password_hash, EXCLUDED.password_hash)
`

type UpsertSeedUserParams struct {
	ID           string
	Email        pgtype.Text
	Name         string
	Role         string
	PasswordHash pgtype.Text
	MemberSince  time.Time
}

func (q *Queries) UpsertSeedUser(ctx context.Context, arg UpsertSeedUserParams) error {
	_, err := q.db.Exec(ctx, upsertSeedUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.PasswordHash,
		arg.MemberSince,
	)
	return err
}
