// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: seed_sales.sql

package sqlc

import (
	"context"
)

const seedBookQuoteBasis = `-- name: SeedBookQuoteBasis :one
SELECT b.title, b.author, b.cover_seed, min(e.price_bdt)::integer AS new_price_bdt
FROM books b JOIN editions e ON e.book_id = b.id AND e.format <> 'ebook'
WHERE b.id = $1
GROUP BY b.id
`

type SeedBookQuoteBasisRow struct {
	Title       string
	Author      string
	CoverSeed   int32
	NewPriceBdt int32
}

// What Sell Back quotes from: the book and its cheapest printed Edition.
func (q *Queries) SeedBookQuoteBasis(ctx context.Context, id string) (SeedBookQuoteBasisRow, error) {
	row := q.db.QueryRow(ctx, seedBookQuoteBasis, id)
	var i SeedBookQuoteBasisRow
	err := row.Scan(
		&i.Title,
		&i.Author,
		&i.CoverSeed,
		&i.NewPriceBdt,
	)
	return i, err
}
