// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: seed_catalog.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertSeedAnswer = `-- name: UpsertSeedAnswer :exec
INSERT INTO book_answers (id, question_id, author_name, text, answered_at, is_staff)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO NOTHING
`

type UpsertSeedAnswerParams struct {
	ID         string
	QuestionID string
	AuthorName string
	Text       string
	AnsweredAt time.Time
	IsStaff    bool
}

func (q *Queries) UpsertSeedAnswer(ctx context.Context, arg UpsertSeedAnswerParams) error {
	_, err := q.db.Exec(ctx, upsertSeedAnswer,
		arg.ID,
		arg.QuestionID,
		arg.AuthorName,
		arg.Text,
		arg.AnsweredAt,
		arg.IsStaff,
	)
	return err
}

const upsertSeedAuthor = `-- name: UpsertSeedAuthor :exec
INSERT INTO authors (id, name, name_bn, bio) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_bn = EXCLUDED.name_bn, bio = EXCLUDED.bio
`

type UpsertSeedAuthorParams struct {
	ID     string
	Name   string
	NameBn pgtype.Text
	Bio    pgtype.Text
}

func (q *Queries) UpsertSeedAuthor(ctx context.Context, arg UpsertSeedAuthorParams) error {
	_, err := q.db.Exec(ctx, upsertSeedAuthor,
		arg.ID,
		arg.Name,
		arg.NameBn,
		arg.Bio,
	)
	return err
}

const upsertSeedBook = `-- name: UpsertSeedBook :exec
INSERT INTO books (id, title, title_bn, short_title, author, author_id, publisher_id, category_id, section,
                   original_language, added_at, rating, tags, cover_seed, hidden, classes, exams, subject_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ON CONFLICT (id) DO UPDATE
SET title = EXCLUDED.title, title_bn = EXCLUDED.title_bn, short_title = EXCLUDED.short_title,
    author = EXCLUDED.author, author_id = EXCLUDED.author_id, publisher_id = EXCLUDED.publisher_id,
    category_id = EXCLUDED.category_id, section = EXCLUDED.section, original_language = EXCLUDED.original_language,
    added_at = EXCLUDED.added_at, rating = EXCLUDED.rating, tags = EXCLUDED.tags, cover_seed = EXCLUDED.cover_seed,
    classes = EXCLUDED.classes, exams = EXCLUDED.exams, subject_id = EXCLUDED.subject_id
`

type UpsertSeedBookParams struct {
	ID               string
	Title            string
	TitleBn          pgtype.Text
	ShortTitle       pgtype.Text
	Author           string
	AuthorID         string
	PublisherID      string
	CategoryID       string
	Section          string
	OriginalLanguage string
	AddedAt          time.Time
	Rating           float64
	Tags             []string
	CoverSeed        int32
	Hidden           bool
	Classes          []int32
	Exams            []string
	SubjectID        pgtype.Text
}

func (q *Queries) UpsertSeedBook(ctx context.Context, arg UpsertSeedBookParams) error {
	_, err := q.db.Exec(ctx, upsertSeedBook,
		arg.ID,
		arg.Title,
		arg.TitleBn,
		arg.ShortTitle,
		arg.Author,
		arg.AuthorID,
		arg.PublisherID,
		arg.CategoryID,
		arg.Section,
		arg.OriginalLanguage,
		arg.AddedAt,
		arg.Rating,
		arg.Tags,
		arg.CoverSeed,
		arg.Hidden,
		arg.Classes,
		arg.Exams,
		arg.SubjectID,
	)
	return err
}

const upsertSeedBookDetails = `-- name: UpsertSeedBookDetails :exec
INSERT INTO book_details (book_id, description, pages) VALUES ($1, $2, $3)
ON CONFLICT (book_id) DO UPDATE SET description = EXCLUDED.description, pages = EXCLUDED.pages
`

type UpsertSeedBookDetailsParams struct {
	BookID      string
	Description string
	Pages       int32
}

func (q *Queries) UpsertSeedBookDetails(ctx context.Context, arg UpsertSeedBookDetailsParams) error {
	_, err := q.db.Exec(ctx, upsertSeedBookDetails, arg.BookID, arg.Description, arg.Pages)
	return err
}

const upsertSeedBooklist = `-- name: UpsertSeedBooklist :exec
INSERT INTO booklists (id, owner_id, kind, title_en, title_bn, note_en, note_bn, book_ids)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE
SET owner_id = EXCLUDED.owner_id, kind = EXCLUDED.kind, title_en = EXCLUDED.title_en,
    title_bn = EXCLUDED.title_bn, note_en = EXCLUDED.note_en, note_bn = EXCLUDED.note_bn,
    book_ids = EXCLUDED.book_ids
`

type UpsertSeedBooklistParams struct {
	ID      string
	OwnerID pgtype.Text
	Kind    string
	TitleEn string
	TitleBn string
	NoteEn  pgtype.Text
	NoteBn  pgtype.Text
	BookIds []string
}

func (q *Queries) UpsertSeedBooklist(ctx context.Context, arg UpsertSeedBooklistParams) error {
	_, err := q.db.Exec(ctx, upsertSeedBooklist,
		arg.ID,
		arg.OwnerID,
		arg.Kind,
		arg.TitleEn,
		arg.TitleBn,
		arg.NoteEn,
		arg.NoteBn,
		arg.BookIds,
	)
	return err
}

const upsertSeedCategory = `-- name: UpsertSeedCategory :exec
INSERT INTO categories (id, section, name_en, name_bn) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, name_en = EXCLUDED.name_en, name_bn = EXCLUDED.name_bn
`

type UpsertSeedCategoryParams struct {
	ID      string
	Section string
	NameEn  string
	NameBn  string
}

func (q *Queries) UpsertSeedCategory(ctx context.Context, arg UpsertSeedCategoryParams) error {
	_, err := q.db.Exec(ctx, upsertSeedCategory,
		arg.ID,
		arg.Section,
		arg.NameEn,
		arg.NameBn,
	)
	return err
}

const upsertSeedCollection = `-- name: UpsertSeedCollection :exec
INSERT INTO collections (id, title_en, title_bn, note_en, note_bn, section, expert_id, book_ids)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE
SET title_en = EXCLUDED.title_en, title_bn = EXCLUDED.title_bn, note_en = EXCLUDED.note_en,
    note_bn = EXCLUDED.note_bn, section = EXCLUDED.section, expert_id = EXCLUDED.expert_id,
    book_ids = EXCLUDED.book_ids
`

type UpsertSeedCollectionParams struct {
	ID       string
	TitleEn  string
	TitleBn  string
	NoteEn   string
	NoteBn   string
	Section  pgtype.Text
	ExpertID pgtype.Text
	BookIds  []string
}

func (q *Queries) UpsertSeedCollection(ctx context.Context, arg UpsertSeedCollectionParams) error {
	_, err := q.db.Exec(ctx, upsertSeedCollection,
		arg.ID,
		arg.TitleEn,
		arg.TitleBn,
		arg.NoteEn,
		arg.NoteBn,
		arg.Section,
		arg.ExpertID,
		arg.BookIds,
	)
	return err
}

const upsertSeedEdition = `-- name: UpsertSeedEdition :exec
INSERT INTO editions (id, book_id, format, language, price_bdt, list_price_bdt, stock, is_preorder, isbn)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE
SET book_id = EXCLUDED.book_id, format = EXCLUDED.format, language = EXCLUDED.language,
    price_bdt = EXCLUDED.price_bdt, list_price_bdt = EXCLUDED.list_price_bdt, is_preorder = EXCLUDED.is_preorder,
    isbn = EXCLUDED.isbn
`

type UpsertSeedEditionParams struct {
	ID           string
	BookID       string
	Format       string
	Language     string
	PriceBdt     int32
	ListPriceBdt pgtype.Int4
	Stock        int32
	IsPreorder   bool
	Isbn         pgtype.Text
}

func (q *Queries) UpsertSeedEdition(ctx context.Context, arg UpsertSeedEditionParams) error {
	_, err := q.db.Exec(ctx, upsertSeedEdition,
		arg.ID,
		arg.BookID,
		arg.Format,
		arg.Language,
		arg.PriceBdt,
		arg.ListPriceBdt,
		arg.Stock,
		arg.IsPreorder,
		arg.Isbn,
	)
	return err
}

const upsertSeedExpert = `-- name: UpsertSeedExpert :exec
INSERT INTO experts (id, name, name_bn, credential_en, credential_bn, kind, verified)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name, name_bn = EXCLUDED.name_bn, credential_en = EXCLUDED.credential_en,
    credential_bn = EXCLUDED.credential_bn, kind = EXCLUDED.kind, verified = EXCLUDED.verified
`

type UpsertSeedExpertParams struct {
	ID           string
	Name         string
	NameBn       string
	CredentialEn string
	CredentialBn string
	Kind         string
	Verified     bool
}

func (q *Queries) UpsertSeedExpert(ctx context.Context, arg UpsertSeedExpertParams) error {
	_, err := q.db.Exec(ctx, upsertSeedExpert,
		arg.ID,
		arg.Name,
		arg.NameBn,
		arg.CredentialEn,
		arg.CredentialBn,
		arg.Kind,
		arg.Verified,
	)
	return err
}

const upsertSeedLookInside = `-- name: UpsertSeedLookInside :exec
INSERT INTO look_inside (book_id, contents, sample_pages) VALUES ($1, $2, $3)
ON CONFLICT (book_id) DO UPDATE SET contents = EXCLUDED.contents, sample_pages = EXCLUDED.sample_pages
`

type UpsertSeedLookInsideParams struct {
	BookID      string
	Contents    []byte
	SamplePages []byte
}

func (q *Queries) UpsertSeedLookInside(ctx context.Context, arg UpsertSeedLookInsideParams) error {
	_, err := q.db.Exec(ctx, upsertSeedLookInside, arg.BookID, arg.Contents, arg.SamplePages)
	return err
}

const upsertSeedPriceLow = `-- name: UpsertSeedPriceLow :exec
INSERT INTO price_lows (edition_id, low_bdt, since) VALUES ($1, $2, $3)
ON CONFLICT (edition_id) DO UPDATE SET low_bdt = EXCLUDED.low_bdt
`

type UpsertSeedPriceLowParams struct {
	EditionID string
	LowBdt    int32
	Since     time.Time
}

func (q *Queries) UpsertSeedPriceLow(ctx context.Context, arg UpsertSeedPriceLowParams) error {
	_, err := q.db.Exec(ctx, upsertSeedPriceLow, arg.EditionID, arg.LowBdt, arg.Since)
	return err
}

const upsertSeedPublisher = `-- name: UpsertSeedPublisher :exec
INSERT INTO publishers (id, name, name_bn) VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_bn = EXCLUDED.name_bn
`

type UpsertSeedPublisherParams struct {
	ID     string
	Name   string
	NameBn pgtype.Text
}

func (q *Queries) UpsertSeedPublisher(ctx context.Context, arg UpsertSeedPublisherParams) error {
	_, err := q.db.Exec(ctx, upsertSeedPublisher, arg.ID, arg.Name, arg.NameBn)
	return err
}

const upsertSeedQuestion = `-- name: UpsertSeedQuestion :exec
INSERT INTO book_questions (id, book_id, asker_name, text, asked_at) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO NOTHING
`

type UpsertSeedQuestionParams struct {
	ID        string
	BookID    string
	AskerName string
	Text      string
	AskedAt   time.Time
}

func (q *Queries) UpsertSeedQuestion(ctx context.Context, arg UpsertSeedQuestionParams) error {
	_, err := q.db.Exec(ctx, upsertSeedQuestion,
		arg.ID,
		arg.BookID,
		arg.AskerName,
		arg.Text,
		arg.AskedAt,
	)
	return err
}

const upsertSeedSales = `-- name: UpsertSeedSales :exec
INSERT INTO sales_by_month (edition_id, month, copies) VALUES ($1, $2, $3)
ON CONFLICT (edition_id, month) DO UPDATE SET copies = EXCLUDED.copies
`

type UpsertSeedSalesParams struct {
	EditionID string
	Month     time.Time
	Copies    int32
}

func (q *Queries) UpsertSeedSales(ctx context.Context, arg UpsertSeedSalesParams) error {
	_, err := q.db.Exec(ctx, upsertSeedSales, arg.EditionID, arg.Month, arg.Copies)
	return err
}

const upsertSeedSeries = `-- name: UpsertSeedSeries :exec
INSERT INTO series (id, name, entries) VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, entries = EXCLUDED.entries
`

type UpsertSeedSeriesParams struct {
	ID      string
	Name    string
	Entries []byte
}

func (q *Queries) UpsertSeedSeries(ctx context.Context, arg UpsertSeedSeriesParams) error {
	_, err := q.db.Exec(ctx, upsertSeedSeries, arg.ID, arg.Name, arg.Entries)
	return err
}

const upsertSeedSubject = `-- name: UpsertSeedSubject :exec
INSERT INTO subjects (id, name_en, name_bn) VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET name_en = EXCLUDED.name_en, name_bn = EXCLUDED.name_bn
`

type UpsertSeedSubjectParams struct {
	ID     string
	NameEn string
	NameBn string
}

func (q *Queries) UpsertSeedSubject(ctx context.Context, arg UpsertSeedSubjectParams) error {
	_, err := q.db.Exec(ctx, upsertSeedSubject, arg.ID, arg.NameEn, arg.NameBn)
	return err
}
