// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: seed_orders.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const seedOrderExists = `-- name: SeedOrderExists :one
SELECT EXISTS (SELECT 1 FROM orders WHERE number = $1)
`

func (q *Queries) SeedOrderExists(ctx context.Context, number string) (bool, error) {
	row := q.db.QueryRow(ctx, seedOrderExists, number)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const seedOrderHistory = `-- name: SeedOrderHistory :exec
INSERT INTO order_history (order_number, position, status, at) VALUES ($1, $2, $3, $4)
`

type SeedOrderHistoryParams struct {
	OrderNumber string
	Position    int32
	Status      string
	At          time.Time
}

func (q *Queries) SeedOrderHistory(ctx context.Context, arg SeedOrderHistoryParams) error {
	_, err := q.db.Exec(ctx, seedOrderHistory,
		arg.OrderNumber,
		arg.Position,
		arg.Status,
		arg.At,
	)
	return err
}

const seedPointsEntryExists = `-- name: SeedPointsEntryExists :one
SELECT EXISTS (SELECT 1 FROM points_entries WHERE user_id = $1 AND reason = $2 AND COALESCE(order_number, '') = $3)
`

type SeedPointsEntryExistsParams struct {
	UserID      string
	Reason      string
	OrderNumber pgtype.Text
}

func (q *Queries) SeedPointsEntryExists(ctx context.Context, arg SeedPointsEntryExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, seedPointsEntryExists, arg.UserID, arg.Reason, arg.OrderNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const seedWalletEntryExists = `-- name: SeedWalletEntryExists :one
SELECT EXISTS (SELECT 1 FROM wallet_entries WHERE user_id = $1 AND reason = $2 AND COALESCE(note, '') = $3 AND order_number IS NULL)
`

type SeedWalletEntryExistsParams struct {
	UserID string
	Reason string
	Note   pgtype.Text
}

func (q *Queries) SeedWalletEntryExists(ctx context.Context, arg SeedWalletEntryExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, seedWalletEntryExists, arg.UserID, arg.Reason, arg.Note)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertSeedCoupon = `-- name: UpsertSeedCoupon :exec
INSERT INTO coupons (code, kind, value, min_order_bdt, max_discount_bdt, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (code) DO UPDATE
SET kind = EXCLUDED.kind, value = EXCLUDED.value, min_order_bdt = EXCLUDED.min_order_bdt,
    max_discount_bdt = EXCLUDED.max_discount_bdt, expires_at = EXCLUDED.expires_at
`

type UpsertSeedCouponParams struct {
	Code           string
	Kind           string
	Value          int32
	MinOrderBdt    int32
	MaxDiscountBdt pgtype.Int4
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) UpsertSeedCoupon(ctx context.Context, arg UpsertSeedCouponParams) error {
	_, err := q.db.Exec(ctx, upsertSeedCoupon,
		arg.Code,
		arg.Kind,
		arg.Value,
		arg.MinOrderBdt,
		arg.MaxDiscountBdt,
		arg.ExpiresAt,
	)
	return err
}
