// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: seed_home.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertSeedAyah = `-- name: UpsertSeedAyah :exec
INSERT INTO ayahs (position, arabic, translation, surah_en, surah_bn, surah_number, verse_number)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (position) DO UPDATE
SET arabic = EXCLUDED.arabic, translation = EXCLUDED.translation, surah_en = EXCLUDED.surah_en,
    surah_bn = EXCLUDED.surah_bn, surah_number = EXCLUDED.surah_number, verse_number = EXCLUDED.verse_number
`

type UpsertSeedAyahParams struct {
	Position    int32
	Arabic      string
	Translation string
	SurahEn     string
	SurahBn     string
	SurahNumber int32
	VerseNumber int32
}

func (q *Queries) UpsertSeedAyah(ctx context.Context, arg UpsertSeedAyahParams) error {
	_, err := q.db.Exec(ctx, upsertSeedAyah,
		arg.Position,
		arg.Arabic,
		arg.Translation,
		arg.SurahEn,
		arg.SurahBn,
		arg.SurahNumber,
		arg.VerseNumber,
	)
	return err
}

const upsertSeedBanner = `-- name: UpsertSeedBanner :exec
INSERT INTO banners (id, position, title_en, title_bn, subtitle_en, subtitle_bn, seed, target_kind, target_value, season)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO UPDATE
SET title_en = EXCLUDED.title_en, title_bn = EXCLUDED.title_bn, subtitle_en = EXCLUDED.subtitle_en,
    subtitle_bn = EXCLUDED.subtitle_bn, seed = EXCLUDED.seed, target_kind = EXCLUDED.target_kind,
    target_value = EXCLUDED.target_value, season = EXCLUDED.season
`

type UpsertSeedBannerParams struct {
	ID          string
	Position    int32
	TitleEn     string
	TitleBn     string
	SubtitleEn  string
	SubtitleBn  string
	Seed        int32
	TargetKind  string
	TargetValue string
	Season      pgtype.Text
}

func (q *Queries) UpsertSeedBanner(ctx context.Context, arg UpsertSeedBannerParams) error {
	_, err := q.db.Exec(ctx, upsertSeedBanner,
		arg.ID,
		arg.Position,
		arg.TitleEn,
		arg.TitleBn,
		arg.SubtitleEn,
		arg.SubtitleBn,
		arg.Seed,
		arg.TargetKind,
		arg.TargetValue,
		arg.Season,
	)
	return err
}

const upsertSeedIsbn = `-- name: UpsertSeedIsbn :exec
INSERT INTO isbn_lookup (isbn, title, title_bn, author, publisher, language, format, list_price_bdt)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (isbn) DO UPDATE
SET title = EXCLUDED.title, title_bn = EXCLUDED.title_bn, author = EXCLUDED.author,
    publisher = EXCLUDED.publisher, language = EXCLUDED.language, format = EXCLUDED.format,
    list_price_bdt = EXCLUDED.list_price_bdt
`

type UpsertSeedIsbnParams struct {
	Isbn         string
	Title        string
	TitleBn      pgtype.Text
	Author       string
	Publisher    string
	Language     string
	Format       string
	ListPriceBdt int32
}

func (q *Queries) UpsertSeedIsbn(ctx context.Context, arg UpsertSeedIsbnParams) error {
	_, err := q.db.Exec(ctx, upsertSeedIsbn,
		arg.Isbn,
		arg.Title,
		arg.TitleBn,
		arg.Author,
		arg.Publisher,
		arg.Language,
		arg.Format,
		arg.ListPriceBdt,
	)
	return err
}
