// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sellback.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const cheapestCertified = `-- name: CheapestCertified :one
SELECT id, book_id, condition, price_bdt, created_at, sold_at FROM certified_used WHERE book_id = $1 AND sold_at IS NULL ORDER BY price_bdt, id LIMIT 1
`

func (q *Queries) CheapestCertified(ctx context.Context, bookID string) (CertifiedUsed, error) {
	row := q.db.QueryRow(ctx, cheapestCertified, bookID)
	var i CertifiedUsed
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Condition,
		&i.PriceBdt,
		&i.CreatedAt,
		&i.SoldAt,
	)
	return i, err
}

const countCertifiedOf = `-- name: CountCertifiedOf :one
SELECT count(*)::bigint FROM certified_used WHERE book_id = $1
`

func (q *Queries) CountCertifiedOf(ctx context.Context, bookID string) (int64, error) {
	row := q.db.QueryRow(ctx, countCertifiedOf, bookID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSellBackQueue = `-- name: CountSellBackQueue :one
SELECT count(*)::bigint FROM sell_backs WHERE status = 'pickedUp'
`

func (q *Queries) CountSellBackQueue(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSellBackQueue)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getCertified = `-- name: GetCertified :one
SELECT id, book_id, condition, price_bdt, created_at, sold_at FROM certified_used WHERE id = $1 AND sold_at IS NULL
`

func (q *Queries) GetCertified(ctx context.Context, id string) (CertifiedUsed, error) {
	row := q.db.QueryRow(ctx, getCertified, id)
	var i CertifiedUsed
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Condition,
		&i.PriceBdt,
		&i.CreatedAt,
		&i.SoldAt,
	)
	return i, err
}

const gradeSellBack = `-- name: GradeSellBack :exec
UPDATE sell_backs SET status = $2, graded_condition = $3, paid_bdt = $4 WHERE id = $1
`

type GradeSellBackParams struct {
	ID              string
	Status          string
	GradedCondition pgtype.Text
	PaidBdt         pgtype.Int4
}

func (q *Queries) GradeSellBack(ctx context.Context, arg GradeSellBackParams) error {
	_, err := q.db.Exec(ctx, gradeSellBack,
		arg.ID,
		arg.Status,
		arg.GradedCondition,
		arg.PaidBdt,
	)
	return err
}

const insertCertified = `-- name: InsertCertified :exec
INSERT INTO certified_used (id, book_id, condition, price_bdt, created_at) VALUES ($1, $2, $3, $4, $5)
`

type InsertCertifiedParams struct {
	ID        string
	BookID    string
	Condition string
	PriceBdt  int32
	CreatedAt time.Time
}

func (q *Queries) InsertCertified(ctx context.Context, arg InsertCertifiedParams) error {
	_, err := q.db.Exec(ctx, insertCertified,
		arg.ID,
		arg.BookID,
		arg.Condition,
		arg.PriceBdt,
		arg.CreatedAt,
	)
	return err
}

const insertSellBack = `-- name: InsertSellBack :exec
INSERT INTO sell_backs (id, user_id, book_id, title, author, new_price_bdt, cover_seed, condition, flags, quote_bdt, pickup_address, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertSellBackParams struct {
	ID            string
	UserID        string
	BookID        string
	Title         string
	Author        string
	NewPriceBdt   int32
	CoverSeed     int32
	Condition     string
	Flags         int32
	QuoteBdt      int32
	PickupAddress string
	CreatedAt     time.Time
}

func (q *Queries) InsertSellBack(ctx context.Context, arg InsertSellBackParams) error {
	_, err := q.db.Exec(ctx, insertSellBack,
		arg.ID,
		arg.UserID,
		arg.BookID,
		arg.Title,
		arg.Author,
		arg.NewPriceBdt,
		arg.CoverSeed,
		arg.Condition,
		arg.Flags,
		arg.QuoteBdt,
		arg.PickupAddress,
		arg.CreatedAt,
	)
	return err
}

const listSellBackQueue = `-- name: ListSellBackQueue :many
SELECT sell_backs.id, sell_backs.user_id, sell_backs.book_id, sell_backs.title, sell_backs.author, sell_backs.new_price_bdt, sell_backs.cover_seed, sell_backs.condition, sell_backs.flags, sell_backs.quote_bdt, sell_backs.status, sell_backs.pickup_address, sell_backs.created_at, sell_backs.graded_condition, sell_backs.paid_bdt, u.name AS reader_name
FROM sell_backs JOIN users u ON u.id = sell_backs.user_id
WHERE sell_backs.status = 'pickedUp' ORDER BY sell_backs.created_at, sell_backs.id
`

type ListSellBackQueueRow struct {
	SellBack   SellBack
	ReaderName string
}

func (q *Queries) ListSellBackQueue(ctx context.Context) ([]ListSellBackQueueRow, error) {
	rows, err := q.db.Query(ctx, listSellBackQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSellBackQueueRow{}
	for rows.Next() {
		var i ListSellBackQueueRow
		if err := rows.Scan(
			&i.SellBack.ID,
			&i.SellBack.UserID,
			&i.SellBack.BookID,
			&i.SellBack.Title,
			&i.SellBack.Author,
			&i.SellBack.NewPriceBdt,
			&i.SellBack.CoverSeed,
			&i.SellBack.Condition,
			&i.SellBack.Flags,
			&i.SellBack.QuoteBdt,
			&i.SellBack.Status,
			&i.SellBack.PickupAddress,
			&i.SellBack.CreatedAt,
			&i.SellBack.GradedCondition,
			&i.SellBack.PaidBdt,
			&i.ReaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellBacksOf = `-- name: ListSellBacksOf :many
SELECT id, user_id, book_id, title, author, new_price_bdt, cover_seed, condition, flags, quote_bdt, status, pickup_address, created_at, graded_condition, paid_bdt FROM sell_backs WHERE user_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListSellBacksOf(ctx context.Context, userID string) ([]SellBack, error) {
	rows, err := q.db.Query(ctx, listSellBacksOf, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SellBack{}
	for rows.Next() {
		var i SellBack
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Title,
			&i.Author,
			&i.NewPriceBdt,
			&i.CoverSeed,
			&i.Condition,
			&i.Flags,
			&i.QuoteBdt,
			&i.Status,
			&i.PickupAddress,
			&i.CreatedAt,
			&i.GradedCondition,
			&i.PaidBdt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSellBack = `-- name: LockSellBack :one
SELECT id, user_id, book_id, title, author, new_price_bdt, cover_seed, condition, flags, quote_bdt, status, pickup_address, created_at, graded_condition, paid_bdt FROM sell_backs WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockSellBack(ctx context.Context, id string) (SellBack, error) {
	row := q.db.QueryRow(ctx, lockSellBack, id)
	var i SellBack
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Title,
		&i.Author,
		&i.NewPriceBdt,
		&i.CoverSeed,
		&i.Condition,
		&i.Flags,
		&i.QuoteBdt,
		&i.Status,
		&i.PickupAddress,
		&i.CreatedAt,
		&i.GradedCondition,
		&i.PaidBdt,
	)
	return i, err
}

const nextSellBackNumber = `-- name: NextSellBackNumber :one
SELECT nextval('sell_back_seq')::bigint
`

func (q *Queries) NextSellBackNumber(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextSellBackNumber)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const pickUpDue = `-- name: PickUpDue :many
UPDATE sell_backs SET status = 'pickedUp' WHERE status = 'scheduled' AND created_at <= $1 RETURNING id
`

// The courier job: every pickup booked before due is collected (catches up after a sleep).
func (q *Queries) PickUpDue(ctx context.Context, createdAt time.Time) ([]string, error) {
	rows, err := q.db.Query(ctx, pickUpDue, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedCertified = `-- name: SeedCertified :exec
INSERT INTO certified_used (id, book_id, condition, price_bdt, created_at) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO NOTHING
`

type SeedCertifiedParams struct {
	ID        string
	BookID    string
	Condition string
	PriceBdt  int32
	CreatedAt time.Time
}

func (q *Queries) SeedCertified(ctx context.Context, arg SeedCertifiedParams) error {
	_, err := q.db.Exec(ctx, seedCertified,
		arg.ID,
		arg.BookID,
		arg.Condition,
		arg.PriceBdt,
		arg.CreatedAt,
	)
	return err
}

const seedSellBack = `-- name: SeedSellBack :exec
INSERT INTO sell_backs (id, user_id, book_id, title, author, new_price_bdt, cover_seed, condition, flags, quote_bdt, status, pickup_address,
                        created_at, graded_condition, paid_bdt)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (id) DO NOTHING
`

type SeedSellBackParams struct {
	ID              string
	UserID          string
	BookID          string
	Title           string
	Author          string
	NewPriceBdt     int32
	CoverSeed       int32
	Condition       string
	Flags           int32
	QuoteBdt        int32
	Status          string
	PickupAddress   string
	CreatedAt       time.Time
	GradedCondition pgtype.Text
	PaidBdt         pgtype.Int4
}

func (q *Queries) SeedSellBack(ctx context.Context, arg SeedSellBackParams) error {
	_, err := q.db.Exec(ctx, seedSellBack,
		arg.ID,
		arg.UserID,
		arg.BookID,
		arg.Title,
		arg.Author,
		arg.NewPriceBdt,
		arg.CoverSeed,
		arg.Condition,
		arg.Flags,
		arg.QuoteBdt,
		arg.Status,
		arg.PickupAddress,
		arg.CreatedAt,
		arg.GradedCondition,
		arg.PaidBdt,
	)
	return err
}

const sellCertified = `-- name: SellCertified :execrows
UPDATE certified_used SET sold_at = $2 WHERE id = $1 AND sold_at IS NULL
`

type SellCertifiedParams struct {
	ID     string
	SoldAt pgtype.Timestamptz
}

func (q *Queries) SellCertified(ctx context.Context, arg SellCertifiedParams) (int64, error) {
	result, err := q.db.Exec(ctx, sellCertified, arg.ID, arg.SoldAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
