// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: shelves.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReadingDay = `-- name: AddReadingDay :exec
INSERT INTO reading_days (user_id, day) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddReadingDayParams struct {
	UserID string
	Day    time.Time
}

func (q *Queries) AddReadingDay(ctx context.Context, arg AddReadingDayParams) error {
	_, err := q.db.Exec(ctx, addReadingDay, arg.UserID, arg.Day)
	return err
}

const addShelfEntryIfAbsent = `-- name: AddShelfEntryIfAbsent :exec
INSERT INTO shelf_entries (user_id, book_id, shelf, added_at) VALUES ($1, $2, 'wantToRead', $3) ON CONFLICT DO NOTHING
`

type AddShelfEntryIfAbsentParams struct {
	UserID  string
	BookID  string
	AddedAt time.Time
}

func (q *Queries) AddShelfEntryIfAbsent(ctx context.Context, arg AddShelfEntryIfAbsentParams) error {
	_, err := q.db.Exec(ctx, addShelfEntryIfAbsent, arg.UserID, arg.BookID, arg.AddedAt)
	return err
}

const deleteShelfEntry = `-- name: DeleteShelfEntry :exec
DELETE FROM shelf_entries WHERE user_id = $1 AND book_id = $2
`

type DeleteShelfEntryParams struct {
	UserID string
	BookID string
}

func (q *Queries) DeleteShelfEntry(ctx context.Context, arg DeleteShelfEntryParams) error {
	_, err := q.db.Exec(ctx, deleteShelfEntry, arg.UserID, arg.BookID)
	return err
}

const getReadingGoal = `-- name: GetReadingGoal :one
SELECT goal FROM reading_goals WHERE user_id = $1 AND year = $2
`

type GetReadingGoalParams struct {
	UserID string
	Year   int32
}

func (q *Queries) GetReadingGoal(ctx context.Context, arg GetReadingGoalParams) (int32, error) {
	row := q.db.QueryRow(ctx, getReadingGoal, arg.UserID, arg.Year)
	var goal int32
	err := row.Scan(&goal)
	return goal, err
}

const getShelfEntry = `-- name: GetShelfEntry :one
SELECT user_id, position, book_id, shelf, added_at, finished_at, progress, pages_read, total_pages FROM shelf_entries WHERE user_id = $1 AND book_id = $2
`

type GetShelfEntryParams struct {
	UserID string
	BookID string
}

func (q *Queries) GetShelfEntry(ctx context.Context, arg GetShelfEntryParams) (ShelfEntry, error) {
	row := q.db.QueryRow(ctx, getShelfEntry, arg.UserID, arg.BookID)
	var i ShelfEntry
	err := row.Scan(
		&i.UserID,
		&i.Position,
		&i.BookID,
		&i.Shelf,
		&i.AddedAt,
		&i.FinishedAt,
		&i.Progress,
		&i.PagesRead,
		&i.TotalPages,
	)
	return i, err
}

const listReadingDays = `-- name: ListReadingDays :many
SELECT day FROM reading_days WHERE user_id = $1 AND day >= $2 ORDER BY day DESC
`

type ListReadingDaysParams struct {
	UserID string
	Day    time.Time
}

func (q *Queries) ListReadingDays(ctx context.Context, arg ListReadingDaysParams) ([]time.Time, error) {
	rows, err := q.db.Query(ctx, listReadingDays, arg.UserID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []time.Time{}
	for rows.Next() {
		var day time.Time
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShelf = `-- name: ListShelf :many
SELECT user_id, position, book_id, shelf, added_at, finished_at, progress, pages_read, total_pages FROM shelf_entries WHERE user_id = $1 ORDER BY added_at DESC, position
`

func (q *Queries) ListShelf(ctx context.Context, userID string) ([]ShelfEntry, error) {
	rows, err := q.db.Query(ctx, listShelf, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShelfEntry{}
	for rows.Next() {
		var i ShelfEntry
		if err := rows.Scan(
			&i.UserID,
			&i.Position,
			&i.BookID,
			&i.Shelf,
			&i.AddedAt,
			&i.FinishedAt,
			&i.Progress,
			&i.PagesRead,
			&i.TotalPages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markShelfSynced = `-- name: MarkShelfSynced :execrows
INSERT INTO shelf_order_sync (user_id, book_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type MarkShelfSyncedParams struct {
	UserID string
	BookID string
}

func (q *Queries) MarkShelfSynced(ctx context.Context, arg MarkShelfSyncedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markShelfSynced, arg.UserID, arg.BookID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const putShelfEntry = `-- name: PutShelfEntry :exec
INSERT INTO shelf_entries (user_id, book_id, shelf, added_at, finished_at, progress, pages_read, total_pages)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id, book_id) DO UPDATE SET shelf = excluded.shelf, added_at = excluded.added_at, finished_at = excluded.finished_at,
    progress = excluded.progress, pages_read = excluded.pages_read, total_pages = excluded.total_pages
`

type PutShelfEntryParams struct {
	UserID     string
	BookID     string
	Shelf      string
	AddedAt    time.Time
	FinishedAt pgtype.Timestamptz
	Progress   int32
	PagesRead  pgtype.Int4
	TotalPages pgtype.Int4
}

func (q *Queries) PutShelfEntry(ctx context.Context, arg PutShelfEntryParams) error {
	_, err := q.db.Exec(ctx, putShelfEntry,
		arg.UserID,
		arg.BookID,
		arg.Shelf,
		arg.AddedAt,
		arg.FinishedAt,
		arg.Progress,
		arg.PagesRead,
		arg.TotalPages,
	)
	return err
}

const seedReadingGoal = `-- name: SeedReadingGoal :exec
INSERT INTO reading_goals (user_id, year, goal) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type SeedReadingGoalParams struct {
	UserID string
	Year   int32
	Goal   int32
}

func (q *Queries) SeedReadingGoal(ctx context.Context, arg SeedReadingGoalParams) error {
	_, err := q.db.Exec(ctx, seedReadingGoal, arg.UserID, arg.Year, arg.Goal)
	return err
}

const seedShelfEntry = `-- name: SeedShelfEntry :exec
INSERT INTO shelf_entries (user_id, book_id, shelf, added_at, finished_at, progress, pages_read, total_pages)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) ON CONFLICT DO NOTHING
`

type SeedShelfEntryParams struct {
	UserID     string
	BookID     string
	Shelf      string
	AddedAt    time.Time
	FinishedAt pgtype.Timestamptz
	Progress   int32
	PagesRead  pgtype.Int4
	TotalPages pgtype.Int4
}

func (q *Queries) SeedShelfEntry(ctx context.Context, arg SeedShelfEntryParams) error {
	_, err := q.db.Exec(ctx, seedShelfEntry,
		arg.UserID,
		arg.BookID,
		arg.Shelf,
		arg.AddedAt,
		arg.FinishedAt,
		arg.Progress,
		arg.PagesRead,
		arg.TotalPages,
	)
	return err
}

const setReadingGoal = `-- name: SetReadingGoal :exec
INSERT INTO reading_goals (user_id, year, goal) VALUES ($1, $2, $3) ON CONFLICT (user_id, year) DO UPDATE SET goal = excluded.goal
`

type SetReadingGoalParams struct {
	UserID string
	Year   int32
	Goal   int32
}

func (q *Queries) SetReadingGoal(ctx context.Context, arg SetReadingGoalParams) error {
	_, err := q.db.Exec(ctx, setReadingGoal, arg.UserID, arg.Year, arg.Goal)
	return err
}
