// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, phone, name, password_hash, role, photo_url, area, district, member_since, strikes, banned, deleted_at, created_at, photo_data FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.PhotoUrl,
		&i.Area,
		&i.District,
		&i.MemberSince,
		&i.Strikes,
		&i.Banned,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.PhotoData,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, phone, name, password_hash, role, photo_url, area, district, member_since, strikes, banned, deleted_at, created_at, photo_data FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.PhotoUrl,
		&i.Area,
		&i.District,
		&i.MemberSince,
		&i.Strikes,
		&i.Banned,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.PhotoData,
	)
	return i, err
}
